//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfDrivingDailyAggregateService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UBIServiceRequest", Namespace="http://schemas.datacontract.org/2004/07/Progressive.UBI.Shared.UBIServicesLib")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WcfDrivingDailyAggregateService.GetDrivingDailyAggregateRequest))]
    public partial class UBIServiceRequest : object
    {
        
        private int VersionField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Version
        {
            get
            {
                return this.VersionField;
            }
            set
            {
                this.VersionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetDrivingDailyAggregateRequest", Namespace="http://schemas.datacontract.org/2004/07/MyRateReportingServices")]
    public partial class GetDrivingDailyAggregateRequest : WcfDrivingDailyAggregateService.UBIServiceRequest
    {
        
        private System.DateTime BeginField;
        
        private System.DateTime EndField;
        
        private int ParticipantSeqIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Begin
        {
            get
            {
                return this.BeginField;
            }
            set
            {
                this.BeginField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime End
        {
            get
            {
                return this.EndField;
            }
            set
            {
                this.EndField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ParticipantSeqID
        {
            get
            {
                return this.ParticipantSeqIDField;
            }
            set
            {
                this.ParticipantSeqIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UBIServiceResponse", Namespace="http://schemas.datacontract.org/2004/07/Progressive.UBI.Shared.UBIServicesLib")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WcfDrivingDailyAggregateService.GetDrivingDailyAggregateResponse))]
    public partial class UBIServiceResponse : object
    {
        
        private WcfDrivingDailyAggregateService.ResponseError[] ResponseErrorsField;
        
        private WcfDrivingDailyAggregateService.ResponseStatus ResponseStatusField;
        
        private int VersionField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public WcfDrivingDailyAggregateService.ResponseError[] ResponseErrors
        {
            get
            {
                return this.ResponseErrorsField;
            }
            set
            {
                this.ResponseErrorsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public WcfDrivingDailyAggregateService.ResponseStatus ResponseStatus
        {
            get
            {
                return this.ResponseStatusField;
            }
            set
            {
                this.ResponseStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Version
        {
            get
            {
                return this.VersionField;
            }
            set
            {
                this.VersionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetDrivingDailyAggregateResponse", Namespace="http://schemas.datacontract.org/2004/07/MyRateReportingServices")]
    public partial class GetDrivingDailyAggregateResponse : WcfDrivingDailyAggregateService.UBIServiceResponse
    {
        
        private WcfDrivingDailyAggregateService.DailyDrivingAggregate[] DailyDrivingAggregatesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WcfDrivingDailyAggregateService.DailyDrivingAggregate[] DailyDrivingAggregates
        {
            get
            {
                return this.DailyDrivingAggregatesField;
            }
            set
            {
                this.DailyDrivingAggregatesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseError", Namespace="http://schemas.datacontract.org/2004/07/Progressive.UBI.Shared.UBIServicesLib")]
    public partial class ResponseError : object
    {
        
        private string ErrorCodeField;
        
        private string FieldField;
        
        private string MessageField;
        
        private WcfDrivingDailyAggregateService.ErrorSeverityCode SeverityCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorCode
        {
            get
            {
                return this.ErrorCodeField;
            }
            set
            {
                this.ErrorCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Field
        {
            get
            {
                return this.FieldField;
            }
            set
            {
                this.FieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WcfDrivingDailyAggregateService.ErrorSeverityCode SeverityCode
        {
            get
            {
                return this.SeverityCodeField;
            }
            set
            {
                this.SeverityCodeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseStatus", Namespace="http://schemas.datacontract.org/2004/07/Progressive.UBI.Shared.UBIServicesLib")]
    public enum ResponseStatus : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Failure = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SuccessWithWarning = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FailureWithWarning = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PartialSuccess = 5,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DailyDrivingAggregate", Namespace="http://schemas.datacontract.org/2004/07/MyRateReportingServices")]
    public partial class DailyDrivingAggregate : object
    {
        
        private System.Nullable<int> HardAccelerationsField;
        
        private System.Nullable<int> HardBrakesField;
        
        private System.Nullable<int> HighRiskSecondsField;
        
        private int TripCountField;
        
        private System.DateTime TripDateField;
        
        private int TripDurationField;
        
        private decimal TripMileageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> HardAccelerations
        {
            get
            {
                return this.HardAccelerationsField;
            }
            set
            {
                this.HardAccelerationsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> HardBrakes
        {
            get
            {
                return this.HardBrakesField;
            }
            set
            {
                this.HardBrakesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> HighRiskSeconds
        {
            get
            {
                return this.HighRiskSecondsField;
            }
            set
            {
                this.HighRiskSecondsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TripCount
        {
            get
            {
                return this.TripCountField;
            }
            set
            {
                this.TripCountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TripDate
        {
            get
            {
                return this.TripDateField;
            }
            set
            {
                this.TripDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TripDuration
        {
            get
            {
                return this.TripDurationField;
            }
            set
            {
                this.TripDurationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TripMileage
        {
            get
            {
                return this.TripMileageField;
            }
            set
            {
                this.TripMileageField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ErrorSeverityCode", Namespace="http://schemas.datacontract.org/2004/07/Progressive.UBI.Shared.UBIServicesLib")]
    public enum ErrorSeverityCode : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Warning = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Validation = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Exception = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Ticket = 5,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WcfDrivingDailyAggregateService.IGetDrivingDailyAggregateService")]
    public interface IGetDrivingDailyAggregateService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGetDrivingDailyAggregateService/Get", ReplyAction="http://tempuri.org/IGetDrivingDailyAggregateService/GetResponse")]
        System.Threading.Tasks.Task<WcfDrivingDailyAggregateService.GetDrivingDailyAggregateResponse> GetAsync(WcfDrivingDailyAggregateService.GetDrivingDailyAggregateRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface IGetDrivingDailyAggregateServiceChannel : WcfDrivingDailyAggregateService.IGetDrivingDailyAggregateService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class GetDrivingDailyAggregateServiceClient : System.ServiceModel.ClientBase<WcfDrivingDailyAggregateService.IGetDrivingDailyAggregateService>, WcfDrivingDailyAggregateService.IGetDrivingDailyAggregateService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);

        public GetDrivingDailyAggregateServiceClient() :
               base(GetDrivingDailyAggregateServiceClient.GetDefaultBinding(), GetDrivingDailyAggregateServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.WSHttpBinding_IGetDrivingDailyAggregateService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public GetDrivingDailyAggregateServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(GetDrivingDailyAggregateServiceClient.GetBindingForEndpoint(endpointConfiguration), GetDrivingDailyAggregateServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GetDrivingDailyAggregateServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(GetDrivingDailyAggregateServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GetDrivingDailyAggregateServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(GetDrivingDailyAggregateServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GetDrivingDailyAggregateServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<WcfDrivingDailyAggregateService.GetDrivingDailyAggregateResponse> GetAsync(WcfDrivingDailyAggregateService.GetDrivingDailyAggregateRequest request)
        {
            return base.Channel.GetAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }

        public static System.ServiceModel.Channels.Binding DefaultBinding()
        {
            return GetBindingForEndpoint(EndpointConfiguration.WSHttpBinding_IGetDrivingDailyAggregateService);
        }

        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WSHttpBinding_IGetDrivingDailyAggregateService))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.WSHttpBinding_IGetDrivingDailyAggregateService1))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }

        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WSHttpBinding_IGetDrivingDailyAggregateService))
            {
                return new System.ServiceModel.EndpointAddress("http://t-ubi-myrate-services/MyRateReportingServices/Services/GetDrivingDailyAggr" +
                        "egateService.svc");
            }
            if ((endpointConfiguration == EndpointConfiguration.WSHttpBinding_IGetDrivingDailyAggregateService1))
            {
                return new System.ServiceModel.EndpointAddress("http://t-ubi-myrate-services/MyRateReportingServices/Services/GetDrivingDailyAggr" +
                        "egateService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }

        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return GetDrivingDailyAggregateServiceClient.GetBindingForEndpoint(EndpointConfiguration.WSHttpBinding_IGetDrivingDailyAggregateService);
        }

        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return GetDrivingDailyAggregateServiceClient.GetEndpointAddress(EndpointConfiguration.WSHttpBinding_IGetDrivingDailyAggregateService);
        }

        public enum EndpointConfiguration
        {
            
            WSHttpBinding_IGetDrivingDailyAggregateService,
            
            WSHttpBinding_IGetDrivingDailyAggregateService1,
        }
    }
}
