//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFBusinessDeviceOrderService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UBIServiceRequest", Namespace="http://schemas.datacontract.org/2004/07/Progressive.UBI.Shared.UBIServicesLib")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WCFBusinessDeviceOrderService.GetBusinessDeviceOrderByParticipantGroupRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WCFBusinessDeviceOrderService.GetBusinessDeviceOrderByOrderStatusRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WCFBusinessDeviceOrderService.GetBusinessDeviceOrderRequest))]
    public partial class UBIServiceRequest : object
    {
        
        private int VersionField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Version
        {
            get
            {
                return this.VersionField;
            }
            set
            {
                this.VersionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetBusinessDeviceOrderByParticipantGroupRequest", Namespace="http://schemas.datacontract.org/2004/07/MyScoreBusiness.Commands.BusinessDeviceOr" +
        "der.Get.Contract")]
    public partial class GetBusinessDeviceOrderByParticipantGroupRequest : WCFBusinessDeviceOrderService.UBIServiceRequest
    {
        
        private int ParticipantGroupSeqIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ParticipantGroupSeqID
        {
            get
            {
                return this.ParticipantGroupSeqIDField;
            }
            set
            {
                this.ParticipantGroupSeqIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetBusinessDeviceOrderByOrderStatusRequest", Namespace="http://schemas.datacontract.org/2004/07/MyScoreBusiness.Commands.BusinessDeviceOr" +
        "der.Get.Contract")]
    public partial class GetBusinessDeviceOrderByOrderStatusRequest : WCFBusinessDeviceOrderService.UBIServiceRequest
    {
        
        private int OrderStatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrderStatus
        {
            get
            {
                return this.OrderStatusField;
            }
            set
            {
                this.OrderStatusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetBusinessDeviceOrderRequest", Namespace="http://schemas.datacontract.org/2004/07/MyScoreBusiness.Commands.BusinessDeviceOr" +
        "der.Get.Contract")]
    public partial class GetBusinessDeviceOrderRequest : WCFBusinessDeviceOrderService.UBIServiceRequest
    {
        
        private int DeviceOrderSeqIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int DeviceOrderSeqID
        {
            get
            {
                return this.DeviceOrderSeqIDField;
            }
            set
            {
                this.DeviceOrderSeqIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UBIServiceResponse", Namespace="http://schemas.datacontract.org/2004/07/Progressive.UBI.Shared.UBIServicesLib")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WCFBusinessDeviceOrderService.GetBusinessDeviceOrderResponse))]
    public partial class UBIServiceResponse : object
    {
        
        private WCFBusinessDeviceOrderService.ResponseError[] ResponseErrorsField;
        
        private WCFBusinessDeviceOrderService.ResponseStatus ResponseStatusField;
        
        private int VersionField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public WCFBusinessDeviceOrderService.ResponseError[] ResponseErrors
        {
            get
            {
                return this.ResponseErrorsField;
            }
            set
            {
                this.ResponseErrorsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public WCFBusinessDeviceOrderService.ResponseStatus ResponseStatus
        {
            get
            {
                return this.ResponseStatusField;
            }
            set
            {
                this.ResponseStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Version
        {
            get
            {
                return this.VersionField;
            }
            set
            {
                this.VersionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetBusinessDeviceOrderResponse", Namespace="http://schemas.datacontract.org/2004/07/MyScoreBusiness.Commands.BusinessDeviceOr" +
        "der.Get.Contract")]
    public partial class GetBusinessDeviceOrderResponse : WCFBusinessDeviceOrderService.UBIServiceResponse
    {
        
        private WCFBusinessDeviceOrderService.BusinessDeviceOrder[] BusinessDeviceOrderListField;
        
        private int RecordCountField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public WCFBusinessDeviceOrderService.BusinessDeviceOrder[] BusinessDeviceOrderList
        {
            get
            {
                return this.BusinessDeviceOrderListField;
            }
            set
            {
                this.BusinessDeviceOrderListField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int RecordCount
        {
            get
            {
                return this.RecordCountField;
            }
            set
            {
                this.RecordCountField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseError", Namespace="http://schemas.datacontract.org/2004/07/Progressive.UBI.Shared.UBIServicesLib")]
    public partial class ResponseError : object
    {
        
        private string ErrorCodeField;
        
        private string FieldField;
        
        private string MessageField;
        
        private WCFBusinessDeviceOrderService.ErrorSeverityCode SeverityCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorCode
        {
            get
            {
                return this.ErrorCodeField;
            }
            set
            {
                this.ErrorCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Field
        {
            get
            {
                return this.FieldField;
            }
            set
            {
                this.FieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WCFBusinessDeviceOrderService.ErrorSeverityCode SeverityCode
        {
            get
            {
                return this.SeverityCodeField;
            }
            set
            {
                this.SeverityCodeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseStatus", Namespace="http://schemas.datacontract.org/2004/07/Progressive.UBI.Shared.UBIServicesLib")]
    public enum ResponseStatus : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Failure = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SuccessWithWarning = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FailureWithWarning = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PartialSuccess = 5,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BusinessDeviceOrder", Namespace="http://schemas.datacontract.org/2004/07/MyScoreBusiness.Commands.BusinessDeviceOr" +
        "der")]
    public partial class BusinessDeviceOrder : object
    {
        
        private WCFBusinessDeviceOrderService.DeviceOrder DeviceOrderField;
        
        private WCFBusinessDeviceOrderService.BusinessDeviceOrderDetail[] DeviceOrderDetailsField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public WCFBusinessDeviceOrderService.DeviceOrder DeviceOrder
        {
            get
            {
                return this.DeviceOrderField;
            }
            set
            {
                this.DeviceOrderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public WCFBusinessDeviceOrderService.BusinessDeviceOrderDetail[] DeviceOrderDetails
        {
            get
            {
                return this.DeviceOrderDetailsField;
            }
            set
            {
                this.DeviceOrderDetailsField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ErrorSeverityCode", Namespace="http://schemas.datacontract.org/2004/07/Progressive.UBI.Shared.UBIServicesLib")]
    public enum ErrorSeverityCode : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Warning = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Validation = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Exception = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Ticket = 5,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeviceOrder", Namespace="http://schemas.datacontract.org/2004/07/MyScoreBusiness.Commands.DeviceOrder")]
    public partial class DeviceOrder : object
    {
        
        private System.DateTime CreateDateTimeField;
        
        private int DeviceOrderSeqIDField;
        
        private int DeviceOrderStatusCodeField;
        
        private string FulfilledByUserIDField;
        
        private int ParticipantGroupSeqIDField;
        
        private System.Nullable<System.DateTime> ProcessedDateTimeField;
        
        private System.Nullable<System.DateTime> ShipDateTimeField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime CreateDateTime
        {
            get
            {
                return this.CreateDateTimeField;
            }
            set
            {
                this.CreateDateTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int DeviceOrderSeqID
        {
            get
            {
                return this.DeviceOrderSeqIDField;
            }
            set
            {
                this.DeviceOrderSeqIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int DeviceOrderStatusCode
        {
            get
            {
                return this.DeviceOrderStatusCodeField;
            }
            set
            {
                this.DeviceOrderStatusCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FulfilledByUserID
        {
            get
            {
                return this.FulfilledByUserIDField;
            }
            set
            {
                this.FulfilledByUserIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ParticipantGroupSeqID
        {
            get
            {
                return this.ParticipantGroupSeqIDField;
            }
            set
            {
                this.ParticipantGroupSeqIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ProcessedDateTime
        {
            get
            {
                return this.ProcessedDateTimeField;
            }
            set
            {
                this.ProcessedDateTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ShipDateTime
        {
            get
            {
                return this.ShipDateTimeField;
            }
            set
            {
                this.ShipDateTimeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BusinessDeviceOrderDetail", Namespace="http://schemas.datacontract.org/2004/07/MyScoreBusiness.Commands.BusinessDeviceOr" +
        "derDetail")]
    public partial class BusinessDeviceOrderDetail : object
    {
        
        private bool DeviceAvailableField;
        
        private WCFBusinessDeviceOrderService.DeviceOrderDetail DeviceOrderDetailField;
        
        private string DeviceSerialNbrField;
        
        private string MessageField;
        
        private WCFBusinessDeviceOrderService.Participant ParticipantField;
        
        private WCFBusinessDeviceOrderService.Vehicle VehicleField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool DeviceAvailable
        {
            get
            {
                return this.DeviceAvailableField;
            }
            set
            {
                this.DeviceAvailableField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public WCFBusinessDeviceOrderService.DeviceOrderDetail DeviceOrderDetail
        {
            get
            {
                return this.DeviceOrderDetailField;
            }
            set
            {
                this.DeviceOrderDetailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeviceSerialNbr
        {
            get
            {
                return this.DeviceSerialNbrField;
            }
            set
            {
                this.DeviceSerialNbrField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public WCFBusinessDeviceOrderService.Participant Participant
        {
            get
            {
                return this.ParticipantField;
            }
            set
            {
                this.ParticipantField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public WCFBusinessDeviceOrderService.Vehicle Vehicle
        {
            get
            {
                return this.VehicleField;
            }
            set
            {
                this.VehicleField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeviceOrderDetail", Namespace="http://schemas.datacontract.org/2004/07/MyScoreBusiness.Commands.DeviceOrderDetai" +
        "l")]
    public partial class DeviceOrderDetail : object
    {
        
        private System.DateTime CreateDateTimeField;
        
        private int DeviceOrderDetailSeqIDField;
        
        private int DeviceOrderSeqIDField;
        
        private System.Nullable<int> DeviceSeqIDField;
        
        private bool IsReplacementOrderField;
        
        private int ParticipantSeqIDField;
        
        private int VehicleSeqIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime CreateDateTime
        {
            get
            {
                return this.CreateDateTimeField;
            }
            set
            {
                this.CreateDateTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int DeviceOrderDetailSeqID
        {
            get
            {
                return this.DeviceOrderDetailSeqIDField;
            }
            set
            {
                this.DeviceOrderDetailSeqIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int DeviceOrderSeqID
        {
            get
            {
                return this.DeviceOrderSeqIDField;
            }
            set
            {
                this.DeviceOrderSeqIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> DeviceSeqID
        {
            get
            {
                return this.DeviceSeqIDField;
            }
            set
            {
                this.DeviceSeqIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool IsReplacementOrder
        {
            get
            {
                return this.IsReplacementOrderField;
            }
            set
            {
                this.IsReplacementOrderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ParticipantSeqID
        {
            get
            {
                return this.ParticipantSeqIDField;
            }
            set
            {
                this.ParticipantSeqIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int VehicleSeqID
        {
            get
            {
                return this.VehicleSeqIDField;
            }
            set
            {
                this.VehicleSeqIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Participant", Namespace="http://schemas.datacontract.org/2004/07/MyScoreBusiness.Commands.Participant")]
    public partial class Participant : object
    {
        
        private System.DateTime CreateDateTimeField;
        
        private int DeviceExperienceTypeCodeField;
        
        private System.Nullable<int> DeviceSeqIDField;
        
        private string DriverExternalIdField;
        
        private System.Nullable<int> DriverSeqIdField;
        
        private System.DateTime LastUpdateDateTimeField;
        
        private System.Nullable<int> MobileSummarizerVersionCodeField;
        
        private string NicknameField;
        
        private string ParticipantExternalIdField;
        
        private int ParticipantGroupSeqIDField;
        
        private System.Nullable<System.Guid> ParticipantIdField;
        
        private int ParticipantSeqIDField;
        
        private int ParticipantStatusCodeField;
        
        private int ScoreCalculatorCodeField;
        
        private System.Nullable<int> ScoringAlgorithmCodeField;
        
        private int VehicleSeqIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime CreateDateTime
        {
            get
            {
                return this.CreateDateTimeField;
            }
            set
            {
                this.CreateDateTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int DeviceExperienceTypeCode
        {
            get
            {
                return this.DeviceExperienceTypeCodeField;
            }
            set
            {
                this.DeviceExperienceTypeCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> DeviceSeqID
        {
            get
            {
                return this.DeviceSeqIDField;
            }
            set
            {
                this.DeviceSeqIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DriverExternalId
        {
            get
            {
                return this.DriverExternalIdField;
            }
            set
            {
                this.DriverExternalIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> DriverSeqId
        {
            get
            {
                return this.DriverSeqIdField;
            }
            set
            {
                this.DriverSeqIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime LastUpdateDateTime
        {
            get
            {
                return this.LastUpdateDateTimeField;
            }
            set
            {
                this.LastUpdateDateTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> MobileSummarizerVersionCode
        {
            get
            {
                return this.MobileSummarizerVersionCodeField;
            }
            set
            {
                this.MobileSummarizerVersionCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nickname
        {
            get
            {
                return this.NicknameField;
            }
            set
            {
                this.NicknameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ParticipantExternalId
        {
            get
            {
                return this.ParticipantExternalIdField;
            }
            set
            {
                this.ParticipantExternalIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ParticipantGroupSeqID
        {
            get
            {
                return this.ParticipantGroupSeqIDField;
            }
            set
            {
                this.ParticipantGroupSeqIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> ParticipantId
        {
            get
            {
                return this.ParticipantIdField;
            }
            set
            {
                this.ParticipantIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ParticipantSeqID
        {
            get
            {
                return this.ParticipantSeqIDField;
            }
            set
            {
                this.ParticipantSeqIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ParticipantStatusCode
        {
            get
            {
                return this.ParticipantStatusCodeField;
            }
            set
            {
                this.ParticipantStatusCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ScoreCalculatorCode
        {
            get
            {
                return this.ScoreCalculatorCodeField;
            }
            set
            {
                this.ScoreCalculatorCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ScoringAlgorithmCode
        {
            get
            {
                return this.ScoringAlgorithmCodeField;
            }
            set
            {
                this.ScoringAlgorithmCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int VehicleSeqID
        {
            get
            {
                return this.VehicleSeqIDField;
            }
            set
            {
                this.VehicleSeqIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Vehicle", Namespace="http://schemas.datacontract.org/2004/07/MyScoreBusiness.Commands.Vehicle")]
    public partial class Vehicle : object
    {
        
        private System.DateTime CreateDateTimeField;
        
        private string MakeField;
        
        private string ModelField;
        
        private string VINField;
        
        private string VehicleExternalIdField;
        
        private int VehicleSeqIDField;
        
        private short YearField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime CreateDateTime
        {
            get
            {
                return this.CreateDateTimeField;
            }
            set
            {
                this.CreateDateTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Make
        {
            get
            {
                return this.MakeField;
            }
            set
            {
                this.MakeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Model
        {
            get
            {
                return this.ModelField;
            }
            set
            {
                this.ModelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VIN
        {
            get
            {
                return this.VINField;
            }
            set
            {
                this.VINField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VehicleExternalId
        {
            get
            {
                return this.VehicleExternalIdField;
            }
            set
            {
                this.VehicleExternalIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int VehicleSeqID
        {
            get
            {
                return this.VehicleSeqIDField;
            }
            set
            {
                this.VehicleSeqIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public short Year
        {
            get
            {
                return this.YearField;
            }
            set
            {
                this.YearField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCFBusinessDeviceOrderService.IBusinessDeviceOrderService")]
    public interface IBusinessDeviceOrderService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessDeviceOrderService/GetBusinessDeviceOrder", ReplyAction="http://tempuri.org/IBusinessDeviceOrderService/GetBusinessDeviceOrderResponse")]
        System.Threading.Tasks.Task<WCFBusinessDeviceOrderService.GetBusinessDeviceOrderResponse> GetBusinessDeviceOrderAsync(WCFBusinessDeviceOrderService.GetBusinessDeviceOrderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessDeviceOrderService/GetBusinessDeviceOrderByParticipan" +
            "tGroup", ReplyAction="http://tempuri.org/IBusinessDeviceOrderService/GetBusinessDeviceOrderByParticipan" +
            "tGroupResponse")]
        System.Threading.Tasks.Task<WCFBusinessDeviceOrderService.GetBusinessDeviceOrderResponse> GetBusinessDeviceOrderByParticipantGroupAsync(WCFBusinessDeviceOrderService.GetBusinessDeviceOrderByParticipantGroupRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBusinessDeviceOrderService/GetBusinessDeviceOrderByOrderStatu" +
            "s", ReplyAction="http://tempuri.org/IBusinessDeviceOrderService/GetBusinessDeviceOrderByOrderStatu" +
            "sResponse")]
        System.Threading.Tasks.Task<WCFBusinessDeviceOrderService.GetBusinessDeviceOrderResponse> GetBusinessDeviceOrderByOrderStatusAsync(WCFBusinessDeviceOrderService.GetBusinessDeviceOrderByOrderStatusRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface IBusinessDeviceOrderServiceChannel : WCFBusinessDeviceOrderService.IBusinessDeviceOrderService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class BusinessDeviceOrderServiceClient : System.ServiceModel.ClientBase<WCFBusinessDeviceOrderService.IBusinessDeviceOrderService>, WCFBusinessDeviceOrderService.IBusinessDeviceOrderService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public BusinessDeviceOrderServiceClient() : 
                base(BusinessDeviceOrderServiceClient.GetDefaultBinding(), BusinessDeviceOrderServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.WSHttpBinding_IBusinessDeviceOrderService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BusinessDeviceOrderServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(BusinessDeviceOrderServiceClient.GetBindingForEndpoint(endpointConfiguration), BusinessDeviceOrderServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BusinessDeviceOrderServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(BusinessDeviceOrderServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BusinessDeviceOrderServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(BusinessDeviceOrderServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BusinessDeviceOrderServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<WCFBusinessDeviceOrderService.GetBusinessDeviceOrderResponse> GetBusinessDeviceOrderAsync(WCFBusinessDeviceOrderService.GetBusinessDeviceOrderRequest request)
        {
            return base.Channel.GetBusinessDeviceOrderAsync(request);
        }
        
        public System.Threading.Tasks.Task<WCFBusinessDeviceOrderService.GetBusinessDeviceOrderResponse> GetBusinessDeviceOrderByParticipantGroupAsync(WCFBusinessDeviceOrderService.GetBusinessDeviceOrderByParticipantGroupRequest request)
        {
            return base.Channel.GetBusinessDeviceOrderByParticipantGroupAsync(request);
        }
        
        public System.Threading.Tasks.Task<WCFBusinessDeviceOrderService.GetBusinessDeviceOrderResponse> GetBusinessDeviceOrderByOrderStatusAsync(WCFBusinessDeviceOrderService.GetBusinessDeviceOrderByOrderStatusRequest request)
        {
            return base.Channel.GetBusinessDeviceOrderByOrderStatusAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WSHttpBinding_IBusinessDeviceOrderService))
            {
                System.ServiceModel.WSHttpBinding result = new System.ServiceModel.WSHttpBinding();
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.SecurityMode.None;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WSHttpBinding_IBusinessDeviceOrderService))
            {
                return new System.ServiceModel.EndpointAddress("http://t-ubi-labs-services/MyScoreBusiness/services/BusinessDeviceOrderService.sv" +
                        "c");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return BusinessDeviceOrderServiceClient.GetBindingForEndpoint(EndpointConfiguration.WSHttpBinding_IBusinessDeviceOrderService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return BusinessDeviceOrderServiceClient.GetEndpointAddress(EndpointConfiguration.WSHttpBinding_IBusinessDeviceOrderService);
        }
        
        public enum EndpointConfiguration
        {
            
            WSHttpBinding_IBusinessDeviceOrderService,
        }
    }
}
