// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Progressive.Telematics.Admin.Services.Models.ClTables
{
    public partial class TripEvent
    {
        public int TripEventSeqId { get; set; }
        public long TripSeqId { get; set; }
        public DateTime TripEventDateTime { get; set; }
        public int TripEventTypeCode { get; set; }
        public byte SpeedKph { get; set; }
        public decimal? LatitudeNbr { get; set; }
        public decimal? LongitudeNbr { get; set; }
        public decimal? EventTimestamp { get; set; }
        public string EventTimeZoneOffsetNbr { get; set; }
        public decimal? LatitudeDeltaNbr { get; set; }
        public decimal? LongitudeDeltaNbr { get; set; }
        public double? EventDurationSeconds { get; set; }

        public virtual TripEventType TripEventTypeCodeNavigation { get; set; }
        public virtual Trip TripSeq { get; set; }
    }
}