// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Progressive.Telematics.Admin.Services.Models.ClTables
{
    public partial class ExcludedDateRange
    {
        public int ParticipantSeqId { get; set; }
        public DateTime RangeStart { get; set; }
        public DateTime RangeEnd { get; set; }
        public string Description { get; set; }
        public DateTime CreateDate { get; set; }

        public virtual Participant ParticipantSeq { get; set; }
    }
}