// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Progressive.Telematics.Admin.Services.Models.ClTables
{
    public partial class Participant
    {
        public Participant()
        {
            BadTrips = new HashSet<BadTrip>();
            DeviceEvents = new HashSet<DeviceEvent>();
            DeviceReturns = new HashSet<DeviceReturn>();
            ExcludedDateRanges = new HashSet<ExcludedDateRange>();
            ParticipantHistories = new HashSet<ParticipantHistory>();
            Trips = new HashSet<Trip>();
        }

        public int ParticipantSeqId { get; set; }
        public int PolicySeqId { get; set; }
        public int VehicleSeqId { get; set; }
        public int? DeviceSeqId { get; set; }
        public int ParticipantStatusCode { get; set; }
        public DateTime LastUpdateDateTime { get; set; }
        public DateTime CreateDateTime { get; set; }
        public int DeviceExperienceTypeCode { get; set; }
        public string ParticipantId { get; set; }
        public DateTime? DashboardEnrollmentDateTime { get; set; }

        public virtual DeviceExperienceType DeviceExperienceTypeCodeNavigation { get; set; }
        public virtual ParticipantStatus ParticipantStatusCodeNavigation { get; set; }
        public virtual Policy PolicySeq { get; set; }
        public virtual Vehicle VehicleSeq { get; set; }
        public virtual ICollection<BadTrip> BadTrips { get; set; }
        public virtual ICollection<DeviceEvent> DeviceEvents { get; set; }
        public virtual ICollection<DeviceReturn> DeviceReturns { get; set; }
        public virtual ICollection<ExcludedDateRange> ExcludedDateRanges { get; set; }
        public virtual ICollection<ParticipantHistory> ParticipantHistories { get; set; }
        public virtual ICollection<Trip> Trips { get; set; }
    }
}