// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Progressive.Telematics.Admin.Services.Models.ClTables
{
    public partial class TripDetailSmoothingAudit
    {
        public int SmoothingSeqId { get; set; }
        public long TripSeqId { get; set; }
        public byte PriorSpeedKph { get; set; }
        public byte BaseSpeedKph { get; set; }
        public byte NextSpeedKph { get; set; }
        public byte SmoothedSpeedKph { get; set; }
        public int PriorElapsedTimeMilliSeconds { get; set; }
        public int BaseElapsedTimeMilliSeconds { get; set; }
        public int NextElapsedTimeMilliSeconds { get; set; }
        public DateTime CreateDate { get; set; }
        public int? SmoothingTypeCode { get; set; }
    }
}