//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFDeviceOrderService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UBIServiceRequest", Namespace="http://schemas.datacontract.org/2004/07/Progressive.UBI.Shared.UBIServicesLib")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WCFDeviceOrderService.UpdateDeviceOrderRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WCFDeviceOrderService.GetDeviceOrderRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WCFDeviceOrderService.FulfillDeviceOrderRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WCFDeviceOrderService.DeleteDeviceOrderRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WCFDeviceOrderService.AddDeviceOrderWithDetailRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WCFDeviceOrderService.AddDeviceOrderRequest))]
    public partial class UBIServiceRequest : object
    {
        
        private int VersionField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Version
        {
            get
            {
                return this.VersionField;
            }
            set
            {
                this.VersionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdateDeviceOrderRequest", Namespace="http://schemas.datacontract.org/2004/07/MyScoreBusiness.Commands.DeviceOrder.Upda" +
        "te.Contract")]
    public partial class UpdateDeviceOrderRequest : WCFDeviceOrderService.UBIServiceRequest
    {
        
        private WCFDeviceOrderService.DeviceOrder DeviceOrderField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public WCFDeviceOrderService.DeviceOrder DeviceOrder
        {
            get
            {
                return this.DeviceOrderField;
            }
            set
            {
                this.DeviceOrderField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetDeviceOrderRequest", Namespace="http://schemas.datacontract.org/2004/07/MyScoreBusiness.Commands.DeviceOrder.Get." +
        "Contract")]
    public partial class GetDeviceOrderRequest : WCFDeviceOrderService.UBIServiceRequest
    {
        
        private int DeviceOrderSeqIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int DeviceOrderSeqID
        {
            get
            {
                return this.DeviceOrderSeqIDField;
            }
            set
            {
                this.DeviceOrderSeqIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FulfillDeviceOrderRequest", Namespace="http://schemas.datacontract.org/2004/07/MyScoreBusiness.Commands.DeviceOrder.Fulf" +
        "ill.Contract")]
    public partial class FulfillDeviceOrderRequest : WCFDeviceOrderService.UBIServiceRequest
    {
        
        private WCFDeviceOrderService.BusinessDeviceOrderDetail[] BusinessDeviceOrderDetailsField;
        
        private int DeviceOrderSeqIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WCFDeviceOrderService.BusinessDeviceOrderDetail[] BusinessDeviceOrderDetails
        {
            get
            {
                return this.BusinessDeviceOrderDetailsField;
            }
            set
            {
                this.BusinessDeviceOrderDetailsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DeviceOrderSeqID
        {
            get
            {
                return this.DeviceOrderSeqIDField;
            }
            set
            {
                this.DeviceOrderSeqIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeleteDeviceOrderRequest", Namespace="http://schemas.datacontract.org/2004/07/MyScoreBusiness.Commands.DeviceOrder.Dele" +
        "te.Contract")]
    public partial class DeleteDeviceOrderRequest : WCFDeviceOrderService.UBIServiceRequest
    {
        
        private int DeviceOrderSeqIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int DeviceOrderSeqID
        {
            get
            {
                return this.DeviceOrderSeqIDField;
            }
            set
            {
                this.DeviceOrderSeqIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddDeviceOrderWithDetailRequest", Namespace="http://schemas.datacontract.org/2004/07/MyScoreBusiness.Commands.DeviceOrder.Add." +
        "Contract")]
    public partial class AddDeviceOrderWithDetailRequest : WCFDeviceOrderService.UBIServiceRequest
    {
        
        private WCFDeviceOrderService.DeviceOrder DeviceOrderField;
        
        private WCFDeviceOrderService.NewDeviceOrderDetail[] DeviceOrderDetailsField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public WCFDeviceOrderService.DeviceOrder DeviceOrder
        {
            get
            {
                return this.DeviceOrderField;
            }
            set
            {
                this.DeviceOrderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public WCFDeviceOrderService.NewDeviceOrderDetail[] DeviceOrderDetails
        {
            get
            {
                return this.DeviceOrderDetailsField;
            }
            set
            {
                this.DeviceOrderDetailsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddDeviceOrderRequest", Namespace="http://schemas.datacontract.org/2004/07/MyScoreBusiness.Commands.DeviceOrder.Add." +
        "Contract")]
    public partial class AddDeviceOrderRequest : WCFDeviceOrderService.UBIServiceRequest
    {
        
        private WCFDeviceOrderService.DeviceOrder DeviceOrderField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public WCFDeviceOrderService.DeviceOrder DeviceOrder
        {
            get
            {
                return this.DeviceOrderField;
            }
            set
            {
                this.DeviceOrderField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeviceOrder", Namespace="http://schemas.datacontract.org/2004/07/MyScoreBusiness.Commands.DeviceOrder")]
    public partial class DeviceOrder : object
    {
        
        private System.DateTime CreateDateTimeField;
        
        private int DeviceOrderSeqIDField;
        
        private int DeviceOrderStatusCodeField;
        
        private string FulfilledByUserIDField;
        
        private int ParticipantGroupSeqIDField;
        
        private System.Nullable<System.DateTime> ProcessedDateTimeField;
        
        private System.Nullable<System.DateTime> ShipDateTimeField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime CreateDateTime
        {
            get
            {
                return this.CreateDateTimeField;
            }
            set
            {
                this.CreateDateTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int DeviceOrderSeqID
        {
            get
            {
                return this.DeviceOrderSeqIDField;
            }
            set
            {
                this.DeviceOrderSeqIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int DeviceOrderStatusCode
        {
            get
            {
                return this.DeviceOrderStatusCodeField;
            }
            set
            {
                this.DeviceOrderStatusCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FulfilledByUserID
        {
            get
            {
                return this.FulfilledByUserIDField;
            }
            set
            {
                this.FulfilledByUserIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ParticipantGroupSeqID
        {
            get
            {
                return this.ParticipantGroupSeqIDField;
            }
            set
            {
                this.ParticipantGroupSeqIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ProcessedDateTime
        {
            get
            {
                return this.ProcessedDateTimeField;
            }
            set
            {
                this.ProcessedDateTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ShipDateTime
        {
            get
            {
                return this.ShipDateTimeField;
            }
            set
            {
                this.ShipDateTimeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BusinessDeviceOrderDetail", Namespace="http://schemas.datacontract.org/2004/07/MyScoreBusiness.Commands.BusinessDeviceOr" +
        "derDetail")]
    public partial class BusinessDeviceOrderDetail : object
    {
        
        private bool DeviceAvailableField;
        
        private WCFDeviceOrderService.DeviceOrderDetail DeviceOrderDetailField;
        
        private string DeviceSerialNbrField;
        
        private string MessageField;
        
        private WCFDeviceOrderService.Participant ParticipantField;
        
        private WCFDeviceOrderService.Vehicle VehicleField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool DeviceAvailable
        {
            get
            {
                return this.DeviceAvailableField;
            }
            set
            {
                this.DeviceAvailableField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public WCFDeviceOrderService.DeviceOrderDetail DeviceOrderDetail
        {
            get
            {
                return this.DeviceOrderDetailField;
            }
            set
            {
                this.DeviceOrderDetailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeviceSerialNbr
        {
            get
            {
                return this.DeviceSerialNbrField;
            }
            set
            {
                this.DeviceSerialNbrField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public WCFDeviceOrderService.Participant Participant
        {
            get
            {
                return this.ParticipantField;
            }
            set
            {
                this.ParticipantField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public WCFDeviceOrderService.Vehicle Vehicle
        {
            get
            {
                return this.VehicleField;
            }
            set
            {
                this.VehicleField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeviceOrderDetail", Namespace="http://schemas.datacontract.org/2004/07/MyScoreBusiness.Commands.DeviceOrderDetai" +
        "l")]
    public partial class DeviceOrderDetail : object
    {
        
        private System.DateTime CreateDateTimeField;
        
        private int DeviceOrderDetailSeqIDField;
        
        private int DeviceOrderSeqIDField;
        
        private System.Nullable<int> DeviceSeqIDField;
        
        private bool IsReplacementOrderField;
        
        private int ParticipantSeqIDField;
        
        private int VehicleSeqIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime CreateDateTime
        {
            get
            {
                return this.CreateDateTimeField;
            }
            set
            {
                this.CreateDateTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int DeviceOrderDetailSeqID
        {
            get
            {
                return this.DeviceOrderDetailSeqIDField;
            }
            set
            {
                this.DeviceOrderDetailSeqIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int DeviceOrderSeqID
        {
            get
            {
                return this.DeviceOrderSeqIDField;
            }
            set
            {
                this.DeviceOrderSeqIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> DeviceSeqID
        {
            get
            {
                return this.DeviceSeqIDField;
            }
            set
            {
                this.DeviceSeqIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool IsReplacementOrder
        {
            get
            {
                return this.IsReplacementOrderField;
            }
            set
            {
                this.IsReplacementOrderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ParticipantSeqID
        {
            get
            {
                return this.ParticipantSeqIDField;
            }
            set
            {
                this.ParticipantSeqIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int VehicleSeqID
        {
            get
            {
                return this.VehicleSeqIDField;
            }
            set
            {
                this.VehicleSeqIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Participant", Namespace="http://schemas.datacontract.org/2004/07/MyScoreBusiness.Commands.Participant")]
    public partial class Participant : object
    {
        
        private System.DateTime CreateDateTimeField;
        
        private int DeviceExperienceTypeCodeField;
        
        private System.Nullable<int> DeviceSeqIDField;
        
        private string DriverExternalIdField;
        
        private System.Nullable<int> DriverSeqIdField;
        
        private System.DateTime LastUpdateDateTimeField;
        
        private System.Nullable<int> MobileSummarizerVersionCodeField;
        
        private string NicknameField;
        
        private string ParticipantExternalIdField;
        
        private int ParticipantGroupSeqIDField;
        
        private System.Nullable<System.Guid> ParticipantIdField;
        
        private int ParticipantSeqIDField;
        
        private int ParticipantStatusCodeField;
        
        private int ScoreCalculatorCodeField;
        
        private System.Nullable<int> ScoringAlgorithmCodeField;
        
        private int VehicleSeqIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime CreateDateTime
        {
            get
            {
                return this.CreateDateTimeField;
            }
            set
            {
                this.CreateDateTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int DeviceExperienceTypeCode
        {
            get
            {
                return this.DeviceExperienceTypeCodeField;
            }
            set
            {
                this.DeviceExperienceTypeCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> DeviceSeqID
        {
            get
            {
                return this.DeviceSeqIDField;
            }
            set
            {
                this.DeviceSeqIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DriverExternalId
        {
            get
            {
                return this.DriverExternalIdField;
            }
            set
            {
                this.DriverExternalIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> DriverSeqId
        {
            get
            {
                return this.DriverSeqIdField;
            }
            set
            {
                this.DriverSeqIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime LastUpdateDateTime
        {
            get
            {
                return this.LastUpdateDateTimeField;
            }
            set
            {
                this.LastUpdateDateTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> MobileSummarizerVersionCode
        {
            get
            {
                return this.MobileSummarizerVersionCodeField;
            }
            set
            {
                this.MobileSummarizerVersionCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nickname
        {
            get
            {
                return this.NicknameField;
            }
            set
            {
                this.NicknameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ParticipantExternalId
        {
            get
            {
                return this.ParticipantExternalIdField;
            }
            set
            {
                this.ParticipantExternalIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ParticipantGroupSeqID
        {
            get
            {
                return this.ParticipantGroupSeqIDField;
            }
            set
            {
                this.ParticipantGroupSeqIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> ParticipantId
        {
            get
            {
                return this.ParticipantIdField;
            }
            set
            {
                this.ParticipantIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ParticipantSeqID
        {
            get
            {
                return this.ParticipantSeqIDField;
            }
            set
            {
                this.ParticipantSeqIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ParticipantStatusCode
        {
            get
            {
                return this.ParticipantStatusCodeField;
            }
            set
            {
                this.ParticipantStatusCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ScoreCalculatorCode
        {
            get
            {
                return this.ScoreCalculatorCodeField;
            }
            set
            {
                this.ScoreCalculatorCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ScoringAlgorithmCode
        {
            get
            {
                return this.ScoringAlgorithmCodeField;
            }
            set
            {
                this.ScoringAlgorithmCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int VehicleSeqID
        {
            get
            {
                return this.VehicleSeqIDField;
            }
            set
            {
                this.VehicleSeqIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Vehicle", Namespace="http://schemas.datacontract.org/2004/07/MyScoreBusiness.Commands.Vehicle")]
    public partial class Vehicle : object
    {
        
        private System.DateTime CreateDateTimeField;
        
        private string MakeField;
        
        private string ModelField;
        
        private string VINField;
        
        private string VehicleExternalIdField;
        
        private int VehicleSeqIDField;
        
        private short YearField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime CreateDateTime
        {
            get
            {
                return this.CreateDateTimeField;
            }
            set
            {
                this.CreateDateTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Make
        {
            get
            {
                return this.MakeField;
            }
            set
            {
                this.MakeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Model
        {
            get
            {
                return this.ModelField;
            }
            set
            {
                this.ModelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VIN
        {
            get
            {
                return this.VINField;
            }
            set
            {
                this.VINField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VehicleExternalId
        {
            get
            {
                return this.VehicleExternalIdField;
            }
            set
            {
                this.VehicleExternalIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int VehicleSeqID
        {
            get
            {
                return this.VehicleSeqIDField;
            }
            set
            {
                this.VehicleSeqIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public short Year
        {
            get
            {
                return this.YearField;
            }
            set
            {
                this.YearField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NewDeviceOrderDetail", Namespace="http://schemas.datacontract.org/2004/07/MyScoreBusiness.Commands.DeviceOrderDetai" +
        "l")]
    public partial class NewDeviceOrderDetail : object
    {
        
        private int DeviceOrderDetailSeqIDField;
        
        private int DeviceOrderSeqIDField;
        
        private System.Nullable<int> DeviceSeqIDField;
        
        private bool IsReplacementOrderField;
        
        private string MakeField;
        
        private string ModelField;
        
        private System.Nullable<int> ParticipantSeqIDField;
        
        private string VINField;
        
        private System.Nullable<int> VehicleSeqIDField;
        
        private System.Nullable<short> YearField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int DeviceOrderDetailSeqID
        {
            get
            {
                return this.DeviceOrderDetailSeqIDField;
            }
            set
            {
                this.DeviceOrderDetailSeqIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int DeviceOrderSeqID
        {
            get
            {
                return this.DeviceOrderSeqIDField;
            }
            set
            {
                this.DeviceOrderSeqIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> DeviceSeqID
        {
            get
            {
                return this.DeviceSeqIDField;
            }
            set
            {
                this.DeviceSeqIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool IsReplacementOrder
        {
            get
            {
                return this.IsReplacementOrderField;
            }
            set
            {
                this.IsReplacementOrderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Make
        {
            get
            {
                return this.MakeField;
            }
            set
            {
                this.MakeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Model
        {
            get
            {
                return this.ModelField;
            }
            set
            {
                this.ModelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ParticipantSeqID
        {
            get
            {
                return this.ParticipantSeqIDField;
            }
            set
            {
                this.ParticipantSeqIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VIN
        {
            get
            {
                return this.VINField;
            }
            set
            {
                this.VINField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> VehicleSeqID
        {
            get
            {
                return this.VehicleSeqIDField;
            }
            set
            {
                this.VehicleSeqIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<short> Year
        {
            get
            {
                return this.YearField;
            }
            set
            {
                this.YearField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UBIServiceResponse", Namespace="http://schemas.datacontract.org/2004/07/Progressive.UBI.Shared.UBIServicesLib")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WCFDeviceOrderService.UpdateDeviceOrderResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WCFDeviceOrderService.GetDeviceOrderResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WCFDeviceOrderService.FulfillDeviceOrderResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WCFDeviceOrderService.DeleteDeviceOrderResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WCFDeviceOrderService.AddDeviceOrderResponse))]
    public partial class UBIServiceResponse : object
    {
        
        private WCFDeviceOrderService.ResponseError[] ResponseErrorsField;
        
        private WCFDeviceOrderService.ResponseStatus ResponseStatusField;
        
        private int VersionField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public WCFDeviceOrderService.ResponseError[] ResponseErrors
        {
            get
            {
                return this.ResponseErrorsField;
            }
            set
            {
                this.ResponseErrorsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public WCFDeviceOrderService.ResponseStatus ResponseStatus
        {
            get
            {
                return this.ResponseStatusField;
            }
            set
            {
                this.ResponseStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Version
        {
            get
            {
                return this.VersionField;
            }
            set
            {
                this.VersionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdateDeviceOrderResponse", Namespace="http://schemas.datacontract.org/2004/07/MyScoreBusiness.Commands.DeviceOrder.Upda" +
        "te.Contract")]
    public partial class UpdateDeviceOrderResponse : WCFDeviceOrderService.UBIServiceResponse
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetDeviceOrderResponse", Namespace="http://schemas.datacontract.org/2004/07/MyScoreBusiness.Commands.DeviceOrder.Get." +
        "Contract")]
    public partial class GetDeviceOrderResponse : WCFDeviceOrderService.UBIServiceResponse
    {
        
        private WCFDeviceOrderService.DeviceOrder[] DeviceOrderListField;
        
        private int RecordCountField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public WCFDeviceOrderService.DeviceOrder[] DeviceOrderList
        {
            get
            {
                return this.DeviceOrderListField;
            }
            set
            {
                this.DeviceOrderListField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int RecordCount
        {
            get
            {
                return this.RecordCountField;
            }
            set
            {
                this.RecordCountField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FulfillDeviceOrderResponse", Namespace="http://schemas.datacontract.org/2004/07/MyScoreBusiness.Commands.DeviceOrder.Fulf" +
        "ill.Contract")]
    public partial class FulfillDeviceOrderResponse : WCFDeviceOrderService.UBIServiceResponse
    {
        
        private WCFDeviceOrderService.BusinessDeviceOrderDetail[] BusinessDeviceOrderDetailsField;
        
        private bool OrderFulfilledField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WCFDeviceOrderService.BusinessDeviceOrderDetail[] BusinessDeviceOrderDetails
        {
            get
            {
                return this.BusinessDeviceOrderDetailsField;
            }
            set
            {
                this.BusinessDeviceOrderDetailsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool OrderFulfilled
        {
            get
            {
                return this.OrderFulfilledField;
            }
            set
            {
                this.OrderFulfilledField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeleteDeviceOrderResponse", Namespace="http://schemas.datacontract.org/2004/07/MyScoreBusiness.Commands.DeviceOrder.Dele" +
        "te.Contract")]
    public partial class DeleteDeviceOrderResponse : WCFDeviceOrderService.UBIServiceResponse
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddDeviceOrderResponse", Namespace="http://schemas.datacontract.org/2004/07/MyScoreBusiness.Commands.DeviceOrder.Add." +
        "Contract")]
    public partial class AddDeviceOrderResponse : WCFDeviceOrderService.UBIServiceResponse
    {
        
        private int DeviceOrderSeqIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int DeviceOrderSeqID
        {
            get
            {
                return this.DeviceOrderSeqIDField;
            }
            set
            {
                this.DeviceOrderSeqIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseError", Namespace="http://schemas.datacontract.org/2004/07/Progressive.UBI.Shared.UBIServicesLib")]
    public partial class ResponseError : object
    {
        
        private string ErrorCodeField;
        
        private string FieldField;
        
        private string MessageField;
        
        private WCFDeviceOrderService.ErrorSeverityCode SeverityCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorCode
        {
            get
            {
                return this.ErrorCodeField;
            }
            set
            {
                this.ErrorCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Field
        {
            get
            {
                return this.FieldField;
            }
            set
            {
                this.FieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WCFDeviceOrderService.ErrorSeverityCode SeverityCode
        {
            get
            {
                return this.SeverityCodeField;
            }
            set
            {
                this.SeverityCodeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseStatus", Namespace="http://schemas.datacontract.org/2004/07/Progressive.UBI.Shared.UBIServicesLib")]
    public enum ResponseStatus : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Failure = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SuccessWithWarning = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FailureWithWarning = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PartialSuccess = 5,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ErrorSeverityCode", Namespace="http://schemas.datacontract.org/2004/07/Progressive.UBI.Shared.UBIServicesLib")]
    public enum ErrorSeverityCode : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Warning = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Validation = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Exception = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Ticket = 5,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCFDeviceOrderService.IDeviceOrderService")]
    public interface IDeviceOrderService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeviceOrderService/Add", ReplyAction="http://tempuri.org/IDeviceOrderService/AddResponse")]
        System.Threading.Tasks.Task<WCFDeviceOrderService.AddDeviceOrderResponse> AddAsync(WCFDeviceOrderService.AddDeviceOrderRequest addDeviceOrderRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeviceOrderService/Delete", ReplyAction="http://tempuri.org/IDeviceOrderService/DeleteResponse")]
        System.Threading.Tasks.Task<WCFDeviceOrderService.DeleteDeviceOrderResponse> DeleteAsync(WCFDeviceOrderService.DeleteDeviceOrderRequest deleteDeviceOrderRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeviceOrderService/Fulfill", ReplyAction="http://tempuri.org/IDeviceOrderService/FulfillResponse")]
        System.Threading.Tasks.Task<WCFDeviceOrderService.FulfillDeviceOrderResponse> FulfillAsync(WCFDeviceOrderService.FulfillDeviceOrderRequest fulfillDeviceOrderRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeviceOrderService/Get", ReplyAction="http://tempuri.org/IDeviceOrderService/GetResponse")]
        System.Threading.Tasks.Task<WCFDeviceOrderService.GetDeviceOrderResponse> GetAsync(WCFDeviceOrderService.GetDeviceOrderRequest getDeviceOrderRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeviceOrderService/Update", ReplyAction="http://tempuri.org/IDeviceOrderService/UpdateResponse")]
        System.Threading.Tasks.Task<WCFDeviceOrderService.UpdateDeviceOrderResponse> UpdateAsync(WCFDeviceOrderService.UpdateDeviceOrderRequest updateDeviceOrderRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeviceOrderService/AddWithDetails", ReplyAction="http://tempuri.org/IDeviceOrderService/AddWithDetailsResponse")]
        System.Threading.Tasks.Task<WCFDeviceOrderService.AddDeviceOrderResponse> AddWithDetailsAsync(WCFDeviceOrderService.AddDeviceOrderWithDetailRequest addDeviceOrderRequest);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface IDeviceOrderServiceChannel : WCFDeviceOrderService.IDeviceOrderService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class DeviceOrderServiceClient : System.ServiceModel.ClientBase<WCFDeviceOrderService.IDeviceOrderService>, WCFDeviceOrderService.IDeviceOrderService
    {
        
        public DeviceOrderServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<WCFDeviceOrderService.AddDeviceOrderResponse> AddAsync(WCFDeviceOrderService.AddDeviceOrderRequest addDeviceOrderRequest)
        {
            return base.Channel.AddAsync(addDeviceOrderRequest);
        }
        
        public System.Threading.Tasks.Task<WCFDeviceOrderService.DeleteDeviceOrderResponse> DeleteAsync(WCFDeviceOrderService.DeleteDeviceOrderRequest deleteDeviceOrderRequest)
        {
            return base.Channel.DeleteAsync(deleteDeviceOrderRequest);
        }
        
        public System.Threading.Tasks.Task<WCFDeviceOrderService.FulfillDeviceOrderResponse> FulfillAsync(WCFDeviceOrderService.FulfillDeviceOrderRequest fulfillDeviceOrderRequest)
        {
            return base.Channel.FulfillAsync(fulfillDeviceOrderRequest);
        }
        
        public System.Threading.Tasks.Task<WCFDeviceOrderService.GetDeviceOrderResponse> GetAsync(WCFDeviceOrderService.GetDeviceOrderRequest getDeviceOrderRequest)
        {
            return base.Channel.GetAsync(getDeviceOrderRequest);
        }
        
        public System.Threading.Tasks.Task<WCFDeviceOrderService.UpdateDeviceOrderResponse> UpdateAsync(WCFDeviceOrderService.UpdateDeviceOrderRequest updateDeviceOrderRequest)
        {
            return base.Channel.UpdateAsync(updateDeviceOrderRequest);
        }
        
        public System.Threading.Tasks.Task<WCFDeviceOrderService.AddDeviceOrderResponse> AddWithDetailsAsync(WCFDeviceOrderService.AddDeviceOrderWithDetailRequest addDeviceOrderRequest)
        {
            return base.Channel.AddWithDetailsAsync(addDeviceOrderRequest);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
    }
}
