// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Progressive.Telematics.Admin.Services.Models.ClTables
;
    public partial class DeviceEvent
    {
        public int DeviceEventSeqId { get; set; }
        public int ParticipantSeqId { get; set; }
        public int DeviceSeqId { get; set; }
        public DateTime DeviceEventDateTime { get; set; }
        public int DeviceEventTypeCode { get; set; }
        public int? VehicleProtocolCode { get; set; }
        public string ReportedVin { get; set; }
        public int? OdometerReading { get; set; }
        public DateTime CreateDateTime { get; set; }

        public virtual DeviceEventType DeviceEventTypeCodeNavigation { get; set; }
        public virtual Participant ParticipantSeq { get; set; }
        public virtual VehicleProtocol VehicleProtocolCodeNavigation { get; set; }
    }
