// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Progressive.Telematics.Admin.Services.Models.ClTables
{
    public partial class DeviceReturnReason
    {
        public DeviceReturnReason()
        {
            DeviceReturns = new HashSet<DeviceReturn>();
        }

        public int Code { get; set; }
        public string Description { get; set; }
        public bool IsActive { get; set; }
        public DateTime CreateDateTime { get; set; }

        public virtual ICollection<DeviceReturn> DeviceReturns { get; set; }
    }
}