// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Progressive.Telematics.Admin.Services.Models.ClTables
;
    public partial class DeviceOrderDetail
    {
        public int DeviceOrderDetailSeqId { get; set; }
        public int DeviceOrderSeqId { get; set; }
        public int ParticipantSeqId { get; set; }
        public int VehicleSeqId { get; set; }
        public int? DeviceSeqId { get; set; }
        public DateTime CreateDateTime { get; set; }
        public bool IsReplacementOrder { get; set; }
        public bool IsCableOrderInd { get; set; }
    
    }
