// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Progressive.Telematics.Admin.Services.Models.ClTables
{
    public partial class ParticipantHistory
    {
        public long ParticipantHistorySeqId { get; set; }
        public int ParticipantSeqId { get; set; }
        public string ParticipantId { get; set; }
        public int PolicySeqId { get; set; }
        public int VehicleSeqId { get; set; }
        public int? DeviceSeqId { get; set; }
        public int ParticipantStatusCode { get; set; }
        public DateTime LastUpdateDateTime { get; set; }
        public DateTime CreateDateTime { get; set; }
        public int? DeviceExperienceTypeCode { get; set; }
        public DateTime? DashboardEnrollmentDateTime { get; set; }

        public virtual Participant ParticipantSeq { get; set; }
    }
}