//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfSimManagementService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UBIServiceRequest", Namespace="http://schemas.datacontract.org/2004/07/Progressive.UBI.Shared.UBIServicesLib")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WcfSimManagementService.DeleteSimManagementRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WcfSimManagementService.GetSimManagementRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WcfSimManagementService.UpdateSimManagementRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WcfSimManagementService.GetSimManagementReadyForActionRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WcfSimManagementService.AddSimManagementRequest))]
    public partial class UBIServiceRequest : object
    {
        
        private int VersionField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Version
        {
            get
            {
                return this.VersionField;
            }
            set
            {
                this.VersionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeleteSimManagementRequest", Namespace="http://schemas.datacontract.org/2004/07/HomeBaseServices.Xirgo")]
    public partial class DeleteSimManagementRequest : WcfSimManagementService.UBIServiceRequest
    {
        
        private string SIMField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string SIM
        {
            get
            {
                return this.SIMField;
            }
            set
            {
                this.SIMField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetSimManagementRequest", Namespace="http://schemas.datacontract.org/2004/07/HomeBaseServices.Xirgo")]
    public partial class GetSimManagementRequest : WcfSimManagementService.UBIServiceRequest
    {
        
        private string SIMField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string SIM
        {
            get
            {
                return this.SIMField;
            }
            set
            {
                this.SIMField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdateSimManagementRequest", Namespace="http://schemas.datacontract.org/2004/07/HomeBaseServices.Xirgo")]
    public partial class UpdateSimManagementRequest : WcfSimManagementService.UBIServiceRequest
    {
        
        private System.Nullable<WcfSimManagementService.ActionType> ActionField;
        
        private System.Nullable<System.DateTime> CreateDateField;
        
        private System.Nullable<System.DateTime> EffectiveDateField;
        
        private System.Nullable<System.DateTime> LastUpdateDateField;
        
        private string SIMField;
        
        private string StatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<WcfSimManagementService.ActionType> Action
        {
            get
            {
                return this.ActionField;
            }
            set
            {
                this.ActionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CreateDate
        {
            get
            {
                return this.CreateDateField;
            }
            set
            {
                this.CreateDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> EffectiveDate
        {
            get
            {
                return this.EffectiveDateField;
            }
            set
            {
                this.EffectiveDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> LastUpdateDate
        {
            get
            {
                return this.LastUpdateDateField;
            }
            set
            {
                this.LastUpdateDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string SIM
        {
            get
            {
                return this.SIMField;
            }
            set
            {
                this.SIMField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetSimManagementReadyForActionRequest", Namespace="http://schemas.datacontract.org/2004/07/HomeBaseServices.Xirgo")]
    public partial class GetSimManagementReadyForActionRequest : WcfSimManagementService.UBIServiceRequest
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddSimManagementRequest", Namespace="http://schemas.datacontract.org/2004/07/HomeBaseServices.Xirgo")]
    public partial class AddSimManagementRequest : WcfSimManagementService.UBIServiceRequest
    {
        
        private WcfSimManagementService.ActionType ActionField;
        
        private System.DateTime EffectiveDateField;
        
        private string SIMField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public WcfSimManagementService.ActionType Action
        {
            get
            {
                return this.ActionField;
            }
            set
            {
                this.ActionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime EffectiveDate
        {
            get
            {
                return this.EffectiveDateField;
            }
            set
            {
                this.EffectiveDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string SIM
        {
            get
            {
                return this.SIMField;
            }
            set
            {
                this.SIMField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ActionType", Namespace="http://schemas.datacontract.org/2004/07/HomeBaseServices.Xirgo")]
    public enum ActionType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Deactivate = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Activate = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Straight_Deactivate = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Straight_Activate = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Straight_Suspend = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Straight_Restore = 5,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UBIServiceResponse", Namespace="http://schemas.datacontract.org/2004/07/Progressive.UBI.Shared.UBIServicesLib")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WcfSimManagementService.DeleteSimManagementResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WcfSimManagementService.GetSimManagementResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WcfSimManagementService.UpdateSimManagementResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WcfSimManagementService.GetSimManagementReadyForActionResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WcfSimManagementService.AddSimManagementResponse))]
    public partial class UBIServiceResponse : object
    {
        
        private WcfSimManagementService.ResponseError[] ResponseErrorsField;
        
        private WcfSimManagementService.ResponseStatus ResponseStatusField;
        
        private int VersionField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public WcfSimManagementService.ResponseError[] ResponseErrors
        {
            get
            {
                return this.ResponseErrorsField;
            }
            set
            {
                this.ResponseErrorsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public WcfSimManagementService.ResponseStatus ResponseStatus
        {
            get
            {
                return this.ResponseStatusField;
            }
            set
            {
                this.ResponseStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Version
        {
            get
            {
                return this.VersionField;
            }
            set
            {
                this.VersionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeleteSimManagementResponse", Namespace="http://schemas.datacontract.org/2004/07/HomeBaseServices.Xirgo")]
    public partial class DeleteSimManagementResponse : WcfSimManagementService.UBIServiceResponse
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetSimManagementResponse", Namespace="http://schemas.datacontract.org/2004/07/HomeBaseServices.Xirgo")]
    public partial class GetSimManagementResponse : WcfSimManagementService.UBIServiceResponse
    {
        
        private WcfSimManagementService.ActionType ActionField;
        
        private System.DateTime CreateDateField;
        
        private System.DateTime EffectiveDateField;
        
        private System.DateTime LastUpdateDateField;
        
        private int RecordCountField;
        
        private string SIMField;
        
        private string StatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public WcfSimManagementService.ActionType Action
        {
            get
            {
                return this.ActionField;
            }
            set
            {
                this.ActionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime CreateDate
        {
            get
            {
                return this.CreateDateField;
            }
            set
            {
                this.CreateDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime EffectiveDate
        {
            get
            {
                return this.EffectiveDateField;
            }
            set
            {
                this.EffectiveDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime LastUpdateDate
        {
            get
            {
                return this.LastUpdateDateField;
            }
            set
            {
                this.LastUpdateDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int RecordCount
        {
            get
            {
                return this.RecordCountField;
            }
            set
            {
                this.RecordCountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string SIM
        {
            get
            {
                return this.SIMField;
            }
            set
            {
                this.SIMField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdateSimManagementResponse", Namespace="http://schemas.datacontract.org/2004/07/HomeBaseServices.Xirgo")]
    public partial class UpdateSimManagementResponse : WcfSimManagementService.UBIServiceResponse
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetSimManagementReadyForActionResponse", Namespace="http://schemas.datacontract.org/2004/07/HomeBaseServices.Xirgo")]
    public partial class GetSimManagementReadyForActionResponse : WcfSimManagementService.UBIServiceResponse
    {
        
        private int RecordCountField;
        
        private WcfSimManagementService.SimManagementRow[] SimManagementRowsField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int RecordCount
        {
            get
            {
                return this.RecordCountField;
            }
            set
            {
                this.RecordCountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public WcfSimManagementService.SimManagementRow[] SimManagementRows
        {
            get
            {
                return this.SimManagementRowsField;
            }
            set
            {
                this.SimManagementRowsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddSimManagementResponse", Namespace="http://schemas.datacontract.org/2004/07/HomeBaseServices.Xirgo")]
    public partial class AddSimManagementResponse : WcfSimManagementService.UBIServiceResponse
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseError", Namespace="http://schemas.datacontract.org/2004/07/Progressive.UBI.Shared.UBIServicesLib")]
    public partial class ResponseError : object
    {
        
        private string ErrorCodeField;
        
        private string FieldField;
        
        private string MessageField;
        
        private WcfSimManagementService.ErrorSeverityCode SeverityCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorCode
        {
            get
            {
                return this.ErrorCodeField;
            }
            set
            {
                this.ErrorCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Field
        {
            get
            {
                return this.FieldField;
            }
            set
            {
                this.FieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WcfSimManagementService.ErrorSeverityCode SeverityCode
        {
            get
            {
                return this.SeverityCodeField;
            }
            set
            {
                this.SeverityCodeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseStatus", Namespace="http://schemas.datacontract.org/2004/07/Progressive.UBI.Shared.UBIServicesLib")]
    public enum ResponseStatus : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Failure = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SuccessWithWarning = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FailureWithWarning = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PartialSuccess = 5,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ErrorSeverityCode", Namespace="http://schemas.datacontract.org/2004/07/Progressive.UBI.Shared.UBIServicesLib")]
    public enum ErrorSeverityCode : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Warning = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Validation = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Exception = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Ticket = 5,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SimManagementRow", Namespace="http://schemas.datacontract.org/2004/07/HomeBaseServices.Xirgo")]
    public partial class SimManagementRow : object
    {
        
        private WcfSimManagementService.ActionType ActionField;
        
        private System.DateTime CreateDateField;
        
        private System.DateTime EffectiveDateField;
        
        private System.DateTime LastUpdateDateField;
        
        private string SIMField;
        
        private string StatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WcfSimManagementService.ActionType Action
        {
            get
            {
                return this.ActionField;
            }
            set
            {
                this.ActionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreateDate
        {
            get
            {
                return this.CreateDateField;
            }
            set
            {
                this.CreateDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EffectiveDate
        {
            get
            {
                return this.EffectiveDateField;
            }
            set
            {
                this.EffectiveDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastUpdateDate
        {
            get
            {
                return this.LastUpdateDateField;
            }
            set
            {
                this.LastUpdateDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SIM
        {
            get
            {
                return this.SIMField;
            }
            set
            {
                this.SIMField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WcfSimManagementService.ISimManagementService")]
    public interface ISimManagementService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISimManagementService/Add", ReplyAction="http://tempuri.org/ISimManagementService/AddResponse")]
        System.Threading.Tasks.Task<WcfSimManagementService.AddSimManagementResponse> AddAsync(WcfSimManagementService.AddSimManagementRequest addSimManagementRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISimManagementService/Delete", ReplyAction="http://tempuri.org/ISimManagementService/DeleteResponse")]
        System.Threading.Tasks.Task<WcfSimManagementService.DeleteSimManagementResponse> DeleteAsync(WcfSimManagementService.DeleteSimManagementRequest deleteSimManagementRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISimManagementService/Get", ReplyAction="http://tempuri.org/ISimManagementService/GetResponse")]
        System.Threading.Tasks.Task<WcfSimManagementService.GetSimManagementResponse> GetAsync(WcfSimManagementService.GetSimManagementRequest getSimManagementRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISimManagementService/Update", ReplyAction="http://tempuri.org/ISimManagementService/UpdateResponse")]
        System.Threading.Tasks.Task<WcfSimManagementService.UpdateSimManagementResponse> UpdateAsync(WcfSimManagementService.UpdateSimManagementRequest updateSimManagementRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISimManagementService/GetReadyForAction", ReplyAction="http://tempuri.org/ISimManagementService/GetReadyForActionResponse")]
        System.Threading.Tasks.Task<WcfSimManagementService.GetSimManagementReadyForActionResponse> GetReadyForActionAsync(WcfSimManagementService.GetSimManagementReadyForActionRequest getSimManagementReadyForActionRequest);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface ISimManagementServiceChannel : WcfSimManagementService.ISimManagementService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class SimManagementServiceClient : System.ServiceModel.ClientBase<WcfSimManagementService.ISimManagementService>, WcfSimManagementService.ISimManagementService
    {
        
        public SimManagementServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<WcfSimManagementService.AddSimManagementResponse> AddAsync(WcfSimManagementService.AddSimManagementRequest addSimManagementRequest)
        {
            return base.Channel.AddAsync(addSimManagementRequest);
        }
        
        public System.Threading.Tasks.Task<WcfSimManagementService.DeleteSimManagementResponse> DeleteAsync(WcfSimManagementService.DeleteSimManagementRequest deleteSimManagementRequest)
        {
            return base.Channel.DeleteAsync(deleteSimManagementRequest);
        }
        
        public System.Threading.Tasks.Task<WcfSimManagementService.GetSimManagementResponse> GetAsync(WcfSimManagementService.GetSimManagementRequest getSimManagementRequest)
        {
            return base.Channel.GetAsync(getSimManagementRequest);
        }
        
        public System.Threading.Tasks.Task<WcfSimManagementService.UpdateSimManagementResponse> UpdateAsync(WcfSimManagementService.UpdateSimManagementRequest updateSimManagementRequest)
        {
            return base.Channel.UpdateAsync(updateSimManagementRequest);
        }
        
        public System.Threading.Tasks.Task<WcfSimManagementService.GetSimManagementReadyForActionResponse> GetReadyForActionAsync(WcfSimManagementService.GetSimManagementReadyForActionRequest getSimManagementReadyForActionRequest)
        {
            return base.Channel.GetReadyForActionAsync(getSimManagementReadyForActionRequest);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }

#if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
#endif

        public static System.ServiceModel.Channels.Binding DefaultBinding()
        {
            return GetBindingForEndpoint(EndpointConfiguration.WSHttpBinding_ISimManagement);
        }

        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WSHttpBinding_ISimManagement))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }

        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WSHttpBinding_ISimManagement))
            {
                return new System.ServiceModel.EndpointAddress("http://t-ubi-labs-services/HomeBaseServices/Services/xirgo/SimManagementService.svc" +
                        "");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }

        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return SimManagementServiceClient.GetBindingForEndpoint(EndpointConfiguration.WSHttpBinding_ISimManagement);
        }

        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return SimManagementServiceClient.GetEndpointAddress(EndpointConfiguration.WSHttpBinding_ISimManagement);
        }

        public enum EndpointConfiguration
        {
            WSHttpBinding_ISimManagement
        }
    }
}
