//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfIneligibleVehiclesService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UBIServiceRequest", Namespace="http://schemas.datacontract.org/2004/07/Progressive.UBI.Shared.UBIServicesLib")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WcfIneligibleVehiclesService.InsertIneligibleVehicleRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WcfIneligibleVehiclesService.UpdateIneligibleVehicleRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WcfIneligibleVehiclesService.DeleteIneligibleVehicleRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WcfIneligibleVehiclesService.GetDeviceVersionsRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WcfIneligibleVehiclesService.GetIneligibleVehicleRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WcfIneligibleVehiclesService.GetIneligibleVehiclesRequest))]
    public partial class UBIServiceRequest : object
    {
        
        private int VersionField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Version
        {
            get
            {
                return this.VersionField;
            }
            set
            {
                this.VersionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InsertIneligibleVehicleRequest", Namespace="http://schemas.datacontract.org/2004/07/PolicySystemBusiness")]
    public partial class InsertIneligibleVehicleRequest : WcfIneligibleVehiclesService.UBIServiceRequest
    {
        
        private int DeviceVersionSeqIDField;
        
        private string ExactModelMatchIndField;
        
        private string ExcludedMakeIndField;
        
        private string MakeField;
        
        private string ModelField;
        
        private string ModelYearField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DeviceVersionSeqID
        {
            get
            {
                return this.DeviceVersionSeqIDField;
            }
            set
            {
                this.DeviceVersionSeqIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExactModelMatchInd
        {
            get
            {
                return this.ExactModelMatchIndField;
            }
            set
            {
                this.ExactModelMatchIndField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExcludedMakeInd
        {
            get
            {
                return this.ExcludedMakeIndField;
            }
            set
            {
                this.ExcludedMakeIndField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Make
        {
            get
            {
                return this.MakeField;
            }
            set
            {
                this.MakeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Model
        {
            get
            {
                return this.ModelField;
            }
            set
            {
                this.ModelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModelYear
        {
            get
            {
                return this.ModelYearField;
            }
            set
            {
                this.ModelYearField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdateIneligibleVehicleRequest", Namespace="http://schemas.datacontract.org/2004/07/PolicySystemBusiness")]
    public partial class UpdateIneligibleVehicleRequest : WcfIneligibleVehiclesService.UBIServiceRequest
    {
        
        private int DeviceVersionSeqIDField;
        
        private string ExactModelMatchIndField;
        
        private string ExcludedMakeIndField;
        
        private int IneligibleVehicleSeqIDField;
        
        private string MakeField;
        
        private string ModelField;
        
        private string ModelYearField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DeviceVersionSeqID
        {
            get
            {
                return this.DeviceVersionSeqIDField;
            }
            set
            {
                this.DeviceVersionSeqIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExactModelMatchInd
        {
            get
            {
                return this.ExactModelMatchIndField;
            }
            set
            {
                this.ExactModelMatchIndField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExcludedMakeInd
        {
            get
            {
                return this.ExcludedMakeIndField;
            }
            set
            {
                this.ExcludedMakeIndField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IneligibleVehicleSeqID
        {
            get
            {
                return this.IneligibleVehicleSeqIDField;
            }
            set
            {
                this.IneligibleVehicleSeqIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Make
        {
            get
            {
                return this.MakeField;
            }
            set
            {
                this.MakeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Model
        {
            get
            {
                return this.ModelField;
            }
            set
            {
                this.ModelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModelYear
        {
            get
            {
                return this.ModelYearField;
            }
            set
            {
                this.ModelYearField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeleteIneligibleVehicleRequest", Namespace="http://schemas.datacontract.org/2004/07/PolicySystemBusiness")]
    public partial class DeleteIneligibleVehicleRequest : WcfIneligibleVehiclesService.UBIServiceRequest
    {
        
        private int IneligibleVehicleSeqIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IneligibleVehicleSeqID
        {
            get
            {
                return this.IneligibleVehicleSeqIDField;
            }
            set
            {
                this.IneligibleVehicleSeqIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetDeviceVersionsRequest", Namespace="http://schemas.datacontract.org/2004/07/PolicySystemBusiness")]
    public partial class GetDeviceVersionsRequest : WcfIneligibleVehiclesService.UBIServiceRequest
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetIneligibleVehicleRequest", Namespace="http://schemas.datacontract.org/2004/07/PolicySystemBusiness")]
    public partial class GetIneligibleVehicleRequest : WcfIneligibleVehiclesService.UBIServiceRequest
    {
        
        private int IneligibleVehicleSeqIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IneligibleVehicleSeqID
        {
            get
            {
                return this.IneligibleVehicleSeqIDField;
            }
            set
            {
                this.IneligibleVehicleSeqIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetIneligibleVehiclesRequest", Namespace="http://schemas.datacontract.org/2004/07/PolicySystemBusiness")]
    public partial class GetIneligibleVehiclesRequest : WcfIneligibleVehiclesService.UBIServiceRequest
    {
        
        private string DescriptionField;
        
        private string ExactModelMatchIndicatorField;
        
        private string MakeField;
        
        private string ModelField;
        
        private string ModelYearField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExactModelMatchIndicator
        {
            get
            {
                return this.ExactModelMatchIndicatorField;
            }
            set
            {
                this.ExactModelMatchIndicatorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Make
        {
            get
            {
                return this.MakeField;
            }
            set
            {
                this.MakeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Model
        {
            get
            {
                return this.ModelField;
            }
            set
            {
                this.ModelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModelYear
        {
            get
            {
                return this.ModelYearField;
            }
            set
            {
                this.ModelYearField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UBIServiceResponse", Namespace="http://schemas.datacontract.org/2004/07/Progressive.UBI.Shared.UBIServicesLib")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WcfIneligibleVehiclesService.InsertIneligibleVehicleResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WcfIneligibleVehiclesService.UpdateIneligibleVehicleResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WcfIneligibleVehiclesService.DeleteIneligibleVehicleResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WcfIneligibleVehiclesService.GetDeviceVersionsResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WcfIneligibleVehiclesService.GetIneligibleVehicleResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WcfIneligibleVehiclesService.GetIneligibleVehiclesResponse))]
    public partial class UBIServiceResponse : object
    {
        
        private WcfIneligibleVehiclesService.ResponseError[] ResponseErrorsField;
        
        private WcfIneligibleVehiclesService.ResponseStatus ResponseStatusField;
        
        private int VersionField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public WcfIneligibleVehiclesService.ResponseError[] ResponseErrors
        {
            get
            {
                return this.ResponseErrorsField;
            }
            set
            {
                this.ResponseErrorsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public WcfIneligibleVehiclesService.ResponseStatus ResponseStatus
        {
            get
            {
                return this.ResponseStatusField;
            }
            set
            {
                this.ResponseStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Version
        {
            get
            {
                return this.VersionField;
            }
            set
            {
                this.VersionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InsertIneligibleVehicleResponse", Namespace="http://schemas.datacontract.org/2004/07/PolicySystemBusiness")]
    public partial class InsertIneligibleVehicleResponse : WcfIneligibleVehiclesService.UBIServiceResponse
    {
        
        private int IneligibleVehicleSeqIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IneligibleVehicleSeqID
        {
            get
            {
                return this.IneligibleVehicleSeqIDField;
            }
            set
            {
                this.IneligibleVehicleSeqIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdateIneligibleVehicleResponse", Namespace="http://schemas.datacontract.org/2004/07/PolicySystemBusiness")]
    public partial class UpdateIneligibleVehicleResponse : WcfIneligibleVehiclesService.UBIServiceResponse
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeleteIneligibleVehicleResponse", Namespace="http://schemas.datacontract.org/2004/07/PolicySystemBusiness")]
    public partial class DeleteIneligibleVehicleResponse : WcfIneligibleVehiclesService.UBIServiceResponse
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetDeviceVersionsResponse", Namespace="http://schemas.datacontract.org/2004/07/PolicySystemBusiness")]
    public partial class GetDeviceVersionsResponse : WcfIneligibleVehiclesService.UBIServiceResponse
    {
        
        private WcfIneligibleVehiclesService.DeviceVersion[] DeviceVersionsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WcfIneligibleVehiclesService.DeviceVersion[] DeviceVersions
        {
            get
            {
                return this.DeviceVersionsField;
            }
            set
            {
                this.DeviceVersionsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetIneligibleVehicleResponse", Namespace="http://schemas.datacontract.org/2004/07/PolicySystemBusiness")]
    public partial class GetIneligibleVehicleResponse : WcfIneligibleVehiclesService.UBIServiceResponse
    {
        
        private WcfIneligibleVehiclesService.IneligibleVehicle IneligibleVehicleField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WcfIneligibleVehiclesService.IneligibleVehicle IneligibleVehicle
        {
            get
            {
                return this.IneligibleVehicleField;
            }
            set
            {
                this.IneligibleVehicleField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetIneligibleVehiclesResponse", Namespace="http://schemas.datacontract.org/2004/07/PolicySystemBusiness")]
    public partial class GetIneligibleVehiclesResponse : WcfIneligibleVehiclesService.UBIServiceResponse
    {
        
        private WcfIneligibleVehiclesService.IneligibleVehicle[] IneligibleVehiclesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WcfIneligibleVehiclesService.IneligibleVehicle[] IneligibleVehicles
        {
            get
            {
                return this.IneligibleVehiclesField;
            }
            set
            {
                this.IneligibleVehiclesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseError", Namespace="http://schemas.datacontract.org/2004/07/Progressive.UBI.Shared.UBIServicesLib")]
    public partial class ResponseError : object
    {
        
        private string ErrorCodeField;
        
        private string FieldField;
        
        private string MessageField;
        
        private WcfIneligibleVehiclesService.ErrorSeverityCode SeverityCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorCode
        {
            get
            {
                return this.ErrorCodeField;
            }
            set
            {
                this.ErrorCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Field
        {
            get
            {
                return this.FieldField;
            }
            set
            {
                this.FieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WcfIneligibleVehiclesService.ErrorSeverityCode SeverityCode
        {
            get
            {
                return this.SeverityCodeField;
            }
            set
            {
                this.SeverityCodeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseStatus", Namespace="http://schemas.datacontract.org/2004/07/Progressive.UBI.Shared.UBIServicesLib")]
    public enum ResponseStatus : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Failure = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SuccessWithWarning = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FailureWithWarning = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PartialSuccess = 5,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IneligibleVehicle", Namespace="http://schemas.datacontract.org/2004/07/PolicySystemBusiness")]
    public partial class IneligibleVehicle : object
    {
        
        private System.DateTime CreateDateField;
        
        private string DeviceDescriptionField;
        
        private string DeviceManufacturerField;
        
        private string DeviceVersionField;
        
        private int DeviceVersionSeqIDField;
        
        private string ExactModelMatchIndField;
        
        private string ExcludedMakeIndField;
        
        private int IneligibleVehicleSeqIDField;
        
        private System.DateTime LastChangeDateTimeField;
        
        private string MakeField;
        
        private string ModelField;
        
        private string ModelYearField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreateDate
        {
            get
            {
                return this.CreateDateField;
            }
            set
            {
                this.CreateDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeviceDescription
        {
            get
            {
                return this.DeviceDescriptionField;
            }
            set
            {
                this.DeviceDescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeviceManufacturer
        {
            get
            {
                return this.DeviceManufacturerField;
            }
            set
            {
                this.DeviceManufacturerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeviceVersion
        {
            get
            {
                return this.DeviceVersionField;
            }
            set
            {
                this.DeviceVersionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DeviceVersionSeqID
        {
            get
            {
                return this.DeviceVersionSeqIDField;
            }
            set
            {
                this.DeviceVersionSeqIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExactModelMatchInd
        {
            get
            {
                return this.ExactModelMatchIndField;
            }
            set
            {
                this.ExactModelMatchIndField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExcludedMakeInd
        {
            get
            {
                return this.ExcludedMakeIndField;
            }
            set
            {
                this.ExcludedMakeIndField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IneligibleVehicleSeqID
        {
            get
            {
                return this.IneligibleVehicleSeqIDField;
            }
            set
            {
                this.IneligibleVehicleSeqIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastChangeDateTime
        {
            get
            {
                return this.LastChangeDateTimeField;
            }
            set
            {
                this.LastChangeDateTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Make
        {
            get
            {
                return this.MakeField;
            }
            set
            {
                this.MakeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Model
        {
            get
            {
                return this.ModelField;
            }
            set
            {
                this.ModelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModelYear
        {
            get
            {
                return this.ModelYearField;
            }
            set
            {
                this.ModelYearField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ErrorSeverityCode", Namespace="http://schemas.datacontract.org/2004/07/Progressive.UBI.Shared.UBIServicesLib")]
    public enum ErrorSeverityCode : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Warning = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Validation = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Exception = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Ticket = 5,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeviceVersion", Namespace="http://schemas.datacontract.org/2004/07/PolicySystemBusiness")]
    public partial class DeviceVersion : object
    {
        
        private System.Nullable<int> CellFirmwareField;
        
        private System.Nullable<int> ConfigFirmwareField;
        
        private string DescriptionField;
        
        private System.Nullable<byte> DeviceCategoryIDField;
        
        private string DeviceManufacturerField;
        
        private System.Nullable<short> DevicePriorityField;
        
        private int DeviceVersionIDField;
        
        private string DeviceVersionNameField;
        
        private System.Nullable<int> GPSFirmwareField;
        
        private string IsAvailableField;
        
        private System.Nullable<int> MainFirmwareField;
        
        private System.Nullable<int> OBD2FirmwareField;
        
        private System.Nullable<bool> SupportsAudioField;
        
        private System.Nullable<bool> SupportsBlueLEDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CellFirmware
        {
            get
            {
                return this.CellFirmwareField;
            }
            set
            {
                this.CellFirmwareField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ConfigFirmware
        {
            get
            {
                return this.ConfigFirmwareField;
            }
            set
            {
                this.ConfigFirmwareField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<byte> DeviceCategoryID
        {
            get
            {
                return this.DeviceCategoryIDField;
            }
            set
            {
                this.DeviceCategoryIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeviceManufacturer
        {
            get
            {
                return this.DeviceManufacturerField;
            }
            set
            {
                this.DeviceManufacturerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<short> DevicePriority
        {
            get
            {
                return this.DevicePriorityField;
            }
            set
            {
                this.DevicePriorityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DeviceVersionID
        {
            get
            {
                return this.DeviceVersionIDField;
            }
            set
            {
                this.DeviceVersionIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeviceVersionName
        {
            get
            {
                return this.DeviceVersionNameField;
            }
            set
            {
                this.DeviceVersionNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> GPSFirmware
        {
            get
            {
                return this.GPSFirmwareField;
            }
            set
            {
                this.GPSFirmwareField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IsAvailable
        {
            get
            {
                return this.IsAvailableField;
            }
            set
            {
                this.IsAvailableField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> MainFirmware
        {
            get
            {
                return this.MainFirmwareField;
            }
            set
            {
                this.MainFirmwareField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> OBD2Firmware
        {
            get
            {
                return this.OBD2FirmwareField;
            }
            set
            {
                this.OBD2FirmwareField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> SupportsAudio
        {
            get
            {
                return this.SupportsAudioField;
            }
            set
            {
                this.SupportsAudioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> SupportsBlueLED
        {
            get
            {
                return this.SupportsBlueLEDField;
            }
            set
            {
                this.SupportsBlueLEDField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WcfIneligibleVehiclesService.IIneligibleVehiclesService")]
    public interface IIneligibleVehiclesService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIneligibleVehiclesService/GetIneligibleVehicles", ReplyAction="http://tempuri.org/IIneligibleVehiclesService/GetIneligibleVehiclesResponse")]
        System.Threading.Tasks.Task<WcfIneligibleVehiclesService.GetIneligibleVehiclesResponse> GetIneligibleVehiclesAsync(WcfIneligibleVehiclesService.GetIneligibleVehiclesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIneligibleVehiclesService/InsertIneligibleVehicle", ReplyAction="http://tempuri.org/IIneligibleVehiclesService/InsertIneligibleVehicleResponse")]
        System.Threading.Tasks.Task<WcfIneligibleVehiclesService.InsertIneligibleVehicleResponse> InsertIneligibleVehicleAsync(WcfIneligibleVehiclesService.InsertIneligibleVehicleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIneligibleVehiclesService/UpdateIneligibleVehicle", ReplyAction="http://tempuri.org/IIneligibleVehiclesService/UpdateIneligibleVehicleResponse")]
        System.Threading.Tasks.Task<WcfIneligibleVehiclesService.UpdateIneligibleVehicleResponse> UpdateIneligibleVehicleAsync(WcfIneligibleVehiclesService.UpdateIneligibleVehicleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIneligibleVehiclesService/DeleteIneligibleVehicle", ReplyAction="http://tempuri.org/IIneligibleVehiclesService/DeleteIneligibleVehicleResponse")]
        System.Threading.Tasks.Task<WcfIneligibleVehiclesService.DeleteIneligibleVehicleResponse> DeleteIneligibleVehicleAsync(WcfIneligibleVehiclesService.DeleteIneligibleVehicleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIneligibleVehiclesService/GetDeviceVersions", ReplyAction="http://tempuri.org/IIneligibleVehiclesService/GetDeviceVersionsResponse")]
        System.Threading.Tasks.Task<WcfIneligibleVehiclesService.GetDeviceVersionsResponse> GetDeviceVersionsAsync(WcfIneligibleVehiclesService.GetDeviceVersionsRequest getDeviceVersionsRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIneligibleVehiclesService/GetIneligibleVehicle", ReplyAction="http://tempuri.org/IIneligibleVehiclesService/GetIneligibleVehicleResponse")]
        System.Threading.Tasks.Task<WcfIneligibleVehiclesService.GetIneligibleVehicleResponse> GetIneligibleVehicleAsync(WcfIneligibleVehiclesService.GetIneligibleVehicleRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface IIneligibleVehiclesServiceChannel : WcfIneligibleVehiclesService.IIneligibleVehiclesService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class IneligibleVehiclesServiceClient : System.ServiceModel.ClientBase<WcfIneligibleVehiclesService.IIneligibleVehiclesService>, WcfIneligibleVehiclesService.IIneligibleVehiclesService
    {
        
        public IneligibleVehiclesServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<WcfIneligibleVehiclesService.GetIneligibleVehiclesResponse> GetIneligibleVehiclesAsync(WcfIneligibleVehiclesService.GetIneligibleVehiclesRequest request)
        {
            return base.Channel.GetIneligibleVehiclesAsync(request);
        }
        
        public System.Threading.Tasks.Task<WcfIneligibleVehiclesService.InsertIneligibleVehicleResponse> InsertIneligibleVehicleAsync(WcfIneligibleVehiclesService.InsertIneligibleVehicleRequest request)
        {
            return base.Channel.InsertIneligibleVehicleAsync(request);
        }
        
        public System.Threading.Tasks.Task<WcfIneligibleVehiclesService.UpdateIneligibleVehicleResponse> UpdateIneligibleVehicleAsync(WcfIneligibleVehiclesService.UpdateIneligibleVehicleRequest request)
        {
            return base.Channel.UpdateIneligibleVehicleAsync(request);
        }
        
        public System.Threading.Tasks.Task<WcfIneligibleVehiclesService.DeleteIneligibleVehicleResponse> DeleteIneligibleVehicleAsync(WcfIneligibleVehiclesService.DeleteIneligibleVehicleRequest request)
        {
            return base.Channel.DeleteIneligibleVehicleAsync(request);
        }
        
        public System.Threading.Tasks.Task<WcfIneligibleVehiclesService.GetDeviceVersionsResponse> GetDeviceVersionsAsync(WcfIneligibleVehiclesService.GetDeviceVersionsRequest getDeviceVersionsRequest)
        {
            return base.Channel.GetDeviceVersionsAsync(getDeviceVersionsRequest);
        }
        
        public System.Threading.Tasks.Task<WcfIneligibleVehiclesService.GetIneligibleVehicleResponse> GetIneligibleVehicleAsync(WcfIneligibleVehiclesService.GetIneligibleVehicleRequest request)
        {
            return base.Channel.GetIneligibleVehicleAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }

        public static System.ServiceModel.Channels.Binding DefaultBinding()
        {
            return GetBindingForEndpoint(EndpointConfiguration.WSHttpBinding_IIneligibleVehiclesService);
        }

        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WSHttpBinding_IIneligibleVehiclesService))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }

        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WSHttpBinding_IIneligibleVehiclesService))
            {
                return new System.ServiceModel.EndpointAddress("http://t-ubi-myrate-services/PolicySystemBusiness/Services/IneligibleVehicles/ineligiblevehiclesservice.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }

        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return IneligibleVehiclesServiceClient.GetBindingForEndpoint(EndpointConfiguration.WSHttpBinding_IIneligibleVehiclesService);
        }

        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return IneligibleVehiclesServiceClient.GetEndpointAddress(EndpointConfiguration.WSHttpBinding_IIneligibleVehiclesService);
        }

        public enum EndpointConfiguration
        {
            WSHttpBinding_IIneligibleVehiclesService
        }
    }
}
