//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfEligibleZipCodesService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UBIServiceRequest", Namespace="http://schemas.datacontract.org/2004/07/Progressive.UBI.Shared.UBIServicesLib")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WcfEligibleZipCodesService.InsertEligibleZipCodeRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WcfEligibleZipCodesService.DeleteEligibleZipCodeRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WcfEligibleZipCodesService.UpdateEligibleZipCodeRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WcfEligibleZipCodesService.GetEligibleZipCodesRequest))]
    public partial class UBIServiceRequest : object
    {
        
        private int VersionField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Version
        {
            get
            {
                return this.VersionField;
            }
            set
            {
                this.VersionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InsertEligibleZipCodeRequest", Namespace="http://schemas.datacontract.org/2004/07/PolicySystemBusiness")]
    public partial class InsertEligibleZipCodeRequest : WcfEligibleZipCodesService.UBIServiceRequest
    {
        
        private string StateField;
        
        private string ZipCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string State
        {
            get
            {
                return this.StateField;
            }
            set
            {
                this.StateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ZipCode
        {
            get
            {
                return this.ZipCodeField;
            }
            set
            {
                this.ZipCodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeleteEligibleZipCodeRequest", Namespace="http://schemas.datacontract.org/2004/07/PolicySystemBusiness")]
    public partial class DeleteEligibleZipCodeRequest : WcfEligibleZipCodesService.UBIServiceRequest
    {
        
        private string StateField;
        
        private string ZipCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string State
        {
            get
            {
                return this.StateField;
            }
            set
            {
                this.StateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ZipCode
        {
            get
            {
                return this.ZipCodeField;
            }
            set
            {
                this.ZipCodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdateEligibleZipCodeRequest", Namespace="http://schemas.datacontract.org/2004/07/PolicySystemBusiness")]
    public partial class UpdateEligibleZipCodeRequest : WcfEligibleZipCodesService.UBIServiceRequest
    {
        
        private System.Nullable<System.DateTime> EffectiveDateField;
        
        private System.Nullable<System.DateTime> ExpirationDateField;
        
        private string StateField;
        
        private string ZipCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> EffectiveDate
        {
            get
            {
                return this.EffectiveDateField;
            }
            set
            {
                this.EffectiveDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ExpirationDate
        {
            get
            {
                return this.ExpirationDateField;
            }
            set
            {
                this.ExpirationDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string State
        {
            get
            {
                return this.StateField;
            }
            set
            {
                this.StateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZipCode
        {
            get
            {
                return this.ZipCodeField;
            }
            set
            {
                this.ZipCodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetEligibleZipCodesRequest", Namespace="http://schemas.datacontract.org/2004/07/PolicySystemBusiness")]
    public partial class GetEligibleZipCodesRequest : WcfEligibleZipCodesService.UBIServiceRequest
    {
        
        private string StateField;
        
        private string ZipCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string State
        {
            get
            {
                return this.StateField;
            }
            set
            {
                this.StateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZipCode
        {
            get
            {
                return this.ZipCodeField;
            }
            set
            {
                this.ZipCodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UBIServiceResponse", Namespace="http://schemas.datacontract.org/2004/07/Progressive.UBI.Shared.UBIServicesLib")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WcfEligibleZipCodesService.InsertEligibleZipCodeResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WcfEligibleZipCodesService.DeleteEligibleZipCodeResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WcfEligibleZipCodesService.UpdateEligibleZipCodeResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WcfEligibleZipCodesService.GetEligibleZipCodesResponse))]
    public partial class UBIServiceResponse : object
    {
        
        private WcfEligibleZipCodesService.ResponseError[] ResponseErrorsField;
        
        private WcfEligibleZipCodesService.ResponseStatus ResponseStatusField;
        
        private int VersionField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public WcfEligibleZipCodesService.ResponseError[] ResponseErrors
        {
            get
            {
                return this.ResponseErrorsField;
            }
            set
            {
                this.ResponseErrorsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public WcfEligibleZipCodesService.ResponseStatus ResponseStatus
        {
            get
            {
                return this.ResponseStatusField;
            }
            set
            {
                this.ResponseStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Version
        {
            get
            {
                return this.VersionField;
            }
            set
            {
                this.VersionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InsertEligibleZipCodeResponse", Namespace="http://schemas.datacontract.org/2004/07/PolicySystemBusiness")]
    public partial class InsertEligibleZipCodeResponse : WcfEligibleZipCodesService.UBIServiceResponse
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeleteEligibleZipCodeResponse", Namespace="http://schemas.datacontract.org/2004/07/PolicySystemBusiness")]
    public partial class DeleteEligibleZipCodeResponse : WcfEligibleZipCodesService.UBIServiceResponse
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdateEligibleZipCodeResponse", Namespace="http://schemas.datacontract.org/2004/07/PolicySystemBusiness")]
    public partial class UpdateEligibleZipCodeResponse : WcfEligibleZipCodesService.UBIServiceResponse
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetEligibleZipCodesResponse", Namespace="http://schemas.datacontract.org/2004/07/PolicySystemBusiness")]
    public partial class GetEligibleZipCodesResponse : WcfEligibleZipCodesService.UBIServiceResponse
    {
        
        private WcfEligibleZipCodesService.EligibleZipCode[] EligibleZipCodesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WcfEligibleZipCodesService.EligibleZipCode[] EligibleZipCodes
        {
            get
            {
                return this.EligibleZipCodesField;
            }
            set
            {
                this.EligibleZipCodesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseError", Namespace="http://schemas.datacontract.org/2004/07/Progressive.UBI.Shared.UBIServicesLib")]
    public partial class ResponseError : object
    {
        
        private string ErrorCodeField;
        
        private string FieldField;
        
        private string MessageField;
        
        private WcfEligibleZipCodesService.ErrorSeverityCode SeverityCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorCode
        {
            get
            {
                return this.ErrorCodeField;
            }
            set
            {
                this.ErrorCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Field
        {
            get
            {
                return this.FieldField;
            }
            set
            {
                this.FieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WcfEligibleZipCodesService.ErrorSeverityCode SeverityCode
        {
            get
            {
                return this.SeverityCodeField;
            }
            set
            {
                this.SeverityCodeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseStatus", Namespace="http://schemas.datacontract.org/2004/07/Progressive.UBI.Shared.UBIServicesLib")]
    public enum ResponseStatus : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Failure = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SuccessWithWarning = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FailureWithWarning = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PartialSuccess = 5,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EligibleZipCode", Namespace="http://schemas.datacontract.org/2004/07/PolicySystemBusiness")]
    public partial class EligibleZipCode : object
    {
        
        private string StateField;
        
        private string ZipCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string State
        {
            get
            {
                return this.StateField;
            }
            set
            {
                this.StateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZipCode
        {
            get
            {
                return this.ZipCodeField;
            }
            set
            {
                this.ZipCodeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ErrorSeverityCode", Namespace="http://schemas.datacontract.org/2004/07/Progressive.UBI.Shared.UBIServicesLib")]
    public enum ErrorSeverityCode : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Warning = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Validation = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Exception = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Ticket = 5,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WcfEligibleZipCodesService.IEligibleZipCodesService")]
    public interface IEligibleZipCodesService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEligibleZipCodesService/GetEligibleZipCodes", ReplyAction="http://tempuri.org/IEligibleZipCodesService/GetEligibleZipCodesResponse")]
        System.Threading.Tasks.Task<WcfEligibleZipCodesService.GetEligibleZipCodesResponse> GetEligibleZipCodesAsync(WcfEligibleZipCodesService.GetEligibleZipCodesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEligibleZipCodesService/InsertEligibleZipCode", ReplyAction="http://tempuri.org/IEligibleZipCodesService/InsertEligibleZipCodeResponse")]
        System.Threading.Tasks.Task<WcfEligibleZipCodesService.InsertEligibleZipCodeResponse> InsertEligibleZipCodeAsync(WcfEligibleZipCodesService.InsertEligibleZipCodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEligibleZipCodesService/DeleteEligibleZipCode", ReplyAction="http://tempuri.org/IEligibleZipCodesService/DeleteEligibleZipCodeResponse")]
        System.Threading.Tasks.Task<WcfEligibleZipCodesService.DeleteEligibleZipCodeResponse> DeleteEligibleZipCodeAsync(WcfEligibleZipCodesService.DeleteEligibleZipCodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEligibleZipCodesService/UpdateEligibleZipCode", ReplyAction="http://tempuri.org/IEligibleZipCodesService/UpdateEligibleZipCodeResponse")]
        System.Threading.Tasks.Task<WcfEligibleZipCodesService.UpdateEligibleZipCodeResponse> UpdateEligibleZipCodeAsync(WcfEligibleZipCodesService.UpdateEligibleZipCodeRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface IEligibleZipCodesServiceChannel : WcfEligibleZipCodesService.IEligibleZipCodesService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class EligibleZipCodesServiceClient : System.ServiceModel.ClientBase<WcfEligibleZipCodesService.IEligibleZipCodesService>, WcfEligibleZipCodesService.IEligibleZipCodesService
    {
        
        public EligibleZipCodesServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<WcfEligibleZipCodesService.GetEligibleZipCodesResponse> GetEligibleZipCodesAsync(WcfEligibleZipCodesService.GetEligibleZipCodesRequest request)
        {
            return base.Channel.GetEligibleZipCodesAsync(request);
        }
        
        public System.Threading.Tasks.Task<WcfEligibleZipCodesService.InsertEligibleZipCodeResponse> InsertEligibleZipCodeAsync(WcfEligibleZipCodesService.InsertEligibleZipCodeRequest request)
        {
            return base.Channel.InsertEligibleZipCodeAsync(request);
        }
        
        public System.Threading.Tasks.Task<WcfEligibleZipCodesService.DeleteEligibleZipCodeResponse> DeleteEligibleZipCodeAsync(WcfEligibleZipCodesService.DeleteEligibleZipCodeRequest request)
        {
            return base.Channel.DeleteEligibleZipCodeAsync(request);
        }
        
        public System.Threading.Tasks.Task<WcfEligibleZipCodesService.UpdateEligibleZipCodeResponse> UpdateEligibleZipCodeAsync(WcfEligibleZipCodesService.UpdateEligibleZipCodeRequest request)
        {
            return base.Channel.UpdateEligibleZipCodeAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }

        public static System.ServiceModel.Channels.Binding DefaultBinding()
        {
            return GetBindingForEndpoint(EndpointConfiguration.WSHttpBinding_IEligibleZipCodeService);
        }

        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WSHttpBinding_IEligibleZipCodeService))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }

        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WSHttpBinding_IEligibleZipCodeService))
            {
                return new System.ServiceModel.EndpointAddress("http://t-ubi-myrate-services/PolicySystemBusiness/Services/EligibleZipCodes/eligiblezipcodesservice.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }

        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return EligibleZipCodesServiceClient.GetBindingForEndpoint(EndpointConfiguration.WSHttpBinding_IEligibleZipCodeService);
        }

        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return EligibleZipCodesServiceClient.GetEndpointAddress(EndpointConfiguration.WSHttpBinding_IEligibleZipCodeService);
        }

        public enum EndpointConfiguration
        {
            WSHttpBinding_IEligibleZipCodeService
        }
    }
}
