//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfPolicyService
{
    using System.Runtime.Serialization;


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "UBIServiceRequest", Namespace = "http://schemas.datacontract.org/2004/07/Progressive.UBI.Shared.UBIServicesLib")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WcfPolicyService.UpdateAddressRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WcfPolicyService.CancelRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WcfPolicyService.ReinstateRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WcfPolicyService.GetPolicyPeriodsRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WcfPolicyService.GetPolicyCommunicationsRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WcfPolicyService.PolicyMergeRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WcfPolicyService.GetPolicyRequest))]
    public partial class UBIServiceRequest : object
    {

        private int VersionField;

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public int Version
        {
            get
            {
                return this.VersionField;
            }
            set
            {
                this.VersionField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "UpdateAddressRequest", Namespace = "http://schemas.datacontract.org/2004/07/PolicySystemBusiness")]
    public partial class UpdateAddressRequest : WcfPolicyService.UBIServiceRequest
    {

        private string Address1Field;

        private string Address2Field;

        private string CityField;

        private string MailingStateField;

        private string NameField;

        private string PolicyNumberField;

        private string ZipField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address1
        {
            get
            {
                return this.Address1Field;
            }
            set
            {
                this.Address1Field = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address2
        {
            get
            {
                return this.Address2Field;
            }
            set
            {
                this.Address2Field = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City
        {
            get
            {
                return this.CityField;
            }
            set
            {
                this.CityField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MailingState
        {
            get
            {
                return this.MailingStateField;
            }
            set
            {
                this.MailingStateField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public string PolicyNumber
        {
            get
            {
                return this.PolicyNumberField;
            }
            set
            {
                this.PolicyNumberField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Zip
        {
            get
            {
                return this.ZipField;
            }
            set
            {
                this.ZipField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "CancelRequest", Namespace = "http://schemas.datacontract.org/2004/07/PolicySystemBusiness")]
    public partial class CancelRequest : WcfPolicyService.UBIServiceRequest
    {

        private string PolicyNumberField;

        private string UserNameField;

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public string PolicyNumber
        {
            get
            {
                return this.PolicyNumberField;
            }
            set
            {
                this.PolicyNumberField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName
        {
            get
            {
                return this.UserNameField;
            }
            set
            {
                this.UserNameField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ReinstateRequest", Namespace = "http://schemas.datacontract.org/2004/07/PolicySystemBusiness")]
    public partial class ReinstateRequest : WcfPolicyService.UBIServiceRequest
    {

        private string PolicyNumberField;

        private string UserNameField;

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public string PolicyNumber
        {
            get
            {
                return this.PolicyNumberField;
            }
            set
            {
                this.PolicyNumberField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName
        {
            get
            {
                return this.UserNameField;
            }
            set
            {
                this.UserNameField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "GetPolicyPeriodsRequest", Namespace = "http://schemas.datacontract.org/2004/07/PolicySystemBusiness")]
    public partial class GetPolicyPeriodsRequest : WcfPolicyService.UBIServiceRequest
    {

        private string PolicyNumberField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PolicyNumber
        {
            get
            {
                return this.PolicyNumberField;
            }
            set
            {
                this.PolicyNumberField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "GetPolicyCommunicationsRequest", Namespace = "http://schemas.datacontract.org/2004/07/PolicySystemBusiness")]
    public partial class GetPolicyCommunicationsRequest : WcfPolicyService.UBIServiceRequest
    {

        private System.Nullable<int> ParticipantSeqIDField;

        private string PolicyNumberField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ParticipantSeqID
        {
            get
            {
                return this.ParticipantSeqIDField;
            }
            set
            {
                this.ParticipantSeqIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PolicyNumber
        {
            get
            {
                return this.PolicyNumberField;
            }
            set
            {
                this.PolicyNumberField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "PolicyMergeRequest", Namespace = "http://schemas.datacontract.org/2004/07/PolicySystemBusiness")]
    public partial class PolicyMergeRequest : WcfPolicyService.UBIServiceRequest
    {

        private WcfPolicyService.Policy NewPolicyField;

        private WcfPolicyService.Policy OldPolicyField;

        private string UserNameField;

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public WcfPolicyService.Policy NewPolicy
        {
            get
            {
                return this.NewPolicyField;
            }
            set
            {
                this.NewPolicyField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public WcfPolicyService.Policy OldPolicy
        {
            get
            {
                return this.OldPolicyField;
            }
            set
            {
                this.OldPolicyField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName
        {
            get
            {
                return this.UserNameField;
            }
            set
            {
                this.UserNameField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "GetPolicyRequest", Namespace = "http://schemas.datacontract.org/2004/07/PolicySystemBusiness")]
    public partial class GetPolicyRequest : WcfPolicyService.UBIServiceRequest
    {

        private string DeviceSerialNumberField;

        private System.Nullable<short> ExpirationYearField;

        private string GroupExternalIdField;

        private string PolicyNumberField;

        private System.Nullable<short> PolicySuffixField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeviceSerialNumber
        {
            get
            {
                return this.DeviceSerialNumberField;
            }
            set
            {
                this.DeviceSerialNumberField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<short> ExpirationYear
        {
            get
            {
                return this.ExpirationYearField;
            }
            set
            {
                this.ExpirationYearField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GroupExternalId
        {
            get
            {
                return this.GroupExternalIdField;
            }
            set
            {
                this.GroupExternalIdField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PolicyNumber
        {
            get
            {
                return this.PolicyNumberField;
            }
            set
            {
                this.PolicyNumberField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<short> PolicySuffix
        {
            get
            {
                return this.PolicySuffixField;
            }
            set
            {
                this.PolicySuffixField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Policy", Namespace = "http://schemas.datacontract.org/2004/07/PolicySystemBusiness")]
    public partial class Policy : object
    {

        private string Address1Field;

        private string Address2Field;

        private string AppNameField;

        private System.Nullable<System.DateTime> AssignmentExpirationDateTimeField;

        private System.DateTime ChangeEffectiveDateField;

        private string ChannelIndicatorField;

        private string CityField;

        private System.DateTime CreateDateField;

        private string DeviceCategoryDescriptionField;

        private int DeviceCategoryIDField;

        private WcfPolicyService.Driver[] DriversField;

        private System.DateTime ExpirationDateField;

        private string GroupExternalIdField;

        private System.DateTime InceptionDateField;

        private bool IsMaxPolicyPeriodFlagField;

        private bool IsMigratedFromTrialField;

        private string MailingStateField;

        private string NameField;

        private WcfPolicyService.Participant[] ParticipantsField;

        private string ParticipationSubTypeField;

        private string ParticipationTypeField;

        private string PolicyNumberField;

        private int PolicyPeriodSeqIDField;

        private WcfPolicyService.PolicyPeriodModel[] PolicyPeriodsField;

        private int PolicySeqIDField;

        private string PolicySuffixField;

        private string PolicySystemField;

        private string StateField;

        private string ZipField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address1
        {
            get
            {
                return this.Address1Field;
            }
            set
            {
                this.Address1Field = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address2
        {
            get
            {
                return this.Address2Field;
            }
            set
            {
                this.Address2Field = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AppName
        {
            get
            {
                return this.AppNameField;
            }
            set
            {
                this.AppNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> AssignmentExpirationDateTime
        {
            get
            {
                return this.AssignmentExpirationDateTimeField;
            }
            set
            {
                this.AssignmentExpirationDateTimeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ChangeEffectiveDate
        {
            get
            {
                return this.ChangeEffectiveDateField;
            }
            set
            {
                this.ChangeEffectiveDateField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ChannelIndicator
        {
            get
            {
                return this.ChannelIndicatorField;
            }
            set
            {
                this.ChannelIndicatorField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City
        {
            get
            {
                return this.CityField;
            }
            set
            {
                this.CityField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreateDate
        {
            get
            {
                return this.CreateDateField;
            }
            set
            {
                this.CreateDateField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeviceCategoryDescription
        {
            get
            {
                return this.DeviceCategoryDescriptionField;
            }
            set
            {
                this.DeviceCategoryDescriptionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DeviceCategoryID
        {
            get
            {
                return this.DeviceCategoryIDField;
            }
            set
            {
                this.DeviceCategoryIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public WcfPolicyService.Driver[] Drivers
        {
            get
            {
                return this.DriversField;
            }
            set
            {
                this.DriversField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ExpirationDate
        {
            get
            {
                return this.ExpirationDateField;
            }
            set
            {
                this.ExpirationDateField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GroupExternalId
        {
            get
            {
                return this.GroupExternalIdField;
            }
            set
            {
                this.GroupExternalIdField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime InceptionDate
        {
            get
            {
                return this.InceptionDateField;
            }
            set
            {
                this.InceptionDateField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsMaxPolicyPeriodFlag
        {
            get
            {
                return this.IsMaxPolicyPeriodFlagField;
            }
            set
            {
                this.IsMaxPolicyPeriodFlagField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsMigratedFromTrial
        {
            get
            {
                return this.IsMigratedFromTrialField;
            }
            set
            {
                this.IsMigratedFromTrialField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MailingState
        {
            get
            {
                return this.MailingStateField;
            }
            set
            {
                this.MailingStateField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public WcfPolicyService.Participant[] Participants
        {
            get
            {
                return this.ParticipantsField;
            }
            set
            {
                this.ParticipantsField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ParticipationSubType
        {
            get
            {
                return this.ParticipationSubTypeField;
            }
            set
            {
                this.ParticipationSubTypeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ParticipationType
        {
            get
            {
                return this.ParticipationTypeField;
            }
            set
            {
                this.ParticipationTypeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PolicyNumber
        {
            get
            {
                return this.PolicyNumberField;
            }
            set
            {
                this.PolicyNumberField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PolicyPeriodSeqID
        {
            get
            {
                return this.PolicyPeriodSeqIDField;
            }
            set
            {
                this.PolicyPeriodSeqIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public WcfPolicyService.PolicyPeriodModel[] PolicyPeriods
        {
            get
            {
                return this.PolicyPeriodsField;
            }
            set
            {
                this.PolicyPeriodsField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PolicySeqID
        {
            get
            {
                return this.PolicySeqIDField;
            }
            set
            {
                this.PolicySeqIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PolicySuffix
        {
            get
            {
                return this.PolicySuffixField;
            }
            set
            {
                this.PolicySuffixField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PolicySystem
        {
            get
            {
                return this.PolicySystemField;
            }
            set
            {
                this.PolicySystemField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string State
        {
            get
            {
                return this.StateField;
            }
            set
            {
                this.StateField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Zip
        {
            get
            {
                return this.ZipField;
            }
            set
            {
                this.ZipField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Driver", Namespace = "http://schemas.datacontract.org/2004/07/PolicySystemBusiness")]
    public partial class Driver : object
    {

        private string DriverExternalIdField;

        private string DriverFirstNameField;

        private string DriverLastNameField;

        private System.Nullable<int> DriverSeqIdField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DriverExternalId
        {
            get
            {
                return this.DriverExternalIdField;
            }
            set
            {
                this.DriverExternalIdField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DriverFirstName
        {
            get
            {
                return this.DriverFirstNameField;
            }
            set
            {
                this.DriverFirstNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DriverLastName
        {
            get
            {
                return this.DriverLastNameField;
            }
            set
            {
                this.DriverLastNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> DriverSeqId
        {
            get
            {
                return this.DriverSeqIdField;
            }
            set
            {
                this.DriverSeqIdField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Participant", Namespace = "http://schemas.datacontract.org/2004/07/PolicySystemBusiness")]
    public partial class Participant : object
    {

        private bool ActivateDeviceField;

        private System.Nullable<bool> AudioOnField;

        private WcfPolicyService.BillingTransaction[] BillingTransactionsField;

        private System.DateTime ChangeEffectiveDateField;

        private System.Nullable<bool> CrashDetectionDeviceEligibleField;

        private System.Nullable<System.DateTime> CrashDetectionEligibleDateTimeField;

        private System.Nullable<System.DateTime> CrashDetectionIneligibleDateTimeField;

        private System.Nullable<bool> CrashDetectionProgramEligibleField;

        private System.Nullable<System.DateTime> DeviceAbandonedDateField;

        private int DeviceExperienceTypeCodeField;

        private string DeviceManufacturerField;

        private System.Nullable<System.DateTime> DeviceReceivedDateField;

        private System.Nullable<System.DateTime> DeviceRecoveryStartDateField;

        private System.Nullable<int> DeviceSeqIDField;

        private string DeviceSerialNumberField;

        private string DeviceVersionField;

        private System.Nullable<int> DriverSeqIdField;

        private System.Nullable<System.DateTime> EnrollmentDateField;

        private System.Nullable<System.DateTime> FirstContactDateTimeField;

        private System.Nullable<int> HomeBaseDeviceSeqIdField;

        private System.Nullable<System.DateTime> InitialFirstContactDateTimeField;

        private System.DateTime InstallDeadlineField;

        private bool IsMigratedFromTrialField;

        private System.Nullable<System.DateTime> LastContactDateTimeField;

        private System.Nullable<System.DateTime> LastUploadDateTimeField;

        private string MakeField;

        private string MobileDeviceAliasNameField;

        private string ModelField;

        private string ModelYearField;

        private short MonitoringCompleteConnectDaysField;

        private System.Nullable<System.DateTime> OptOutDateField;

        private string OptOutReasonDescriptionField;

        private string ParticipantExternalIDField;

        private string ParticipantIDField;

        private int ParticipantSeqIDField;

        private string PendingDeviceSerialNumberField;

        private System.Nullable<System.DateTime> PolicyStartDateField;

        private string ProgramTypeField;

        private int QualifyingPeriodSeqIDField;

        private string ReasonField;

        private int ReasonCodeField;

        private System.Nullable<int> ReturnReasonCodeField;

        private string ReturnReasonDescriptionField;

        private string SIMField;

        private System.Nullable<int> ScoringAlgorithmCodeField;

        private System.Nullable<System.DateTime> ShipDateTimeField;

        private string StatusField;

        private System.Nullable<System.DateTime> TrialStartDateField;

        private string VINField;

        private System.Nullable<int> VehicleSeqIDField;

        private string WirelessStatusField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ActivateDevice
        {
            get
            {
                return this.ActivateDeviceField;
            }
            set
            {
                this.ActivateDeviceField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> AudioOn
        {
            get
            {
                return this.AudioOnField;
            }
            set
            {
                this.AudioOnField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public WcfPolicyService.BillingTransaction[] BillingTransactions
        {
            get
            {
                return this.BillingTransactionsField;
            }
            set
            {
                this.BillingTransactionsField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ChangeEffectiveDate
        {
            get
            {
                return this.ChangeEffectiveDateField;
            }
            set
            {
                this.ChangeEffectiveDateField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> CrashDetectionDeviceEligible
        {
            get
            {
                return this.CrashDetectionDeviceEligibleField;
            }
            set
            {
                this.CrashDetectionDeviceEligibleField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CrashDetectionEligibleDateTime
        {
            get
            {
                return this.CrashDetectionEligibleDateTimeField;
            }
            set
            {
                this.CrashDetectionEligibleDateTimeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CrashDetectionIneligibleDateTime
        {
            get
            {
                return this.CrashDetectionIneligibleDateTimeField;
            }
            set
            {
                this.CrashDetectionIneligibleDateTimeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> CrashDetectionProgramEligible
        {
            get
            {
                return this.CrashDetectionProgramEligibleField;
            }
            set
            {
                this.CrashDetectionProgramEligibleField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DeviceAbandonedDate
        {
            get
            {
                return this.DeviceAbandonedDateField;
            }
            set
            {
                this.DeviceAbandonedDateField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DeviceExperienceTypeCode
        {
            get
            {
                return this.DeviceExperienceTypeCodeField;
            }
            set
            {
                this.DeviceExperienceTypeCodeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeviceManufacturer
        {
            get
            {
                return this.DeviceManufacturerField;
            }
            set
            {
                this.DeviceManufacturerField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DeviceReceivedDate
        {
            get
            {
                return this.DeviceReceivedDateField;
            }
            set
            {
                this.DeviceReceivedDateField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DeviceRecoveryStartDate
        {
            get
            {
                return this.DeviceRecoveryStartDateField;
            }
            set
            {
                this.DeviceRecoveryStartDateField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> DeviceSeqID
        {
            get
            {
                return this.DeviceSeqIDField;
            }
            set
            {
                this.DeviceSeqIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeviceSerialNumber
        {
            get
            {
                return this.DeviceSerialNumberField;
            }
            set
            {
                this.DeviceSerialNumberField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeviceVersion
        {
            get
            {
                return this.DeviceVersionField;
            }
            set
            {
                this.DeviceVersionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> DriverSeqId
        {
            get
            {
                return this.DriverSeqIdField;
            }
            set
            {
                this.DriverSeqIdField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> EnrollmentDate
        {
            get
            {
                return this.EnrollmentDateField;
            }
            set
            {
                this.EnrollmentDateField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FirstContactDateTime
        {
            get
            {
                return this.FirstContactDateTimeField;
            }
            set
            {
                this.FirstContactDateTimeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> HomeBaseDeviceSeqId
        {
            get
            {
                return this.HomeBaseDeviceSeqIdField;
            }
            set
            {
                this.HomeBaseDeviceSeqIdField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> InitialFirstContactDateTime
        {
            get
            {
                return this.InitialFirstContactDateTimeField;
            }
            set
            {
                this.InitialFirstContactDateTimeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime InstallDeadline
        {
            get
            {
                return this.InstallDeadlineField;
            }
            set
            {
                this.InstallDeadlineField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsMigratedFromTrial
        {
            get
            {
                return this.IsMigratedFromTrialField;
            }
            set
            {
                this.IsMigratedFromTrialField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> LastContactDateTime
        {
            get
            {
                return this.LastContactDateTimeField;
            }
            set
            {
                this.LastContactDateTimeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> LastUploadDateTime
        {
            get
            {
                return this.LastUploadDateTimeField;
            }
            set
            {
                this.LastUploadDateTimeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Make
        {
            get
            {
                return this.MakeField;
            }
            set
            {
                this.MakeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MobileDeviceAliasName
        {
            get
            {
                return this.MobileDeviceAliasNameField;
            }
            set
            {
                this.MobileDeviceAliasNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Model
        {
            get
            {
                return this.ModelField;
            }
            set
            {
                this.ModelField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModelYear
        {
            get
            {
                return this.ModelYearField;
            }
            set
            {
                this.ModelYearField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public short MonitoringCompleteConnectDays
        {
            get
            {
                return this.MonitoringCompleteConnectDaysField;
            }
            set
            {
                this.MonitoringCompleteConnectDaysField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> OptOutDate
        {
            get
            {
                return this.OptOutDateField;
            }
            set
            {
                this.OptOutDateField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OptOutReasonDescription
        {
            get
            {
                return this.OptOutReasonDescriptionField;
            }
            set
            {
                this.OptOutReasonDescriptionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ParticipantExternalID
        {
            get
            {
                return this.ParticipantExternalIDField;
            }
            set
            {
                this.ParticipantExternalIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ParticipantID
        {
            get
            {
                return this.ParticipantIDField;
            }
            set
            {
                this.ParticipantIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ParticipantSeqID
        {
            get
            {
                return this.ParticipantSeqIDField;
            }
            set
            {
                this.ParticipantSeqIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PendingDeviceSerialNumber
        {
            get
            {
                return this.PendingDeviceSerialNumberField;
            }
            set
            {
                this.PendingDeviceSerialNumberField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> PolicyStartDate
        {
            get
            {
                return this.PolicyStartDateField;
            }
            set
            {
                this.PolicyStartDateField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProgramType
        {
            get
            {
                return this.ProgramTypeField;
            }
            set
            {
                this.ProgramTypeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int QualifyingPeriodSeqID
        {
            get
            {
                return this.QualifyingPeriodSeqIDField;
            }
            set
            {
                this.QualifyingPeriodSeqIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Reason
        {
            get
            {
                return this.ReasonField;
            }
            set
            {
                this.ReasonField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ReasonCode
        {
            get
            {
                return this.ReasonCodeField;
            }
            set
            {
                this.ReasonCodeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ReturnReasonCode
        {
            get
            {
                return this.ReturnReasonCodeField;
            }
            set
            {
                this.ReturnReasonCodeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReturnReasonDescription
        {
            get
            {
                return this.ReturnReasonDescriptionField;
            }
            set
            {
                this.ReturnReasonDescriptionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SIM
        {
            get
            {
                return this.SIMField;
            }
            set
            {
                this.SIMField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ScoringAlgorithmCode
        {
            get
            {
                return this.ScoringAlgorithmCodeField;
            }
            set
            {
                this.ScoringAlgorithmCodeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ShipDateTime
        {
            get
            {
                return this.ShipDateTimeField;
            }
            set
            {
                this.ShipDateTimeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> TrialStartDate
        {
            get
            {
                return this.TrialStartDateField;
            }
            set
            {
                this.TrialStartDateField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VIN
        {
            get
            {
                return this.VINField;
            }
            set
            {
                this.VINField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> VehicleSeqID
        {
            get
            {
                return this.VehicleSeqIDField;
            }
            set
            {
                this.VehicleSeqIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WirelessStatus
        {
            get
            {
                return this.WirelessStatusField;
            }
            set
            {
                this.WirelessStatusField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "PolicyPeriodModel", Namespace = "http://schemas.datacontract.org/2004/07/PolicySystemBusiness")]
    public partial class PolicyPeriodModel : object
    {

        private System.DateTime CreateDateField;

        private System.DateTime ExpirationDateField;

        private short ExpirationYearField;

        private string GroupExternalIdField;

        private System.DateTime InceptionDateField;

        private System.Nullable<System.DateTime> LastChangeDateTimeField;

        private int PolicyPeriodSeqIdField;

        private int PolicySeqIdField;

        private short PolicySuffixField;

        private string PolicySystemField;

        private string RateRevisionField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreateDate
        {
            get
            {
                return this.CreateDateField;
            }
            set
            {
                this.CreateDateField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ExpirationDate
        {
            get
            {
                return this.ExpirationDateField;
            }
            set
            {
                this.ExpirationDateField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public short ExpirationYear
        {
            get
            {
                return this.ExpirationYearField;
            }
            set
            {
                this.ExpirationYearField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GroupExternalId
        {
            get
            {
                return this.GroupExternalIdField;
            }
            set
            {
                this.GroupExternalIdField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime InceptionDate
        {
            get
            {
                return this.InceptionDateField;
            }
            set
            {
                this.InceptionDateField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> LastChangeDateTime
        {
            get
            {
                return this.LastChangeDateTimeField;
            }
            set
            {
                this.LastChangeDateTimeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PolicyPeriodSeqId
        {
            get
            {
                return this.PolicyPeriodSeqIdField;
            }
            set
            {
                this.PolicyPeriodSeqIdField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PolicySeqId
        {
            get
            {
                return this.PolicySeqIdField;
            }
            set
            {
                this.PolicySeqIdField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public short PolicySuffix
        {
            get
            {
                return this.PolicySuffixField;
            }
            set
            {
                this.PolicySuffixField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PolicySystem
        {
            get
            {
                return this.PolicySystemField;
            }
            set
            {
                this.PolicySystemField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RateRevision
        {
            get
            {
                return this.RateRevisionField;
            }
            set
            {
                this.RateRevisionField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "BillingTransaction", Namespace = "http://schemas.datacontract.org/2004/07/PolicySystemBusiness")]
    public partial class BillingTransaction : object
    {

        private string AmountField;

        private System.DateTime CreateDateField;

        private string DescriptionField;

        private int DeviceSeqIDField;

        private string DeviceSerialNumberField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Amount
        {
            get
            {
                return this.AmountField;
            }
            set
            {
                this.AmountField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreateDate
        {
            get
            {
                return this.CreateDateField;
            }
            set
            {
                this.CreateDateField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DeviceSeqID
        {
            get
            {
                return this.DeviceSeqIDField;
            }
            set
            {
                this.DeviceSeqIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeviceSerialNumber
        {
            get
            {
                return this.DeviceSerialNumberField;
            }
            set
            {
                this.DeviceSerialNumberField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "UBIServiceResponse", Namespace = "http://schemas.datacontract.org/2004/07/Progressive.UBI.Shared.UBIServicesLib")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WcfPolicyService.UpdateAddressResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WcfPolicyService.CancelResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WcfPolicyService.ReinstateResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WcfPolicyService.GetPolicyPeriodsResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WcfPolicyService.GetPolicyCommunicationsResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WcfPolicyService.PolicyMergeResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WcfPolicyService.GetPolicyResponse))]
    public partial class UBIServiceResponse : object
    {

        private WcfPolicyService.ResponseError[] ResponseErrorsField;

        private WcfPolicyService.ResponseStatus ResponseStatusField;

        private int VersionField;

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public WcfPolicyService.ResponseError[] ResponseErrors
        {
            get
            {
                return this.ResponseErrorsField;
            }
            set
            {
                this.ResponseErrorsField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public WcfPolicyService.ResponseStatus ResponseStatus
        {
            get
            {
                return this.ResponseStatusField;
            }
            set
            {
                this.ResponseStatusField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public int Version
        {
            get
            {
                return this.VersionField;
            }
            set
            {
                this.VersionField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "UpdateAddressResponse", Namespace = "http://schemas.datacontract.org/2004/07/PolicySystemBusiness")]
    public partial class UpdateAddressResponse : WcfPolicyService.UBIServiceResponse
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "CancelResponse", Namespace = "http://schemas.datacontract.org/2004/07/PolicySystemBusiness")]
    public partial class CancelResponse : WcfPolicyService.UBIServiceResponse
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ReinstateResponse", Namespace = "http://schemas.datacontract.org/2004/07/PolicySystemBusiness")]
    public partial class ReinstateResponse : WcfPolicyService.UBIServiceResponse
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "GetPolicyPeriodsResponse", Namespace = "http://schemas.datacontract.org/2004/07/PolicySystemBusiness")]
    public partial class GetPolicyPeriodsResponse : WcfPolicyService.UBIServiceResponse
    {

        private WcfPolicyService.PolicyPeriodModel[] PolicyPeriodsField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public WcfPolicyService.PolicyPeriodModel[] PolicyPeriods
        {
            get
            {
                return this.PolicyPeriodsField;
            }
            set
            {
                this.PolicyPeriodsField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "GetPolicyCommunicationsResponse", Namespace = "http://schemas.datacontract.org/2004/07/PolicySystemBusiness")]
    public partial class GetPolicyCommunicationsResponse : WcfPolicyService.UBIServiceResponse
    {

        private WcfPolicyService.CommunicationItem[] CommunicationsField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public WcfPolicyService.CommunicationItem[] Communications
        {
            get
            {
                return this.CommunicationsField;
            }
            set
            {
                this.CommunicationsField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "PolicyMergeResponse", Namespace = "http://schemas.datacontract.org/2004/07/PolicySystemBusiness")]
    public partial class PolicyMergeResponse : WcfPolicyService.UBIServiceResponse
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "GetPolicyResponse", Namespace = "http://schemas.datacontract.org/2004/07/PolicySystemBusiness")]
    public partial class GetPolicyResponse : WcfPolicyService.UBIServiceResponse
    {

        private WcfPolicyService.Policy PolicyField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public WcfPolicyService.Policy Policy
        {
            get
            {
                return this.PolicyField;
            }
            set
            {
                this.PolicyField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ResponseError", Namespace = "http://schemas.datacontract.org/2004/07/Progressive.UBI.Shared.UBIServicesLib")]
    public partial class ResponseError : object
    {

        private string ErrorCodeField;

        private string FieldField;

        private string MessageField;

        private WcfPolicyService.ErrorSeverityCode SeverityCodeField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorCode
        {
            get
            {
                return this.ErrorCodeField;
            }
            set
            {
                this.ErrorCodeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Field
        {
            get
            {
                return this.FieldField;
            }
            set
            {
                this.FieldField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public WcfPolicyService.ErrorSeverityCode SeverityCode
        {
            get
            {
                return this.SeverityCodeField;
            }
            set
            {
                this.SeverityCodeField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ResponseStatus", Namespace = "http://schemas.datacontract.org/2004/07/Progressive.UBI.Shared.UBIServicesLib")]
    public enum ResponseStatus : int
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 1,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Failure = 2,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        SuccessWithWarning = 3,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        FailureWithWarning = 4,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        PartialSuccess = 5,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ErrorSeverityCode", Namespace = "http://schemas.datacontract.org/2004/07/Progressive.UBI.Shared.UBIServicesLib")]
    public enum ErrorSeverityCode : int
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Warning = 1,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Validation = 2,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 3,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Exception = 4,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Ticket = 5,
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "CommunicationItem", Namespace = "http://schemas.datacontract.org/2004/07/PolicySystemBusiness")]
    public partial class CommunicationItem : object
    {

        private string CampaignField;

        private string DeviceSerialNumberField;

        private string MethodField;

        private int ParticipantSeqIDField;

        private System.DateTime ProcessedDateField;

        private string ReasonField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Campaign
        {
            get
            {
                return this.CampaignField;
            }
            set
            {
                this.CampaignField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeviceSerialNumber
        {
            get
            {
                return this.DeviceSerialNumberField;
            }
            set
            {
                this.DeviceSerialNumberField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Method
        {
            get
            {
                return this.MethodField;
            }
            set
            {
                this.MethodField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ParticipantSeqID
        {
            get
            {
                return this.ParticipantSeqIDField;
            }
            set
            {
                this.ParticipantSeqIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ProcessedDate
        {
            get
            {
                return this.ProcessedDateField;
            }
            set
            {
                this.ProcessedDateField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Reason
        {
            get
            {
                return this.ReasonField;
            }
            set
            {
                this.ReasonField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName = "WcfPolicyService.IPolicyService")]
    public interface IPolicyService
    {

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IPolicyService/GetPolicy", ReplyAction = "http://tempuri.org/IPolicyService/GetPolicyResponse")]
        System.Threading.Tasks.Task<WcfPolicyService.GetPolicyResponse> GetPolicyAsync(WcfPolicyService.GetPolicyRequest getPolicyRequest);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IPolicyService/UpdateAddress", ReplyAction = "http://tempuri.org/IPolicyService/UpdateAddressResponse")]
        System.Threading.Tasks.Task<WcfPolicyService.UpdateAddressResponse> UpdateAddressAsync(WcfPolicyService.UpdateAddressRequest updateAddressRequest);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IPolicyService/Cancel", ReplyAction = "http://tempuri.org/IPolicyService/CancelResponse")]
        System.Threading.Tasks.Task<WcfPolicyService.CancelResponse> CancelAsync(WcfPolicyService.CancelRequest cancelRequest);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IPolicyService/Reinstate", ReplyAction = "http://tempuri.org/IPolicyService/ReinstateResponse")]
        System.Threading.Tasks.Task<WcfPolicyService.ReinstateResponse> ReinstateAsync(WcfPolicyService.ReinstateRequest reinstateRequest);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IPolicyService/GetPolicyPeriods", ReplyAction = "http://tempuri.org/IPolicyService/GetPolicyPeriodsResponse")]
        System.Threading.Tasks.Task<WcfPolicyService.GetPolicyPeriodsResponse> GetPolicyPeriodsAsync(WcfPolicyService.GetPolicyPeriodsRequest getPolicyPeriodsRequest);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IPolicyService/GetPolicyCommunications", ReplyAction = "http://tempuri.org/IPolicyService/GetPolicyCommunicationsResponse")]
        System.Threading.Tasks.Task<WcfPolicyService.GetPolicyCommunicationsResponse> GetPolicyCommunicationsAsync(WcfPolicyService.GetPolicyCommunicationsRequest getPolicyCommunicationsRequest);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IPolicyService/PolicyMerge", ReplyAction = "http://tempuri.org/IPolicyService/PolicyMergeResponse")]
        System.Threading.Tasks.Task<WcfPolicyService.PolicyMergeResponse> PolicyMergeAsync(WcfPolicyService.PolicyMergeRequest policyMergeRequest);
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface IPolicyServiceChannel : WcfPolicyService.IPolicyService, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class PolicyServiceClient : System.ServiceModel.ClientBase<WcfPolicyService.IPolicyService>, WcfPolicyService.IPolicyService
    {

        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);

        public PolicyServiceClient() :
                base(PolicyServiceClient.GetDefaultBinding(), PolicyServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.WSHttpBinding_IPolicyService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public PolicyServiceClient(EndpointConfiguration endpointConfiguration) :
                base(PolicyServiceClient.GetBindingForEndpoint(endpointConfiguration), PolicyServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public PolicyServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) :
                base(PolicyServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public PolicyServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) :
                base(PolicyServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public PolicyServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
                base(binding, remoteAddress)
        {
        }

        public System.Threading.Tasks.Task<WcfPolicyService.GetPolicyResponse> GetPolicyAsync(WcfPolicyService.GetPolicyRequest getPolicyRequest)
        {
            return base.Channel.GetPolicyAsync(getPolicyRequest);
        }

        public System.Threading.Tasks.Task<WcfPolicyService.UpdateAddressResponse> UpdateAddressAsync(WcfPolicyService.UpdateAddressRequest updateAddressRequest)
        {
            return base.Channel.UpdateAddressAsync(updateAddressRequest);
        }

        public System.Threading.Tasks.Task<WcfPolicyService.CancelResponse> CancelAsync(WcfPolicyService.CancelRequest cancelRequest)
        {
            return base.Channel.CancelAsync(cancelRequest);
        }

        public System.Threading.Tasks.Task<WcfPolicyService.ReinstateResponse> ReinstateAsync(WcfPolicyService.ReinstateRequest reinstateRequest)
        {
            return base.Channel.ReinstateAsync(reinstateRequest);
        }

        public System.Threading.Tasks.Task<WcfPolicyService.GetPolicyPeriodsResponse> GetPolicyPeriodsAsync(WcfPolicyService.GetPolicyPeriodsRequest getPolicyPeriodsRequest)
        {
            return base.Channel.GetPolicyPeriodsAsync(getPolicyPeriodsRequest);
        }

        public System.Threading.Tasks.Task<WcfPolicyService.GetPolicyCommunicationsResponse> GetPolicyCommunicationsAsync(WcfPolicyService.GetPolicyCommunicationsRequest getPolicyCommunicationsRequest)
        {
            return base.Channel.GetPolicyCommunicationsAsync(getPolicyCommunicationsRequest);
        }

        public System.Threading.Tasks.Task<WcfPolicyService.PolicyMergeResponse> PolicyMergeAsync(WcfPolicyService.PolicyMergeRequest policyMergeRequest)
        {
            return base.Channel.PolicyMergeAsync(policyMergeRequest);
        }

        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }

        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }

        public static System.ServiceModel.Channels.Binding DefaultBinding()
        {
            return GetBindingForEndpoint(EndpointConfiguration.WSHttpBinding_IPolicyService);
        }

        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WSHttpBinding_IPolicyService))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }

        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WSHttpBinding_IPolicyService))
            {
                return new System.ServiceModel.EndpointAddress(new System.Uri("http://t-ubi-myrate-services/PolicySystemBusiness/Services/Policy/PolicyService.s" +
                            "vc"), new System.ServiceModel.DnsEndpointIdentity("localhost"));
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }

        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return PolicyServiceClient.GetBindingForEndpoint(EndpointConfiguration.WSHttpBinding_IPolicyService);
        }

        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return PolicyServiceClient.GetEndpointAddress(EndpointConfiguration.WSHttpBinding_IPolicyService);
        }

        public enum EndpointConfiguration
        {

            WSHttpBinding_IPolicyService,
        }
    }
}
