//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFReturnLabelService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UBIServiceResponse", Namespace="http://schemas.datacontract.org/2004/07/Progressive.UBI.Shared.UBIServicesLib")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WCFReturnLabelService.GetReturnLabelResponse))]
    public partial class UBIServiceResponse : object
    {
        
        private WCFReturnLabelService.ResponseError[] ResponseErrorsField;
        
        private WCFReturnLabelService.ResponseStatus ResponseStatusField;
        
        private int VersionField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public WCFReturnLabelService.ResponseError[] ResponseErrors
        {
            get
            {
                return this.ResponseErrorsField;
            }
            set
            {
                this.ResponseErrorsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public WCFReturnLabelService.ResponseStatus ResponseStatus
        {
            get
            {
                return this.ResponseStatusField;
            }
            set
            {
                this.ResponseStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Version
        {
            get
            {
                return this.VersionField;
            }
            set
            {
                this.VersionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetReturnLabelResponse", Namespace="http://schemas.datacontract.org/2004/07/HomeBaseServices.Xirgo")]
    public partial class GetReturnLabelResponse : WCFReturnLabelService.UBIServiceResponse
    {
        
        private WCFReturnLabelService.ReturnLabel ReturnLabelDataField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public WCFReturnLabelService.ReturnLabel ReturnLabelData
        {
            get
            {
                return this.ReturnLabelDataField;
            }
            set
            {
                this.ReturnLabelDataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseError", Namespace="http://schemas.datacontract.org/2004/07/Progressive.UBI.Shared.UBIServicesLib")]
    public partial class ResponseError : object
    {
        
        private string ErrorCodeField;
        
        private string FieldField;
        
        private string MessageField;
        
        private WCFReturnLabelService.ErrorSeverityCode SeverityCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorCode
        {
            get
            {
                return this.ErrorCodeField;
            }
            set
            {
                this.ErrorCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Field
        {
            get
            {
                return this.FieldField;
            }
            set
            {
                this.FieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WCFReturnLabelService.ErrorSeverityCode SeverityCode
        {
            get
            {
                return this.SeverityCodeField;
            }
            set
            {
                this.SeverityCodeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseStatus", Namespace="http://schemas.datacontract.org/2004/07/Progressive.UBI.Shared.UBIServicesLib")]
    public enum ResponseStatus : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Failure = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SuccessWithWarning = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FailureWithWarning = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PartialSuccess = 5,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReturnLabel", Namespace="http://schemas.datacontract.org/2004/07/HomeBaseServices.Xirgo")]
    public partial class ReturnLabel : object
    {
        
        private byte[] LabelField;
        
        private string PostalRoutingField;
        
        private string TrackingNumberField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Label
        {
            get
            {
                return this.LabelField;
            }
            set
            {
                this.LabelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostalRouting
        {
            get
            {
                return this.PostalRoutingField;
            }
            set
            {
                this.PostalRoutingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TrackingNumber
        {
            get
            {
                return this.TrackingNumberField;
            }
            set
            {
                this.TrackingNumberField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ErrorSeverityCode", Namespace="http://schemas.datacontract.org/2004/07/Progressive.UBI.Shared.UBIServicesLib")]
    public enum ErrorSeverityCode : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Warning = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Validation = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Exception = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Ticket = 5,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UBIServiceRequest", Namespace="http://schemas.datacontract.org/2004/07/Progressive.UBI.Shared.UBIServicesLib")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WCFReturnLabelService.GetReturnLabelRequest))]
    public partial class UBIServiceRequest : object
    {
        
        private int VersionField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Version
        {
            get
            {
                return this.VersionField;
            }
            set
            {
                this.VersionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetReturnLabelRequest", Namespace="http://schemas.datacontract.org/2004/07/HomeBaseServices.Xirgo")]
    public partial class GetReturnLabelRequest : WCFReturnLabelService.UBIServiceRequest
    {
        
        private WCFReturnLabelService.InsuranceType InsuranceTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public WCFReturnLabelService.InsuranceType InsuranceType
        {
            get
            {
                return this.InsuranceTypeField;
            }
            set
            {
                this.InsuranceTypeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InsuranceType", Namespace="http://schemas.datacontract.org/2004/07/HomeBaseServices.Commands.Xirgo.ShippingL" +
        "abel")]
    public enum InsuranceType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PersonalLines = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CommercialLines = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SpecialLines = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCFReturnLabelService.IReturnLabelService")]
    public interface IReturnLabelService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReturnLabelService/GetDistributorReturnLabel", ReplyAction="http://tempuri.org/IReturnLabelService/GetDistributorReturnLabelResponse")]
        System.Threading.Tasks.Task<WCFReturnLabelService.GetReturnLabelResponse> GetDistributorReturnLabelAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReturnLabelService/GetSelfServiceReturnLabel", ReplyAction="http://tempuri.org/IReturnLabelService/GetSelfServiceReturnLabelResponse")]
        System.Threading.Tasks.Task<WCFReturnLabelService.GetReturnLabelResponse> GetSelfServiceReturnLabelAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReturnLabelService/GetUspsDistributorReturnLabel", ReplyAction="http://tempuri.org/IReturnLabelService/GetUspsDistributorReturnLabelResponse")]
        System.Threading.Tasks.Task<WCFReturnLabelService.GetReturnLabelResponse> GetUspsDistributorReturnLabelAsync(WCFReturnLabelService.GetReturnLabelRequest getReturnLabelRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReturnLabelService/GetUspsHazmatDistributorReturnLabel", ReplyAction="http://tempuri.org/IReturnLabelService/GetUspsHazmatDistributorReturnLabelRespons" +
            "e")]
        System.Threading.Tasks.Task<WCFReturnLabelService.GetReturnLabelResponse> GetUspsHazmatDistributorReturnLabelAsync(WCFReturnLabelService.GetReturnLabelRequest getReturnLabelRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReturnLabelService/GetUspsSelfServiceReturnLabel", ReplyAction="http://tempuri.org/IReturnLabelService/GetUspsSelfServiceReturnLabelResponse")]
        System.Threading.Tasks.Task<WCFReturnLabelService.GetReturnLabelResponse> GetUspsSelfServiceReturnLabelAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface IReturnLabelServiceChannel : WCFReturnLabelService.IReturnLabelService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class ReturnLabelServiceClient : System.ServiceModel.ClientBase<WCFReturnLabelService.IReturnLabelService>, WCFReturnLabelService.IReturnLabelService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ReturnLabelServiceClient() : 
                base(ReturnLabelServiceClient.GetDefaultBinding(), ReturnLabelServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.WSHttpBinding_IReturnLabelService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ReturnLabelServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(ReturnLabelServiceClient.GetBindingForEndpoint(endpointConfiguration), ReturnLabelServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ReturnLabelServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ReturnLabelServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ReturnLabelServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ReturnLabelServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ReturnLabelServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<WCFReturnLabelService.GetReturnLabelResponse> GetDistributorReturnLabelAsync()
        {
            return base.Channel.GetDistributorReturnLabelAsync();
        }
        
        public System.Threading.Tasks.Task<WCFReturnLabelService.GetReturnLabelResponse> GetSelfServiceReturnLabelAsync()
        {
            return base.Channel.GetSelfServiceReturnLabelAsync();
        }
        
        public System.Threading.Tasks.Task<WCFReturnLabelService.GetReturnLabelResponse> GetUspsDistributorReturnLabelAsync(WCFReturnLabelService.GetReturnLabelRequest getReturnLabelRequest)
        {
            return base.Channel.GetUspsDistributorReturnLabelAsync(getReturnLabelRequest);
        }
        
        public System.Threading.Tasks.Task<WCFReturnLabelService.GetReturnLabelResponse> GetUspsHazmatDistributorReturnLabelAsync(WCFReturnLabelService.GetReturnLabelRequest getReturnLabelRequest)
        {
            return base.Channel.GetUspsHazmatDistributorReturnLabelAsync(getReturnLabelRequest);
        }
        
        public System.Threading.Tasks.Task<WCFReturnLabelService.GetReturnLabelResponse> GetUspsSelfServiceReturnLabelAsync()
        {
            return base.Channel.GetUspsSelfServiceReturnLabelAsync();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WSHttpBinding_IReturnLabelService))
            {
                System.ServiceModel.WSHttpBinding result = new System.ServiceModel.WSHttpBinding();
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.SecurityMode.None;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WSHttpBinding_IReturnLabelService))
            {
                return new System.ServiceModel.EndpointAddress("http://t-ubi-homebase-services/HomeBaseServices/Services/Xirgo/ReturnLabelService" +
                        ".svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ReturnLabelServiceClient.GetBindingForEndpoint(EndpointConfiguration.WSHttpBinding_IReturnLabelService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ReturnLabelServiceClient.GetEndpointAddress(EndpointConfiguration.WSHttpBinding_IReturnLabelService);
        }
        
        public enum EndpointConfiguration
        {
            
            WSHttpBinding_IReturnLabelService,
        }
    }
}
