//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParticipantGroupService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UBIServiceRequest", Namespace="http://schemas.datacontract.org/2004/07/Progressive.UBI.Shared.UBIServicesLib")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ParticipantGroupService.GetPartGroupByExtKeyRequest))]
    public partial class UBIServiceRequest : object
    {
        
        private int VersionField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Version
        {
            get
            {
                return this.VersionField;
            }
            set
            {
                this.VersionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetPartGroupByExtKeyRequest", Namespace="http://schemas.datacontract.org/2004/07/MyScoreBusiness.Commands.ParticipantGroup" +
        ".Get.Contract")]
    public partial class GetPartGroupByExtKeyRequest : ParticipantGroupService.UBIServiceRequest
    {
        
        private string ParticipantGroupExternalKeyField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ParticipantGroupExternalKey
        {
            get
            {
                return this.ParticipantGroupExternalKeyField;
            }
            set
            {
                this.ParticipantGroupExternalKeyField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UBIServiceResponse", Namespace="http://schemas.datacontract.org/2004/07/Progressive.UBI.Shared.UBIServicesLib")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ParticipantGroupService.GetPartGroupByExtKeyResponse))]
    public partial class UBIServiceResponse : object
    {
        
        private ParticipantGroupService.ResponseError[] ResponseErrorsField;
        
        private ParticipantGroupService.ResponseStatus ResponseStatusField;
        
        private int VersionField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ParticipantGroupService.ResponseError[] ResponseErrors
        {
            get
            {
                return this.ResponseErrorsField;
            }
            set
            {
                this.ResponseErrorsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ParticipantGroupService.ResponseStatus ResponseStatus
        {
            get
            {
                return this.ResponseStatusField;
            }
            set
            {
                this.ResponseStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Version
        {
            get
            {
                return this.VersionField;
            }
            set
            {
                this.VersionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetPartGroupByExtKeyResponse", Namespace="http://schemas.datacontract.org/2004/07/MyScoreBusiness.Commands.ParticipantGroup" +
        ".Get.Contract")]
    public partial class GetPartGroupByExtKeyResponse : ParticipantGroupService.UBIServiceResponse
    {
        
        private ParticipantGroupService.ParticipantGroup ParticipantGroupField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ParticipantGroupService.ParticipantGroup ParticipantGroup
        {
            get
            {
                return this.ParticipantGroupField;
            }
            set
            {
                this.ParticipantGroupField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseError", Namespace="http://schemas.datacontract.org/2004/07/Progressive.UBI.Shared.UBIServicesLib")]
    public partial class ResponseError : object
    {
        
        private string ErrorCodeField;
        
        private string FieldField;
        
        private string MessageField;
        
        private ParticipantGroupService.ErrorSeverityCode SeverityCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorCode
        {
            get
            {
                return this.ErrorCodeField;
            }
            set
            {
                this.ErrorCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Field
        {
            get
            {
                return this.FieldField;
            }
            set
            {
                this.FieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ParticipantGroupService.ErrorSeverityCode SeverityCode
        {
            get
            {
                return this.SeverityCodeField;
            }
            set
            {
                this.SeverityCodeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseStatus", Namespace="http://schemas.datacontract.org/2004/07/Progressive.UBI.Shared.UBIServicesLib")]
    public enum ResponseStatus : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Failure = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SuccessWithWarning = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FailureWithWarning = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PartialSuccess = 5,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ParticipantGroup", Namespace="http://schemas.datacontract.org/2004/07/MyScoreBusiness.Commands.ParticipantGroup" +
        "")]
    public partial class ParticipantGroup : object
    {
        
        private System.DateTime CreateDateTimeField;
        
        private string ParticipantGroupExternalKeyField;
        
        private int ParticipantGroupSeqIDField;
        
        private int ParticipantGroupTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreateDateTime
        {
            get
            {
                return this.CreateDateTimeField;
            }
            set
            {
                this.CreateDateTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ParticipantGroupExternalKey
        {
            get
            {
                return this.ParticipantGroupExternalKeyField;
            }
            set
            {
                this.ParticipantGroupExternalKeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ParticipantGroupSeqID
        {
            get
            {
                return this.ParticipantGroupSeqIDField;
            }
            set
            {
                this.ParticipantGroupSeqIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ParticipantGroupType
        {
            get
            {
                return this.ParticipantGroupTypeField;
            }
            set
            {
                this.ParticipantGroupTypeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ErrorSeverityCode", Namespace="http://schemas.datacontract.org/2004/07/Progressive.UBI.Shared.UBIServicesLib")]
    public enum ErrorSeverityCode : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Warning = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Validation = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Exception = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Ticket = 5,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ParticipantGroupService.IParticipantGroupService")]
    public interface IParticipantGroupService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IParticipantGroupService/GetPartGroupByExtKey", ReplyAction="http://tempuri.org/IParticipantGroupService/GetPartGroupByExtKeyResponse")]
        System.Threading.Tasks.Task<ParticipantGroupService.GetPartGroupByExtKeyResponse> GetPartGroupByExtKeyAsync(ParticipantGroupService.GetPartGroupByExtKeyRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface IParticipantGroupServiceChannel : ParticipantGroupService.IParticipantGroupService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class ParticipantGroupServiceClient : System.ServiceModel.ClientBase<ParticipantGroupService.IParticipantGroupService>, ParticipantGroupService.IParticipantGroupService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ParticipantGroupServiceClient() : 
                base(ParticipantGroupServiceClient.GetDefaultBinding(), ParticipantGroupServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.WSHttpBinding_IParticipantGroupService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ParticipantGroupServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(ParticipantGroupServiceClient.GetBindingForEndpoint(endpointConfiguration), ParticipantGroupServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ParticipantGroupServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ParticipantGroupServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ParticipantGroupServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ParticipantGroupServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ParticipantGroupServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }

        public static System.ServiceModel.Channels.Binding DefaultBinding()
        {
            return GetBindingForEndpoint(EndpointConfiguration.WSHttpBinding_IParticipantGroupService);
        }

        public System.Threading.Tasks.Task<ParticipantGroupService.GetPartGroupByExtKeyResponse> GetPartGroupByExtKeyAsync(ParticipantGroupService.GetPartGroupByExtKeyRequest request)
        {
            return base.Channel.GetPartGroupByExtKeyAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WSHttpBinding_IParticipantGroupService))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WSHttpBinding_IParticipantGroupService))
            {
                return new System.ServiceModel.EndpointAddress("http://t-ubi-labs-services/MyScoreBusiness/services/ParticipantGroupService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ParticipantGroupServiceClient.GetBindingForEndpoint(EndpointConfiguration.WSHttpBinding_IParticipantGroupService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ParticipantGroupServiceClient.GetEndpointAddress(EndpointConfiguration.WSHttpBinding_IParticipantGroupService);
        }
        
        public enum EndpointConfiguration
        {
            
            WSHttpBinding_IParticipantGroupService,
        }
    }
}
