//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFMobileDeviceOrderService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UBIServiceRequest", Namespace="http://schemas.datacontract.org/2004/07/Progressive.UBI.Shared.UBIServicesLib")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WCFMobileDeviceOrderService.FulfillMobileDeviceOrderRequest))]
    public partial class UBIServiceRequest : object
    {
        
        private int VersionField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Version
        {
            get
            {
                return this.VersionField;
            }
            set
            {
                this.VersionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FulfillMobileDeviceOrderRequest", Namespace="http://schemas.datacontract.org/2004/07/MyScoreBusiness.Commands")]
    public partial class FulfillMobileDeviceOrderRequest : WCFMobileDeviceOrderService.UBIServiceRequest
    {
        
        private int DeviceOrderDetailSeqIdField;
        
        private int DeviceOrderSeqIdField;
        
        private string FulfilledByUserIdField;
        
        private WCFMobileDeviceOrderService.MobileDevice MobileDeviceField;
        
        private int ParticipantGroupSeqIdField;
        
        private int ParticipantSeqIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DeviceOrderDetailSeqId
        {
            get
            {
                return this.DeviceOrderDetailSeqIdField;
            }
            set
            {
                this.DeviceOrderDetailSeqIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DeviceOrderSeqId
        {
            get
            {
                return this.DeviceOrderSeqIdField;
            }
            set
            {
                this.DeviceOrderSeqIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FulfilledByUserId
        {
            get
            {
                return this.FulfilledByUserIdField;
            }
            set
            {
                this.FulfilledByUserIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WCFMobileDeviceOrderService.MobileDevice MobileDevice
        {
            get
            {
                return this.MobileDeviceField;
            }
            set
            {
                this.MobileDeviceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ParticipantGroupSeqId
        {
            get
            {
                return this.ParticipantGroupSeqIdField;
            }
            set
            {
                this.ParticipantGroupSeqIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ParticipantSeqId
        {
            get
            {
                return this.ParticipantSeqIdField;
            }
            set
            {
                this.ParticipantSeqIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MobileDevice", Namespace="http://schemas.datacontract.org/2004/07/MyScoreBusiness.Commands")]
    public partial class MobileDevice : object
    {
        
        private string AppVersionNameField;
        
        private string DeviceIdentifierField;
        
        private string DeviceModelNameField;
        
        private string OSNameField;
        
        private string OSVersionNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AppVersionName
        {
            get
            {
                return this.AppVersionNameField;
            }
            set
            {
                this.AppVersionNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeviceIdentifier
        {
            get
            {
                return this.DeviceIdentifierField;
            }
            set
            {
                this.DeviceIdentifierField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeviceModelName
        {
            get
            {
                return this.DeviceModelNameField;
            }
            set
            {
                this.DeviceModelNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OSName
        {
            get
            {
                return this.OSNameField;
            }
            set
            {
                this.OSNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OSVersionName
        {
            get
            {
                return this.OSVersionNameField;
            }
            set
            {
                this.OSVersionNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UBIServiceResponse", Namespace="http://schemas.datacontract.org/2004/07/Progressive.UBI.Shared.UBIServicesLib")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WCFMobileDeviceOrderService.FulfillMobileDeviceOrderResponse))]
    public partial class UBIServiceResponse : object
    {
        
        private WCFMobileDeviceOrderService.ResponseError[] ResponseErrorsField;
        
        private WCFMobileDeviceOrderService.ResponseStatus ResponseStatusField;
        
        private int VersionField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public WCFMobileDeviceOrderService.ResponseError[] ResponseErrors
        {
            get
            {
                return this.ResponseErrorsField;
            }
            set
            {
                this.ResponseErrorsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public WCFMobileDeviceOrderService.ResponseStatus ResponseStatus
        {
            get
            {
                return this.ResponseStatusField;
            }
            set
            {
                this.ResponseStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Version
        {
            get
            {
                return this.VersionField;
            }
            set
            {
                this.VersionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FulfillMobileDeviceOrderResponse", Namespace="http://schemas.datacontract.org/2004/07/MyScoreBusiness.Commands")]
    public partial class FulfillMobileDeviceOrderResponse : WCFMobileDeviceOrderService.UBIServiceResponse
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseError", Namespace="http://schemas.datacontract.org/2004/07/Progressive.UBI.Shared.UBIServicesLib")]
    public partial class ResponseError : object
    {
        
        private string ErrorCodeField;
        
        private string FieldField;
        
        private string MessageField;
        
        private WCFMobileDeviceOrderService.ErrorSeverityCode SeverityCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorCode
        {
            get
            {
                return this.ErrorCodeField;
            }
            set
            {
                this.ErrorCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Field
        {
            get
            {
                return this.FieldField;
            }
            set
            {
                this.FieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WCFMobileDeviceOrderService.ErrorSeverityCode SeverityCode
        {
            get
            {
                return this.SeverityCodeField;
            }
            set
            {
                this.SeverityCodeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseStatus", Namespace="http://schemas.datacontract.org/2004/07/Progressive.UBI.Shared.UBIServicesLib")]
    public enum ResponseStatus : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Failure = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SuccessWithWarning = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FailureWithWarning = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PartialSuccess = 5,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ErrorSeverityCode", Namespace="http://schemas.datacontract.org/2004/07/Progressive.UBI.Shared.UBIServicesLib")]
    public enum ErrorSeverityCode : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Warning = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Validation = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Exception = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Ticket = 5,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCFMobileDeviceOrderService.IMobileDeviceOrderService")]
    public interface IMobileDeviceOrderService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMobileDeviceOrderService/Fulfill", ReplyAction="http://tempuri.org/IMobileDeviceOrderService/FulfillResponse")]
        System.Threading.Tasks.Task<WCFMobileDeviceOrderService.FulfillMobileDeviceOrderResponse> FulfillAsync(WCFMobileDeviceOrderService.FulfillMobileDeviceOrderRequest fulfillMobileDeviceOrderRequest);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface IMobileDeviceOrderServiceChannel : WCFMobileDeviceOrderService.IMobileDeviceOrderService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class MobileDeviceOrderServiceClient : System.ServiceModel.ClientBase<WCFMobileDeviceOrderService.IMobileDeviceOrderService>, WCFMobileDeviceOrderService.IMobileDeviceOrderService
    {
        
        public MobileDeviceOrderServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<WCFMobileDeviceOrderService.FulfillMobileDeviceOrderResponse> FulfillAsync(WCFMobileDeviceOrderService.FulfillMobileDeviceOrderRequest fulfillMobileDeviceOrderRequest)
        {
            return base.Channel.FulfillAsync(fulfillMobileDeviceOrderRequest);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
    }
}
