//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfDeviceLotService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UBIServiceRequest", Namespace="http://schemas.datacontract.org/2004/07/Progressive.UBI.Shared.UBIServicesLib")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WcfDeviceLotService.AddManufacturerLotRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WcfDeviceLotService.DeleteDeviceLotRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WcfDeviceLotService.GetDeviceLotRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WcfDeviceLotService.UpdateDeviceLotRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WcfDeviceLotService.ReceiveLotRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WcfDeviceLotService.GetDeviceLotByNameRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WcfDeviceLotService.GetDeviceLotsByTypeAndStatusRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WcfDeviceLotService.CloseDeviceLotRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WcfDeviceLotService.GetRMADeviceLotsByStatusAndDeviceProductRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WcfDeviceLotService.AddDeviceLotRequest))]
    public partial class UBIServiceRequest : object
    {
        
        private int VersionField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Version
        {
            get
            {
                return this.VersionField;
            }
            set
            {
                this.VersionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddManufacturerLotRequest", Namespace="http://schemas.datacontract.org/2004/07/HomeBaseServices.Xirgo")]
    public partial class AddManufacturerLotRequest : WcfDeviceLotService.UBIServiceRequest
    {
        
        private int DefaultFirmwareCodeField;
        
        private WcfDeviceLotService.DeviceFromMfg[] DevicesField;
        
        private string NameField;
        
        private int VersionCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int DefaultFirmwareCode
        {
            get
            {
                return this.DefaultFirmwareCodeField;
            }
            set
            {
                this.DefaultFirmwareCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public WcfDeviceLotService.DeviceFromMfg[] Devices
        {
            get
            {
                return this.DevicesField;
            }
            set
            {
                this.DevicesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int VersionCode
        {
            get
            {
                return this.VersionCodeField;
            }
            set
            {
                this.VersionCodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeleteDeviceLotRequest", Namespace="http://schemas.datacontract.org/2004/07/HomeBaseServices.Xirgo")]
    public partial class DeleteDeviceLotRequest : WcfDeviceLotService.UBIServiceRequest
    {
        
        private int LotSeqIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LotSeqID
        {
            get
            {
                return this.LotSeqIDField;
            }
            set
            {
                this.LotSeqIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetDeviceLotRequest", Namespace="http://schemas.datacontract.org/2004/07/HomeBaseServices.Xirgo")]
    public partial class GetDeviceLotRequest : WcfDeviceLotService.UBIServiceRequest
    {
        
        private int LotSeqIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int LotSeqID
        {
            get
            {
                return this.LotSeqIDField;
            }
            set
            {
                this.LotSeqIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdateDeviceLotRequest", Namespace="http://schemas.datacontract.org/2004/07/HomeBaseServices.Xirgo")]
    public partial class UpdateDeviceLotRequest : WcfDeviceLotService.UBIServiceRequest
    {
        
        private WcfDeviceLotService.DeviceLot DeviceLotField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public WcfDeviceLotService.DeviceLot DeviceLot
        {
            get
            {
                return this.DeviceLotField;
            }
            set
            {
                this.DeviceLotField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReceiveLotRequest", Namespace="http://schemas.datacontract.org/2004/07/HomeBaseServices.Xirgo")]
    public partial class ReceiveLotRequest : WcfDeviceLotService.UBIServiceRequest
    {
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetDeviceLotByNameRequest", Namespace="http://schemas.datacontract.org/2004/07/HomeBaseServices.Xirgo")]
    public partial class GetDeviceLotByNameRequest : WcfDeviceLotService.UBIServiceRequest
    {
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetDeviceLotsByTypeAndStatusRequest", Namespace="http://schemas.datacontract.org/2004/07/HomeBaseServices.Xirgo")]
    public partial class GetDeviceLotsByTypeAndStatusRequest : WcfDeviceLotService.UBIServiceRequest
    {
        
        private int StatusCodeField;
        
        private int TypeCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int StatusCode
        {
            get
            {
                return this.StatusCodeField;
            }
            set
            {
                this.StatusCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int TypeCode
        {
            get
            {
                return this.TypeCodeField;
            }
            set
            {
                this.TypeCodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CloseDeviceLotRequest", Namespace="http://schemas.datacontract.org/2004/07/HomeBaseServices.Xirgo")]
    public partial class CloseDeviceLotRequest : WcfDeviceLotService.UBIServiceRequest
    {
        
        private int LotSequenceIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int LotSequenceID
        {
            get
            {
                return this.LotSequenceIDField;
            }
            set
            {
                this.LotSequenceIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetRMADeviceLotsByStatusAndDeviceProductRequest", Namespace="http://schemas.datacontract.org/2004/07/HomeBaseServices.Xirgo")]
    public partial class GetRMADeviceLotsByStatusAndDeviceProductRequest : WcfDeviceLotService.UBIServiceRequest
    {
        
        private int StatusCodeField;
        
        private int VersionCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int StatusCode
        {
            get
            {
                return this.StatusCodeField;
            }
            set
            {
                this.StatusCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int VersionCode
        {
            get
            {
                return this.VersionCodeField;
            }
            set
            {
                this.VersionCodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddDeviceLotRequest", Namespace="http://schemas.datacontract.org/2004/07/HomeBaseServices.Xirgo")]
    public partial class AddDeviceLotRequest : WcfDeviceLotService.UBIServiceRequest
    {
        
        private string NameField;
        
        private byte StatusCodeField;
        
        private byte TypeCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte StatusCode
        {
            get
            {
                return this.StatusCodeField;
            }
            set
            {
                this.StatusCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte TypeCode
        {
            get
            {
                return this.TypeCodeField;
            }
            set
            {
                this.TypeCodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeviceFromMfg", Namespace="http://schemas.datacontract.org/2004/07/HomeBaseServices.Xirgo")]
    public partial class DeviceFromMfg : object
    {
        
        private string IMEIField;
        
        private string SIMField;
        
        private string SerialNumberField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IMEI
        {
            get
            {
                return this.IMEIField;
            }
            set
            {
                this.IMEIField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SIM
        {
            get
            {
                return this.SIMField;
            }
            set
            {
                this.SIMField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SerialNumber
        {
            get
            {
                return this.SerialNumberField;
            }
            set
            {
                this.SerialNumberField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeviceLot", Namespace="http://schemas.datacontract.org/2004/07/HomeBaseServices.Xirgo")]
    public partial class DeviceLot : object
    {
        
        private System.Nullable<System.DateTime> CreateDateTimeField;
        
        private System.Nullable<int> LotSeqIDField;
        
        private string NameField;
        
        private System.Nullable<int> StatusCodeField;
        
        private System.Nullable<int> TypeCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CreateDateTime
        {
            get
            {
                return this.CreateDateTimeField;
            }
            set
            {
                this.CreateDateTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> LotSeqID
        {
            get
            {
                return this.LotSeqIDField;
            }
            set
            {
                this.LotSeqIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> StatusCode
        {
            get
            {
                return this.StatusCodeField;
            }
            set
            {
                this.StatusCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TypeCode
        {
            get
            {
                return this.TypeCodeField;
            }
            set
            {
                this.TypeCodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UBIServiceResponse", Namespace="http://schemas.datacontract.org/2004/07/Progressive.UBI.Shared.UBIServicesLib")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WcfDeviceLotService.AddManufacturerLotResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WcfDeviceLotService.DeleteDeviceLotResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WcfDeviceLotService.GetDeviceLotResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WcfDeviceLotService.UpdateDeviceLotResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WcfDeviceLotService.GetReceiveDeviceLotsInProcessResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WcfDeviceLotService.ReceiveLotResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WcfDeviceLotService.GetDeviceLotByNameResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WcfDeviceLotService.GetDeviceLotsByTypeAndStatusResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WcfDeviceLotService.CloseDeviceLotResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WcfDeviceLotService.GetRMADeviceLotsByStatusAndDeviceProductResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WcfDeviceLotService.AddDeviceLotResponse))]
    public partial class UBIServiceResponse : object
    {
        
        private WcfDeviceLotService.ResponseError[] ResponseErrorsField;
        
        private WcfDeviceLotService.ResponseStatus ResponseStatusField;
        
        private int VersionField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public WcfDeviceLotService.ResponseError[] ResponseErrors
        {
            get
            {
                return this.ResponseErrorsField;
            }
            set
            {
                this.ResponseErrorsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public WcfDeviceLotService.ResponseStatus ResponseStatus
        {
            get
            {
                return this.ResponseStatusField;
            }
            set
            {
                this.ResponseStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Version
        {
            get
            {
                return this.VersionField;
            }
            set
            {
                this.VersionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddManufacturerLotResponse", Namespace="http://schemas.datacontract.org/2004/07/HomeBaseServices.Xirgo")]
    public partial class AddManufacturerLotResponse : WcfDeviceLotService.UBIServiceResponse
    {
        
        private int DevicesAddedField;
        
        private int DevicesAlreadyInDBField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int DevicesAdded
        {
            get
            {
                return this.DevicesAddedField;
            }
            set
            {
                this.DevicesAddedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int DevicesAlreadyInDB
        {
            get
            {
                return this.DevicesAlreadyInDBField;
            }
            set
            {
                this.DevicesAlreadyInDBField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeleteDeviceLotResponse", Namespace="http://schemas.datacontract.org/2004/07/HomeBaseServices.Xirgo")]
    public partial class DeleteDeviceLotResponse : WcfDeviceLotService.UBIServiceResponse
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetDeviceLotResponse", Namespace="http://schemas.datacontract.org/2004/07/HomeBaseServices.Xirgo")]
    public partial class GetDeviceLotResponse : WcfDeviceLotService.UBIServiceResponse
    {
        
        private WcfDeviceLotService.DeviceLot DeviceLotField;
        
        private int RecordCountField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public WcfDeviceLotService.DeviceLot DeviceLot
        {
            get
            {
                return this.DeviceLotField;
            }
            set
            {
                this.DeviceLotField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int RecordCount
        {
            get
            {
                return this.RecordCountField;
            }
            set
            {
                this.RecordCountField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdateDeviceLotResponse", Namespace="http://schemas.datacontract.org/2004/07/HomeBaseServices.Xirgo")]
    public partial class UpdateDeviceLotResponse : WcfDeviceLotService.UBIServiceResponse
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetReceiveDeviceLotsInProcessResponse", Namespace="http://schemas.datacontract.org/2004/07/HomeBaseServices.Xirgo")]
    public partial class GetReceiveDeviceLotsInProcessResponse : WcfDeviceLotService.UBIServiceResponse
    {
        
        private WcfDeviceLotService.DeviceLot[] DeviceLotsField;
        
        private int resultCountField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public WcfDeviceLotService.DeviceLot[] DeviceLots
        {
            get
            {
                return this.DeviceLotsField;
            }
            set
            {
                this.DeviceLotsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int resultCount
        {
            get
            {
                return this.resultCountField;
            }
            set
            {
                this.resultCountField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReceiveLotResponse", Namespace="http://schemas.datacontract.org/2004/07/HomeBaseServices.Xirgo")]
    public partial class ReceiveLotResponse : WcfDeviceLotService.UBIServiceResponse
    {
        
        private int TotalDevicesUpdatedField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int TotalDevicesUpdated
        {
            get
            {
                return this.TotalDevicesUpdatedField;
            }
            set
            {
                this.TotalDevicesUpdatedField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetDeviceLotByNameResponse", Namespace="http://schemas.datacontract.org/2004/07/HomeBaseServices.Xirgo")]
    public partial class GetDeviceLotByNameResponse : WcfDeviceLotService.UBIServiceResponse
    {
        
        private WcfDeviceLotService.DeviceLot DeviceLotField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public WcfDeviceLotService.DeviceLot DeviceLot
        {
            get
            {
                return this.DeviceLotField;
            }
            set
            {
                this.DeviceLotField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetDeviceLotsByTypeAndStatusResponse", Namespace="http://schemas.datacontract.org/2004/07/HomeBaseServices.Xirgo")]
    public partial class GetDeviceLotsByTypeAndStatusResponse : WcfDeviceLotService.UBIServiceResponse
    {
        
        private WcfDeviceLotService.DeviceLot[] DeviceLotsField;
        
        private int resultCountField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public WcfDeviceLotService.DeviceLot[] DeviceLots
        {
            get
            {
                return this.DeviceLotsField;
            }
            set
            {
                this.DeviceLotsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int resultCount
        {
            get
            {
                return this.resultCountField;
            }
            set
            {
                this.resultCountField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CloseDeviceLotResponse", Namespace="http://schemas.datacontract.org/2004/07/HomeBaseServices.Xirgo")]
    public partial class CloseDeviceLotResponse : WcfDeviceLotService.UBIServiceResponse
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetRMADeviceLotsByStatusAndDeviceProductResponse", Namespace="http://schemas.datacontract.org/2004/07/HomeBaseServices.Xirgo")]
    public partial class GetRMADeviceLotsByStatusAndDeviceProductResponse : WcfDeviceLotService.UBIServiceResponse
    {
        
        private WcfDeviceLotService.DeviceLot[] DeviceLotsField;
        
        private int resultCountField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public WcfDeviceLotService.DeviceLot[] DeviceLots
        {
            get
            {
                return this.DeviceLotsField;
            }
            set
            {
                this.DeviceLotsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int resultCount
        {
            get
            {
                return this.resultCountField;
            }
            set
            {
                this.resultCountField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddDeviceLotResponse", Namespace="http://schemas.datacontract.org/2004/07/HomeBaseServices.Xirgo")]
    public partial class AddDeviceLotResponse : WcfDeviceLotService.UBIServiceResponse
    {
        
        private int LotSeqIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int LotSeqID
        {
            get
            {
                return this.LotSeqIDField;
            }
            set
            {
                this.LotSeqIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseError", Namespace="http://schemas.datacontract.org/2004/07/Progressive.UBI.Shared.UBIServicesLib")]
    public partial class ResponseError : object
    {
        
        private string ErrorCodeField;
        
        private string FieldField;
        
        private string MessageField;
        
        private WcfDeviceLotService.ErrorSeverityCode SeverityCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorCode
        {
            get
            {
                return this.ErrorCodeField;
            }
            set
            {
                this.ErrorCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Field
        {
            get
            {
                return this.FieldField;
            }
            set
            {
                this.FieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WcfDeviceLotService.ErrorSeverityCode SeverityCode
        {
            get
            {
                return this.SeverityCodeField;
            }
            set
            {
                this.SeverityCodeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseStatus", Namespace="http://schemas.datacontract.org/2004/07/Progressive.UBI.Shared.UBIServicesLib")]
    public enum ResponseStatus : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Failure = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SuccessWithWarning = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FailureWithWarning = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PartialSuccess = 5,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ErrorSeverityCode", Namespace="http://schemas.datacontract.org/2004/07/Progressive.UBI.Shared.UBIServicesLib")]
    public enum ErrorSeverityCode : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Warning = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Validation = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Exception = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Ticket = 5,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WcfDeviceLotService.IDeviceLotService")]
    public interface IDeviceLotService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeviceLotService/Add", ReplyAction="http://tempuri.org/IDeviceLotService/AddResponse")]
        System.Threading.Tasks.Task<WcfDeviceLotService.AddDeviceLotResponse> AddAsync(WcfDeviceLotService.AddDeviceLotRequest addDeviceLotRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeviceLotService/AddManufacturerLot", ReplyAction="http://tempuri.org/IDeviceLotService/AddManufacturerLotResponse")]
        System.Threading.Tasks.Task<WcfDeviceLotService.AddManufacturerLotResponse> AddManufacturerLotAsync(WcfDeviceLotService.AddManufacturerLotRequest addManufacturerLotRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeviceLotService/Delete", ReplyAction="http://tempuri.org/IDeviceLotService/DeleteResponse")]
        System.Threading.Tasks.Task<WcfDeviceLotService.DeleteDeviceLotResponse> DeleteAsync(WcfDeviceLotService.DeleteDeviceLotRequest deleteDeviceLotRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeviceLotService/Get", ReplyAction="http://tempuri.org/IDeviceLotService/GetResponse")]
        System.Threading.Tasks.Task<WcfDeviceLotService.GetDeviceLotResponse> GetAsync(WcfDeviceLotService.GetDeviceLotRequest getDeviceLotRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeviceLotService/Update", ReplyAction="http://tempuri.org/IDeviceLotService/UpdateResponse")]
        System.Threading.Tasks.Task<WcfDeviceLotService.UpdateDeviceLotResponse> UpdateAsync(WcfDeviceLotService.UpdateDeviceLotRequest updateDeviceLotRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeviceLotService/GetReceiveDeviceLotsInProcess", ReplyAction="http://tempuri.org/IDeviceLotService/GetReceiveDeviceLotsInProcessResponse")]
        System.Threading.Tasks.Task<WcfDeviceLotService.GetReceiveDeviceLotsInProcessResponse> GetReceiveDeviceLotsInProcessAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeviceLotService/ReceiveLot", ReplyAction="http://tempuri.org/IDeviceLotService/ReceiveLotResponse")]
        System.Threading.Tasks.Task<WcfDeviceLotService.ReceiveLotResponse> ReceiveLotAsync(WcfDeviceLotService.ReceiveLotRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeviceLotService/GetDeviceLotByName", ReplyAction="http://tempuri.org/IDeviceLotService/GetDeviceLotByNameResponse")]
        System.Threading.Tasks.Task<WcfDeviceLotService.GetDeviceLotByNameResponse> GetDeviceLotByNameAsync(WcfDeviceLotService.GetDeviceLotByNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeviceLotService/GetDeviceLotsByTypeAndStatus", ReplyAction="http://tempuri.org/IDeviceLotService/GetDeviceLotsByTypeAndStatusResponse")]
        System.Threading.Tasks.Task<WcfDeviceLotService.GetDeviceLotsByTypeAndStatusResponse> GetDeviceLotsByTypeAndStatusAsync(WcfDeviceLotService.GetDeviceLotsByTypeAndStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeviceLotService/CloseDeviceLot", ReplyAction="http://tempuri.org/IDeviceLotService/CloseDeviceLotResponse")]
        System.Threading.Tasks.Task<WcfDeviceLotService.CloseDeviceLotResponse> CloseDeviceLotAsync(WcfDeviceLotService.CloseDeviceLotRequest closeDeviceLotRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeviceLotService/GetRMADeviceLotsByStatusAndDeviceProduct", ReplyAction="http://tempuri.org/IDeviceLotService/GetRMADeviceLotsByStatusAndDeviceProductResp" +
            "onse")]
        System.Threading.Tasks.Task<WcfDeviceLotService.GetRMADeviceLotsByStatusAndDeviceProductResponse> GetRMADeviceLotsByStatusAndDeviceProductAsync(WcfDeviceLotService.GetRMADeviceLotsByStatusAndDeviceProductRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface IDeviceLotServiceChannel : WcfDeviceLotService.IDeviceLotService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class DeviceLotServiceClient : System.ServiceModel.ClientBase<WcfDeviceLotService.IDeviceLotService>, WcfDeviceLotService.IDeviceLotService
    {
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);

        public DeviceLotServiceClient() :
                base(DeviceLotServiceClient.GetDefaultBinding(), DeviceLotServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.WSHttpBinding_IDeviceLotService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public DeviceLotServiceClient(EndpointConfiguration endpointConfiguration) :
                base(DeviceLotServiceClient.GetBindingForEndpoint(endpointConfiguration), DeviceLotServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public DeviceLotServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) :
                base(DeviceLotServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public DeviceLotServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) :
                base(DeviceLotServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public DeviceLotServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
                base(binding, remoteAddress)
        {
        }

        public System.Threading.Tasks.Task<WcfDeviceLotService.AddDeviceLotResponse> AddAsync(WcfDeviceLotService.AddDeviceLotRequest addDeviceLotRequest)
        {
            return base.Channel.AddAsync(addDeviceLotRequest);
        }
        
        public System.Threading.Tasks.Task<WcfDeviceLotService.AddManufacturerLotResponse> AddManufacturerLotAsync(WcfDeviceLotService.AddManufacturerLotRequest addManufacturerLotRequest)
        {
            return base.Channel.AddManufacturerLotAsync(addManufacturerLotRequest);
        }
        
        public System.Threading.Tasks.Task<WcfDeviceLotService.DeleteDeviceLotResponse> DeleteAsync(WcfDeviceLotService.DeleteDeviceLotRequest deleteDeviceLotRequest)
        {
            return base.Channel.DeleteAsync(deleteDeviceLotRequest);
        }
        
        public System.Threading.Tasks.Task<WcfDeviceLotService.GetDeviceLotResponse> GetAsync(WcfDeviceLotService.GetDeviceLotRequest getDeviceLotRequest)
        {
            return base.Channel.GetAsync(getDeviceLotRequest);
        }
        
        public System.Threading.Tasks.Task<WcfDeviceLotService.UpdateDeviceLotResponse> UpdateAsync(WcfDeviceLotService.UpdateDeviceLotRequest updateDeviceLotRequest)
        {
            return base.Channel.UpdateAsync(updateDeviceLotRequest);
        }
        
        public System.Threading.Tasks.Task<WcfDeviceLotService.GetReceiveDeviceLotsInProcessResponse> GetReceiveDeviceLotsInProcessAsync()
        {
            return base.Channel.GetReceiveDeviceLotsInProcessAsync();
        }
        
        public System.Threading.Tasks.Task<WcfDeviceLotService.ReceiveLotResponse> ReceiveLotAsync(WcfDeviceLotService.ReceiveLotRequest request)
        {
            return base.Channel.ReceiveLotAsync(request);
        }
        
        public System.Threading.Tasks.Task<WcfDeviceLotService.GetDeviceLotByNameResponse> GetDeviceLotByNameAsync(WcfDeviceLotService.GetDeviceLotByNameRequest request)
        {
            return base.Channel.GetDeviceLotByNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<WcfDeviceLotService.GetDeviceLotsByTypeAndStatusResponse> GetDeviceLotsByTypeAndStatusAsync(WcfDeviceLotService.GetDeviceLotsByTypeAndStatusRequest request)
        {
            return base.Channel.GetDeviceLotsByTypeAndStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<WcfDeviceLotService.CloseDeviceLotResponse> CloseDeviceLotAsync(WcfDeviceLotService.CloseDeviceLotRequest closeDeviceLotRequest)
        {
            return base.Channel.CloseDeviceLotAsync(closeDeviceLotRequest);
        }
        
        public System.Threading.Tasks.Task<WcfDeviceLotService.GetRMADeviceLotsByStatusAndDeviceProductResponse> GetRMADeviceLotsByStatusAndDeviceProductAsync(WcfDeviceLotService.GetRMADeviceLotsByStatusAndDeviceProductRequest request)
        {
            return base.Channel.GetRMADeviceLotsByStatusAndDeviceProductAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }

        public static System.ServiceModel.Channels.Binding DefaultBinding()
        {
            return GetBindingForEndpoint(EndpointConfiguration.WSHttpBinding_IDeviceLotService);
        }

        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WSHttpBinding_IDeviceLotService))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }

        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WSHttpBinding_IDeviceLotService))
            {
                return new System.ServiceModel.EndpointAddress(new System.Uri("http://t-ubi-homebase-services/HomeBaseServices/Services/Xirgo/DeviceLotService.s" +
                            "vc"), new System.ServiceModel.DnsEndpointIdentity("localhost"));
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }

        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return DeviceLotServiceClient.GetBindingForEndpoint(EndpointConfiguration.WSHttpBinding_IDeviceLotService);
        }

        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return DeviceLotServiceClient.GetEndpointAddress(EndpointConfiguration.WSHttpBinding_IDeviceLotService);
        }

        public enum EndpointConfiguration
        {

            WSHttpBinding_IDeviceLotService,
        }
    }
}
