// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using Progressive.Telematics.Admin.Services.Database;
using Progressive.Telematics.Admin.Shared.Configs;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading.Tasks;

namespace Progressive.Telematics.Admin.Services.Models.ClTables
;
    public partial class CLContext : Microsoft.EntityFrameworkCore.DbContext
    {
        public IOptions<ConnectionStringsConfig> config { get; }
        public IOptions<EnvironmentPrefixes> envConfig { get; }

        public CLContext(DbContextOptions<CLContext> options)
            : base(options)
        {
        
        }

        public virtual DbSet<BadTrip> BadTrips { get; set; }
        public virtual DbSet<BadTripReason> BadTripReasons { get; set; }
        public virtual DbSet<ConfigValue> ConfigValues { get; set; }
        public virtual DbSet<DeviceEvent> DeviceEvents { get; set; }
        public virtual DbSet<DeviceEventType> DeviceEventTypes { get; set; }
        public virtual DbSet<DeviceExperienceType> DeviceExperienceTypes { get; set; }
        public virtual DbSet<DeviceOrder> DeviceOrders { get; set; }
        public virtual DbSet<DeviceOrderDetail> DeviceOrderDetails { get; set; }
        public virtual DbSet<DeviceOrderStatus> DeviceOrderStatuses { get; set; }
        public virtual DbSet<DeviceReturn> DeviceReturns { get; set; }
        public virtual DbSet<DeviceReturnReason> DeviceReturnReasons { get; set; }
        public virtual DbSet<ExcludedDateRange> ExcludedDateRanges { get; set; }
        public virtual DbSet<Participant> Participants { get; set; }
        public virtual DbSet<ParticipantHistory> ParticipantHistories { get; set; }
        public virtual DbSet<ParticipantStatus> ParticipantStatuses { get; set; }
        public virtual DbSet<Policy> Policies { get; set; }
        public virtual DbSet<SummarizationMethod> SummarizationMethods { get; set; }
        public virtual DbSet<Trip> Trips { get; set; }
        public virtual DbSet<TripDetailSmoothingAudit> TripDetailSmoothingAudits { get; set; }
        public virtual DbSet<TripDetailSmoothingAuditType> TripDetailSmoothingAuditTypes { get; set; }
        public virtual DbSet<TripEvent> TripEvents { get; set; }
        public virtual DbSet<TripEventType> TripEventTypes { get; set; }
        public virtual DbSet<UnreasonableTrip> UnreasonableTrips { get; set; }
        public virtual DbSet<UnreasonableTripEvent> UnreasonableTripEvents { get; set; }
        public virtual DbSet<UnreasonableTripEventCode> UnreasonableTripEventCodes { get; set; }
        public virtual DbSet<Vehicle> Vehicles { get; set; }
        public virtual DbSet<VehicleProtocol> VehicleProtocols { get; set; }


        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<BadTrip>(entity =>
            {
                entity.HasKey(e => e.BadTripSeqId);

                entity.ToTable("BadTrip", "dbo");

                entity.HasIndex(e => e.CreateDateTime, "IX_BadTrip_CreateDateTime")
                    .HasFillFactor(90);

                entity.HasIndex(e => new { e.ParticipantSeqId, e.TripStartDateTime }, "IX_BadTrip_ParticipantSeqID_TripStartDateTime")
                    .IsUnique();

                entity.Property(e => e.BadTripSeqId).HasColumnName("BadTripSeqID");

                entity.Property(e => e.CreateDateTime)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.DeviceSeqId).HasColumnName("DeviceSeqID");

                entity.Property(e => e.MaxSpeedKph).HasColumnName("MaxSpeedKPH");

                entity.Property(e => e.ParticipantSeqId).HasColumnName("ParticipantSeqID");

                entity.Property(e => e.TripEndDateTime).HasColumnType("datetime");

                entity.Property(e => e.TripStartDateTime).HasColumnType("datetime");

                entity.Property(e => e.VehicleSeqId).HasColumnName("VehicleSeqID");

                entity.HasOne(d => d.BadTripReasonCodeNavigation)
                    .WithMany(p => p.BadTrips)
                    .HasForeignKey(d => d.BadTripReasonCode)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_BadTrip_BadTripReason");

                entity.HasOne(d => d.ParticipantSeq)
                    .WithMany(p => p.BadTrips)
                    .HasForeignKey(d => d.ParticipantSeqId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_BadTrip_Participant");

                entity.HasOne(d => d.VehicleSeq)
                    .WithMany(p => p.BadTrips)
                    .HasForeignKey(d => d.VehicleSeqId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_BadTrip_Vehicle");
            });

            modelBuilder.Entity<BadTripReason>(entity =>
            {
                entity.HasKey(e => e.Code);

                entity.ToTable("BadTripReason", "dbo");

                entity.HasIndex(e => e.Description, "IX_BadTripReason_Description")
                    .IsUnique();

                entity.Property(e => e.Code).ValueGeneratedNever();

                entity.Property(e => e.CreateDateTime)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.Description)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<ConfigValue>(entity =>
            {
                entity.HasKey(e => e.ConfigValueKey);

                entity.ToTable("ConfigValues", "dbo");

                entity.Property(e => e.ConfigValueKey)
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.ConfigValue1)
                    .IsRequired()
                    .HasMaxLength(255)
                    .IsUnicode(false)
                    .HasColumnName("ConfigValue");

                entity.Property(e => e.ConfigValueCastDataType)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<DeviceEvent>(entity =>
            {
                entity.HasKey(e => e.DeviceEventSeqId);

                entity.ToTable("DeviceEvent", "dbo");

                entity.Property(e => e.DeviceEventSeqId).HasColumnName("DeviceEventSeqID");

                entity.Property(e => e.CreateDateTime)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.DeviceEventDateTime).HasColumnType("datetime");

                entity.Property(e => e.DeviceSeqId).HasColumnName("DeviceSeqID");

                entity.Property(e => e.ParticipantSeqId).HasColumnName("ParticipantSeqID");

                entity.Property(e => e.ReportedVin)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("ReportedVIN");

                entity.HasOne(d => d.DeviceEventTypeCodeNavigation)
                    .WithMany(p => p.DeviceEvents)
                    .HasForeignKey(d => d.DeviceEventTypeCode)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_DeviceEvent_DeviceEventType");

                entity.HasOne(d => d.ParticipantSeq)
                    .WithMany(p => p.DeviceEvents)
                    .HasForeignKey(d => d.ParticipantSeqId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_DeviceEvent_Participant");

                entity.HasOne(d => d.VehicleProtocolCodeNavigation)
                    .WithMany(p => p.DeviceEvents)
                    .HasForeignKey(d => d.VehicleProtocolCode)
                    .HasConstraintName("FK_DeviceEvent_VehicleProtocol");
            });

            modelBuilder.Entity<DeviceEventType>(entity =>
            {
                entity.HasKey(e => e.Code);

                entity.ToTable("DeviceEventType", "dbo");

                entity.HasIndex(e => e.Description, "IX_DeviceEventType_Description")
                    .IsUnique();

                entity.Property(e => e.Code).ValueGeneratedNever();

                entity.Property(e => e.CreateDateTime)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.Description)
                    .IsRequired()
                    .HasMaxLength(255)
                    .IsUnicode(false);

                entity.Property(e => e.IsActive)
                    .IsRequired()
                    .HasDefaultValueSql("((1))");
            });

            modelBuilder.Entity<DeviceExperienceType>(entity =>
            {
                entity.HasKey(e => e.Code);

                entity.ToTable("DeviceExperienceType", "dbo");

                entity.HasIndex(e => e.Description, "IX_Description")
                    .IsUnique();

                entity.Property(e => e.Code).ValueGeneratedNever();

                entity.Property(e => e.CreateDateTime)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.Description)
                    .IsRequired()
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.LastChangeDateTime)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.LastChangeUserId)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<DeviceOrder>(entity =>
            {
                entity.HasKey(e => e.DeviceOrderSeqId);

                entity.ToTable("DeviceOrder", "dbo");

                entity.Property(e => e.DeviceOrderSeqId).HasColumnName("DeviceOrderSeqID");

                entity.Property(e => e.CreateDateTime)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.FulfilledByUserId)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("FulfilledByUserID");

                entity.Property(e => e.PolicySeqId).HasColumnName("PolicySeqID");

                entity.Property(e => e.ProcessedDateTime).HasColumnType("datetime");

                entity.Property(e => e.ShipDateTime).HasColumnType("datetime");

                entity.HasOne(d => d.DeviceOrderStatusCodeNavigation)
                    .WithMany(p => p.DeviceOrders)
                    .HasForeignKey(d => d.DeviceOrderStatusCode)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_DeviceOrder_DeviceOrderStatusCode");

                entity.HasOne(d => d.PolicySeq)
                    .WithMany(p => p.DeviceOrders)
                    .HasForeignKey(d => d.PolicySeqId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_DeviceOrder_Policy");
            });

            modelBuilder.Entity<DeviceOrderDetail>(entity =>
            {
                entity.HasKey(e => e.DeviceOrderDetailSeqId);

                entity.ToTable("DeviceOrderDetail", "dbo");

                entity.HasIndex(e => new { e.DeviceOrderSeqId, e.ParticipantSeqId }, "IX_DeviceOrderDetail_DeviceOrderSeqID_ParticipantSeqID")
                    .IsUnique()
                    .HasFillFactor(90);

                entity.Property(e => e.DeviceOrderDetailSeqId).HasColumnName("DeviceOrderDetailSeqID");

                entity.Property(e => e.CreateDateTime)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.DeviceOrderSeqId).HasColumnName("DeviceOrderSeqID");

                entity.Property(e => e.DeviceSeqId).HasColumnName("DeviceSeqID");

                entity.Property(e => e.ParticipantSeqId).HasColumnName("ParticipantSeqID");

                entity.Property(e => e.VehicleSeqId).HasColumnName("VehicleSeqID");
            });

            modelBuilder.Entity<DeviceOrderStatus>(entity =>
            {
                entity.HasKey(e => e.Code);

                entity.ToTable("DeviceOrderStatus", "dbo");

                entity.HasIndex(e => e.Description, "IX_DeviceOrderStatus_Description")
                    .IsUnique();

                entity.Property(e => e.Code).ValueGeneratedNever();

                entity.Property(e => e.CreateDateTime)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.Description)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<DeviceReturn>(entity =>
            {
                entity.HasKey(e => new { e.DeviceSeqId, e.ParticipantSeqId })
                    .IsClustered(false);

                entity.ToTable("DeviceReturn", "dbo");

                entity.HasIndex(e => new { e.DeviceSeqId, e.ParticipantSeqId }, "IX_DeviceReturn_Device_Participant")
                    .IsUnique()
                    .IsClustered()
                    .HasFillFactor(90);

                entity.Property(e => e.DeviceSeqId).HasColumnName("DeviceSeqID");

                entity.Property(e => e.ParticipantSeqId).HasColumnName("ParticipantSeqID");

                entity.Property(e => e.CreateDateTime)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.DeviceAbandonedDateTime).HasColumnType("datetime");

                entity.Property(e => e.DeviceReceivedDateTime).HasColumnType("datetime");

                entity.Property(e => e.VehicleSeqId).HasColumnName("VehicleSeqID");

                entity.HasOne(d => d.DeviceReturnReasonCodeNavigation)
                    .WithMany(p => p.DeviceReturns)
                    .HasForeignKey(d => d.DeviceReturnReasonCode)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_DeviceReturn_DeviceReturnReason");

                entity.HasOne(d => d.ParticipantSeq)
                    .WithMany(p => p.DeviceReturns)
                    .HasForeignKey(d => d.ParticipantSeqId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_DeviceReturn_Participant");

                entity.HasOne(d => d.VehicleSeq)
                    .WithMany(p => p.DeviceReturns)
                    .HasForeignKey(d => d.VehicleSeqId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_DeviceReturn_Vehicle");
            });

            modelBuilder.Entity<DeviceReturnReason>(entity =>
            {
                entity.HasKey(e => e.Code);

                entity.ToTable("DeviceReturnReason", "dbo");

                entity.HasIndex(e => e.Description, "IX_DeviceReturnReason_Description")
                    .IsUnique()
                    .HasFillFactor(90);

                entity.Property(e => e.Code).ValueGeneratedNever();

                entity.Property(e => e.CreateDateTime)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.Description)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<ExcludedDateRange>(entity =>
            {
                entity.HasKey(e => new { e.ParticipantSeqId, e.RangeStart });

                entity.ToTable("ExcludedDateRange", "dbo");

                entity.Property(e => e.ParticipantSeqId).HasColumnName("ParticipantSeqID");

                entity.Property(e => e.RangeStart).HasColumnType("datetime");

                entity.Property(e => e.CreateDate)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.Description)
                    .HasMaxLength(250)
                    .IsUnicode(false);

                entity.Property(e => e.RangeEnd).HasColumnType("datetime");

                entity.HasOne(d => d.ParticipantSeq)
                    .WithMany(p => p.ExcludedDateRanges)
                    .HasForeignKey(d => d.ParticipantSeqId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_ExcludedDateRange_Participant");
            });

            modelBuilder.Entity<Participant>(entity =>
            {
                entity.HasKey(e => e.ParticipantSeqId);

                entity.ToTable("Participant", "dbo");

                entity.HasIndex(e => e.ParticipantId, "IX_Participant_ParticipantID")
                    .IsUnique();

                entity.HasIndex(e => e.PolicySeqId, "IX_Participant_Policy");

                entity.Property(e => e.ParticipantSeqId).HasColumnName("ParticipantSeqID");

                entity.Property(e => e.CreateDateTime)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.DashboardEnrollmentDateTime).HasColumnType("datetime");

                entity.Property(e => e.DeviceSeqId).HasColumnName("DeviceSeqID");

                entity.Property(e => e.LastUpdateDateTime).HasColumnType("datetime");

                entity.Property(e => e.ParticipantId)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("ParticipantID");

                entity.Property(e => e.PolicySeqId).HasColumnName("PolicySeqID");

                entity.Property(e => e.VehicleSeqId).HasColumnName("VehicleSeqID");

                entity.HasOne(d => d.DeviceExperienceTypeCodeNavigation)
                    .WithMany(p => p.Participants)
                    .HasForeignKey(d => d.DeviceExperienceTypeCode)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Participant_DeviceExperienceTypeCode");

                entity.HasOne(d => d.ParticipantStatusCodeNavigation)
                    .WithMany(p => p.Participants)
                    .HasForeignKey(d => d.ParticipantStatusCode)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Participant_ParticipantStatus");

                entity.HasOne(d => d.PolicySeq)
                    .WithMany(p => p.Participants)
                    .HasForeignKey(d => d.PolicySeqId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Participant_Policy");

                entity.HasOne(d => d.VehicleSeq)
                    .WithMany(p => p.Participants)
                    .HasForeignKey(d => d.VehicleSeqId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Participant_Vehicle");
            });

            modelBuilder.Entity<ParticipantHistory>(entity =>
            {
                entity.HasKey(e => e.ParticipantHistorySeqId);

                entity.ToTable("ParticipantHistory", "dbo");

                entity.Property(e => e.ParticipantHistorySeqId).HasColumnName("ParticipantHistorySeqID");

                entity.Property(e => e.CreateDateTime)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.DashboardEnrollmentDateTime).HasColumnType("datetime");

                entity.Property(e => e.DeviceSeqId).HasColumnName("DeviceSeqID");

                entity.Property(e => e.LastUpdateDateTime).HasColumnType("datetime");

                entity.Property(e => e.ParticipantId)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("ParticipantID");

                entity.Property(e => e.ParticipantSeqId).HasColumnName("ParticipantSeqID");

                entity.Property(e => e.PolicySeqId).HasColumnName("PolicySeqID");

                entity.Property(e => e.VehicleSeqId).HasColumnName("VehicleSeqID");

                entity.HasOne(d => d.ParticipantSeq)
                    .WithMany(p => p.ParticipantHistories)
                    .HasForeignKey(d => d.ParticipantSeqId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_ParticipantHistory_Participant");
            });

            modelBuilder.Entity<ParticipantStatus>(entity =>
            {
                entity.HasKey(e => e.Code);

                entity.ToTable("ParticipantStatus", "dbo");

                entity.HasIndex(e => e.Description, "IX_ParticipantStatus_Description")
                    .IsUnique()
                    .HasFillFactor(90);

                entity.Property(e => e.Code).ValueGeneratedNever();

                entity.Property(e => e.CreateDateTime)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.Description)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<Policy>(entity =>
            {
                entity.HasKey(e => e.PolicySeqId);

                entity.ToTable("Policy", "dbo");

                entity.HasIndex(e => e.PolicyNumber, "IX_Policy_PolicyNumber")
                    .IsUnique();

                entity.Property(e => e.PolicySeqId).HasColumnName("PolicySeqID");

                entity.Property(e => e.Address1)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.Address2)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.City)
                    .IsRequired()
                    .HasMaxLength(25)
                    .IsUnicode(false);

                entity.Property(e => e.CreateDateTime)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.EmailAddress)
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.LastChangeDateTime)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.MailingState)
                    .HasMaxLength(2)
                    .IsUnicode(false)
                    .IsFixedLength();

                entity.Property(e => e.Name)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.PolicyNumber)
                    .IsRequired()
                    .HasMaxLength(20)
                    .IsUnicode(false);

                entity.Property(e => e.State)
                    .IsRequired()
                    .HasMaxLength(2)
                    .IsUnicode(false)
                    .IsFixedLength();

                entity.Property(e => e.ZipCode)
                    .IsRequired()
                    .HasMaxLength(5)
                    .IsUnicode(false)
                    .IsFixedLength();
            });

            modelBuilder.Entity<SummarizationMethod>(entity =>
            {
                entity.HasKey(e => e.Code);

                entity.ToTable("SummarizationMethod", "dbo");

                entity.Property(e => e.Code).ValueGeneratedNever();

                entity.Property(e => e.CreateDateTime)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.Description)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.IsActive)
                    .IsRequired()
                    .HasDefaultValueSql("((1))");
            });

            modelBuilder.Entity<Trip>(entity =>
            {
                entity.HasKey(e => e.TripSeqId);

                entity.ToTable("Trip", "dbo");

                entity.HasIndex(e => e.CreateDateTime, "IX_Trip_CreateDateTime")
                    .HasFillFactor(90);

                entity.HasIndex(e => new { e.ParticipantSeqId, e.TripStartDateTime }, "IX_Trip_ParticipantSeqID_TripStartDateTime")
                    .IsUnique();

                entity.Property(e => e.TripSeqId).HasColumnName("TripSeqID");

                entity.Property(e => e.CreateDateTime)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.DeviceSeqId).HasColumnName("DeviceSeqID");

                entity.Property(e => e.ExternalTripId)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.HardAccelerationV2count).HasColumnName("HardAccelerationV2Count");

                entity.Property(e => e.HardBrakeV2count).HasColumnName("HardBrakeV2Count");

                entity.Property(e => e.MaxSpeedKph).HasColumnName("MaxSpeedKPH");

                entity.Property(e => e.MilesSinceCheckEngineLightReset).HasColumnType("decimal(9, 2)");

                entity.Property(e => e.ParticipantSeqId).HasColumnName("ParticipantSeqID");

                entity.Property(e => e.RecordedWithGps).HasColumnName("RecordedWithGPS");

                entity.Property(e => e.ReportedVehicleVin)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("ReportedVehicleVIN");

                entity.Property(e => e.TripEndDateTime).HasColumnType("datetime");

                entity.Property(e => e.TripKilometers).HasColumnType("decimal(9, 2)");

                entity.Property(e => e.TripStartDateTime).HasColumnType("datetime");

                entity.Property(e => e.VehicleSeqId).HasColumnName("VehicleSeqID");

                entity.HasOne(d => d.ParticipantSeq)
                    .WithMany(p => p.Trips)
                    .HasForeignKey(d => d.ParticipantSeqId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Trip_Participant");

                entity.HasOne(d => d.UnreasonableTripCodeNavigation)
                    .WithMany(p => p.Trips)
                    .HasForeignKey(d => d.UnreasonableTripCode)
                    .HasConstraintName("FK_Trip_UnreasonableTrip");

                entity.HasOne(d => d.VehicleSeq)
                    .WithMany(p => p.Trips)
                    .HasForeignKey(d => d.VehicleSeqId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Trip_Vehicle");
            });

            modelBuilder.Entity<TripDetailSmoothingAudit>(entity =>
            {
                entity.HasKey(e => e.SmoothingSeqId);

                entity.ToTable("TripDetail_SmoothingAudit", "dbo");

                entity.HasIndex(e => new { e.TripSeqId, e.BaseElapsedTimeMilliSeconds }, "IX_TripDetail_SmoothingAudit_TripSeqID_BaseElapsedTime");

                entity.Property(e => e.SmoothingSeqId).HasColumnName("SmoothingSeqID");

                entity.Property(e => e.BaseSpeedKph).HasColumnName("BaseSpeedKPH");

                entity.Property(e => e.CreateDate)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.NextSpeedKph).HasColumnName("NextSpeedKPH");

                entity.Property(e => e.PriorSpeedKph).HasColumnName("PriorSpeedKPH");

                entity.Property(e => e.SmoothedSpeedKph).HasColumnName("SmoothedSpeedKPH");

                entity.Property(e => e.TripSeqId).HasColumnName("TripSeqID");
            });

            modelBuilder.Entity<TripDetailSmoothingAuditType>(entity =>
            {
                entity.HasKey(e => e.Code)
                    .HasName("PK_SmoothingAuditTypeID");

                entity.ToTable("TripDetail_SmoothingAuditType", "dbo");

                entity.HasIndex(e => e.Name, "IX_SmoothingAuditType_Name")
                    .IsUnique();

                entity.Property(e => e.Code).ValueGeneratedNever();

                entity.Property(e => e.CreateDateTime)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.Description)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.IsActive)
                    .IsRequired()
                    .HasDefaultValueSql("((1))");

                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<TripEvent>(entity =>
            {
                entity.HasKey(e => new { e.TripSeqId, e.TripEventSeqId })
                    .HasName("PK_Ubi_TripEvent");

                entity.ToTable("TripEvent", "dbo");

                entity.Property(e => e.TripSeqId).HasColumnName("TripSeqID");

                entity.Property(e => e.TripEventSeqId).HasColumnName("TripEventSeqID");

                entity.Property(e => e.EventTimeZoneOffsetNbr)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.EventTimestamp).HasColumnType("decimal(18, 7)");

                entity.Property(e => e.LatitudeDeltaNbr).HasColumnType("decimal(9, 6)");

                entity.Property(e => e.LatitudeNbr).HasColumnType("decimal(9, 6)");

                entity.Property(e => e.LongitudeDeltaNbr).HasColumnType("decimal(9, 6)");

                entity.Property(e => e.LongitudeNbr).HasColumnType("decimal(9, 6)");

                entity.Property(e => e.SpeedKph).HasColumnName("SpeedKPH");

                entity.Property(e => e.TripEventDateTime).HasColumnType("datetime");

                entity.HasOne(d => d.TripEventTypeCodeNavigation)
                    .WithMany(p => p.TripEvents)
                    .HasForeignKey(d => d.TripEventTypeCode)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_TripEvent_TripEventType");

                entity.HasOne(d => d.TripSeq)
                    .WithMany(p => p.TripEvents)
                    .HasForeignKey(d => d.TripSeqId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_TripEvent_Trip");
            });

            modelBuilder.Entity<TripEventType>(entity =>
            {
                entity.HasKey(e => e.Code)
                    .HasName("PK_EventTypeID");

                entity.ToTable("TripEventType", "dbo");

                entity.HasIndex(e => e.Name, "IX_TripEventType_Name")
                    .IsUnique();

                entity.Property(e => e.Code).ValueGeneratedNever();

                entity.Property(e => e.CreateDateTime)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.Description)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.IsActive)
                    .IsRequired()
                    .HasDefaultValueSql("((1))");

                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<UnreasonableTrip>(entity =>
            {
                entity.HasKey(e => e.Code);

                entity.ToTable("UnreasonableTrip", "dbo");

                entity.HasIndex(e => e.Code, "IX_UnreasonableTrip_Code")
                    .IsUnique();

                entity.Property(e => e.Code).ValueGeneratedNever();

                entity.Property(e => e.CreateDateTime)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.Description)
                    .IsRequired()
                    .HasMaxLength(200)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<UnreasonableTripEvent>(entity =>
            {
                entity.HasKey(e => new { e.TripSeqId, e.EventSeqId });

                entity.ToTable("UnreasonableTripEvent", "dbo");

                entity.Property(e => e.TripSeqId).HasColumnName("TripSeqID");

                entity.Property(e => e.EventSeqId).HasColumnName("EventSeqID");

                entity.Property(e => e.EventDateTime).HasColumnType("datetime");

                entity.Property(e => e.EventTypeSeqId).HasColumnName("EventTypeSeqID");

                entity.HasOne(d => d.TripSeq)
                    .WithMany(p => p.UnreasonableTripEvents)
                    .HasForeignKey(d => d.TripSeqId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_UnreasonableTripEvent_TripSummary_TripSeqID");
            });

            modelBuilder.Entity<UnreasonableTripEventCode>(entity =>
            {
                entity.HasKey(e => e.Code);

                entity.ToTable("UnreasonableTripEventCode", "dbo");

                entity.HasIndex(e => e.Description, "IX_UnreasonableTripEventCode_Description")
                    .IsUnique();

                entity.Property(e => e.CreateDateTime)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.Description)
                    .IsRequired()
                    .HasMaxLength(200)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<Vehicle>(entity =>
            {
                entity.HasKey(e => e.VehicleSeqId);

                entity.ToTable("Vehicle", "dbo");

                entity.Property(e => e.VehicleSeqId).HasColumnName("VehicleSeqID");

                entity.Property(e => e.CableType)
                    .HasMaxLength(20)
                    .IsUnicode(false);

                entity.Property(e => e.CreateDateTime)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.Make)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.Model)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.VehicleExternalId)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.Vin)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("VIN");
            });

            modelBuilder.Entity<VehicleProtocol>(entity =>
            {
                entity.HasKey(e => e.Code);

                entity.ToTable("VehicleProtocol", "dbo");

                entity.HasIndex(e => e.Description, "IX_VehicleProtocol_Description")
                    .IsUnique();

                entity.Property(e => e.Code).ValueGeneratedNever();

                entity.Property(e => e.CreateDateTime)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.Description)
                    .IsRequired()
                    .HasMaxLength(255)
                    .IsUnicode(false);

                entity.Property(e => e.IsActive)
                    .IsRequired()
                    .HasDefaultValueSql("((1))");
            });

        OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
