//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFGetCodeTablesService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCFGetCodeTablesService.IGetCodeTablesService")]
    public interface IGetCodeTablesService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGetCodeTablesService/GetCodeTables", ReplyAction="http://tempuri.org/IGetCodeTablesService/GetCodeTablesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UBIServiceResponse))]
        System.Threading.Tasks.Task<WCFGetCodeTablesService.GetCodeTablesResponse1> GetCodeTablesAsync(WCFGetCodeTablesService.GetCodeTablesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGetCodeTablesService/RefreshCodeTableCache", ReplyAction="http://tempuri.org/IGetCodeTablesService/RefreshCodeTableCacheResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(UBIServiceResponse))]
        System.Threading.Tasks.Task<bool> RefreshCodeTableCacheAsync();
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/TrialBusiness.Commands.CodeTables.Get.Con" +
        "tract")]
    public partial class GetCodeTablesResponse : UBIServiceResponse
    {
        
        private System.Xml.XmlElement codeTableDataSetField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Xml.XmlElement CodeTableDataSet
        {
            get
            {
                return this.codeTableDataSetField;
            }
            set
            {
                this.codeTableDataSetField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetCodeTablesResponse))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Progressive.UBI.Shared.UBIServicesLib")]
    public partial class UBIServiceResponse
    {
        
        private ResponseError[] responseErrorsField;
        
        private ResponseStatus responseStatusField;
        
        private int versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=0)]
        public ResponseError[] ResponseErrors
        {
            get
            {
                return this.responseErrorsField;
            }
            set
            {
                this.responseErrorsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ResponseStatus ResponseStatus
        {
            get
            {
                return this.responseStatusField;
            }
            set
            {
                this.responseStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int Version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Progressive.UBI.Shared.UBIServicesLib")]
    public partial class ResponseError
    {
        
        private string errorCodeField;
        
        private string fieldField;
        
        private string messageField;
        
        private ErrorSeverityCode severityCodeField;
        
        private bool severityCodeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string ErrorCode
        {
            get
            {
                return this.errorCodeField;
            }
            set
            {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string Field
        {
            get
            {
                return this.fieldField;
            }
            set
            {
                this.fieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string Message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public ErrorSeverityCode SeverityCode
        {
            get
            {
                return this.severityCodeField;
            }
            set
            {
                this.severityCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SeverityCodeSpecified
        {
            get
            {
                return this.severityCodeFieldSpecified;
            }
            set
            {
                this.severityCodeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Progressive.UBI.Shared.UBIServicesLib")]
    public enum ErrorSeverityCode
    {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        Warning,
        
        /// <remarks/>
        Validation,
        
        /// <remarks/>
        Error,
        
        /// <remarks/>
        Exception,
        
        /// <remarks/>
        Ticket,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Progressive.UBI.Shared.UBIServicesLib")]
    public enum ResponseStatus
    {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        Success,
        
        /// <remarks/>
        Failure,
        
        /// <remarks/>
        SuccessWithWarning,
        
        /// <remarks/>
        FailureWithWarning,
        
        /// <remarks/>
        PartialSuccess,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCodeTables", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCodeTablesRequest
    {
        
        public GetCodeTablesRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCodeTablesResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCodeTablesResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public WCFGetCodeTablesService.GetCodeTablesResponse GetCodeTablesResult;
        
        public GetCodeTablesResponse1()
        {
        }
        
        public GetCodeTablesResponse1(WCFGetCodeTablesService.GetCodeTablesResponse GetCodeTablesResult)
        {
            this.GetCodeTablesResult = GetCodeTablesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface IGetCodeTablesServiceChannel : WCFGetCodeTablesService.IGetCodeTablesService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class GetCodeTablesServiceClient : System.ServiceModel.ClientBase<WCFGetCodeTablesService.IGetCodeTablesService>, WCFGetCodeTablesService.IGetCodeTablesService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public GetCodeTablesServiceClient() : 
                base(GetCodeTablesServiceClient.GetDefaultBinding(), GetCodeTablesServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IGetCodeTablesService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GetCodeTablesServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(GetCodeTablesServiceClient.GetBindingForEndpoint(endpointConfiguration), GetCodeTablesServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GetCodeTablesServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(GetCodeTablesServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GetCodeTablesServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(GetCodeTablesServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GetCodeTablesServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WCFGetCodeTablesService.GetCodeTablesResponse1> WCFGetCodeTablesService.IGetCodeTablesService.GetCodeTablesAsync(WCFGetCodeTablesService.GetCodeTablesRequest request)
        {
            return base.Channel.GetCodeTablesAsync(request);
        }
        
        public System.Threading.Tasks.Task<WCFGetCodeTablesService.GetCodeTablesResponse1> GetCodeTablesAsync()
        {
            WCFGetCodeTablesService.GetCodeTablesRequest inValue = new WCFGetCodeTablesService.GetCodeTablesRequest();
            return ((WCFGetCodeTablesService.IGetCodeTablesService)(this)).GetCodeTablesAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<bool> RefreshCodeTableCacheAsync()
        {
            return base.Channel.RefreshCodeTableCacheAsync();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IGetCodeTablesService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IGetCodeTablesService))
            {
                return new System.ServiceModel.EndpointAddress("http://t-ubi-trial-services/TrialBusiness/Services/CodeTables/GetCodeTablesServic" +
                        "e.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return GetCodeTablesServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IGetCodeTablesService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return GetCodeTablesServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IGetCodeTablesService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IGetCodeTablesService,
        }
    }
}
